/**
 * Arabic dictionary for the management console.
 *
 * Typed as `ConsoleCopy`, so a key missing here is a build error rather than
 * a blank label — FR-LOC-006. Modern Standard Arabic throughout, not a
 * regional dialect (FR-LOC-002).
 */

import type { ConsoleCopy } from "./en";

export const consoleAr: ConsoleCopy = {
  // -- Product and chrome --------------------------------------------------
  "app.name": "TRENDOW",
  "app.subtitle": "نظام تشغيل المطاعم",
  "app.console": "وحدة تحكم الإدارة",
  "app.skipToContent": "تخطَّ إلى المحتوى",

  // -- Authentication ------------------------------------------------------
  "auth.signIn": "تسجيل الدخول",
  "auth.signInTitle": "تسجيل الدخول إلى TRENDOW",
  "auth.signInLede": "وحدة تحكم إدارة عمليات المطاعم. نسخة تجريبية — لا تُرسل أي بيانات اعتماد إلى أي جهة.",
  "auth.email": "البريد الإلكتروني",
  "auth.password": "كلمة المرور",
  "auth.emailPlaceholder": "you@restaurant.example",
  "auth.forgot": "هل نسيت كلمة المرور؟",
  "auth.remember": "أبقني مسجّلًا على هذا الجهاز",
  "auth.signingIn": "جارٍ تسجيل الدخول",
  "auth.signOut": "تسجيل الخروج",
  "auth.demoRole": "الدخول بصفة",
  "auth.demoRoleHint": "اختر دورًا. يتغير التنقل والإجراءات ونطاق البيانات وفقًا لصلاحياته.",
  "auth.errorRequired": "أدخل البريد الإلكتروني وكلمة المرور.",
  "auth.errorInvalid": "لم يتم التعرف على هذا البريد مع كلمة المرور.",
  "auth.mfaTitle": "المصادقة الثنائية",
  "auth.mfaLede": "أدخل الرمز المكوّن من ستة أرقام من تطبيق المصادقة.",
  "auth.mfaRequired": "يحمل هذا الدور صلاحيات حسّاسة، لذا فالمصادقة الثنائية إلزامية.",
  "auth.mfaCode": "رمز التحقق",
  "auth.mfaVerify": "تحقّق",
  "auth.mfaVerifying": "جارٍ التحقق",
  "auth.mfaResend": "أرسل رمزًا جديدًا",
  "auth.mfaHint": "أي ستة أرقام تفي بالغرض في هذه النسخة التجريبية.",
  "auth.mfaError": "أدخل الأرقام الستة كاملة.",
  "auth.mfaBack": "استخدام حساب آخر",
  "auth.pinNote": "مصادقة رمز PIN مرتبطة بالجهاز ولا تمنح الوصول إلى لوحة التحكم أبدًا.",
  "auth.notSignedIn": "لم تسجّل الدخول.",
  "auth.liveApi": "تسجيل الدخول إلى الخادم المباشر على",
  "auth.mustReset": "يجب على هذا الحساب تعيين كلمة مرور جديدة قبل تسجيل الدخول التالي.",
  "auth.chooseTenant": "اختر المنشأة",
  "auth.chooseTenantHint": "هذا الحساب يعمل لأكثر من منشأة. لا تُقرأ أي بيانات قبل اختيار واحدة.",
  "auth.errorNetwork": "لم يستجب الخادم. تحقّق من عنوان الواجهة ومن إمكانية الوصول إليه من هذا الجهاز.",

  // -- Navigation ----------------------------------------------------------
  "nav.dashboard": "لوحة المعلومات",
  "nav.operations": "الطلبات والعمليات",
  "nav.orders": "الطلبات",
  "nav.openOrders": "الطلبات المفتوحة",
  "nav.tables": "حالة الطاولات",
  "nav.kitchen": "طابور المطبخ",
  "nav.terminals": "الأجهزة",
  "nav.menu": "القائمة والوصفات",
  "nav.categories": "الفئات",
  "nav.items": "الأصناف",
  "nav.modifiers": "الإضافات",
  "nav.combos": "الوجبات المركّبة",
  "nav.pricing": "التسعير",
  "nav.recipes": "الوصفات",
  "nav.inventory": "المخزون",
  "nav.stockLevels": "مستويات المخزون",
  "nav.stockItems": "أصناف المخزون",
  "nav.counts": "الجرد",
  "nav.transfers": "التحويلات",
  "nav.batches": "الدفعات",
  "nav.expiry": "الصلاحية",
  "nav.waste": "الهدر",
  "nav.adjustments": "التسويات",
  "nav.movements": "الحركات",
  "nav.purchasing": "المشتريات",
  "nav.suppliers": "الموردون",
  "nav.requisitions": "طلبات الشراء",
  "nav.purchaseOrders": "أوامر الشراء",
  "nav.receiving": "الاستلام",
  "nav.invoices": "فواتير الموردين",
  "nav.costing": "التكلفة والربحية",
  "nav.foodCost": "تكلفة الطعام",
  "nav.variance": "النظري مقابل الفعلي",
  "nav.wasteAnalysis": "تحليل الهدر",
  "nav.margin": "هامش المساهمة",
  "nav.workforce": "القوى العاملة",
  "nav.employees": "الموظفون",
  "nav.schedules": "الجداول",
  "nav.attendance": "الحضور",
  "nav.overtime": "العمل الإضافي",
  "nav.performance": "الأداء",
  "nav.finance": "المالية",
  "nav.cashSessions": "جلسات النقد",
  "nav.expenses": "المصروفات",
  "nav.dayClose": "إغلاق اليوم",
  "nav.payments": "ملخص المدفوعات",
  "nav.tax": "ملخص الضريبة",
  "nav.organisation": "المنشأة",
  "nav.tenants": "المستأجرون",
  "nav.brands": "العلامات التجارية",
  "nav.branches": "الفروع",
  "nav.warehouses": "المستودعات",
  "nav.centralKitchens": "المطابخ المركزية",
  "nav.reports": "التقارير",
  "nav.approvals": "الاعتمادات",
  "nav.audit": "سجل التدقيق",
  "nav.users": "المستخدمون",
  "nav.roles": "الأدوار",
  "nav.settings": "الإعدادات",
  "nav.countryPacks": "حزم الدول",
  "nav.integrations": "التكاملات",
  "nav.governance": "الحوكمة",
  "nav.administration": "الإدارة",
  "nav.openMenu": "فتح التنقل",
  "nav.closeMenu": "إغلاق التنقل",
  "nav.collapse": "طيّ الشريط الجانبي",
  "nav.expand": "توسيع الشريط الجانبي",

  // -- Scope switcher ------------------------------------------------------
  "scope.tenant": "المستأجر",
  "scope.brand": "العلامة",
  "scope.branch": "الفرع",
  "scope.allBrands": "كل العلامات",
  "scope.allBranches": "كل الفروع",
  "scope.change": "تغيير النطاق",
  "scope.locked": "دورك مقيّد بهذا الموقع.",
  "scope.viewing": "المعروض",

  // -- Common actions and labels -------------------------------------------
  "common.search": "بحث",
  "common.searchPlaceholder": "ابحث…",
  "common.filter": "تصفية",
  "common.filters": "عوامل التصفية",
  "common.clearFilters": "مسح التصفية",
  "common.all": "الكل",
  "common.export": "تصدير",
  "common.exportCsv": "تصدير CSV",
  "common.refresh": "تحديث",
  "common.create": "إنشاء",
  "common.new": "جديد",
  "common.edit": "تعديل",
  "common.save": "حفظ",
  "common.saving": "جارٍ الحفظ",
  "common.cancel": "إلغاء",
  "common.close": "إغلاق",
  "common.delete": "حذف",
  "common.confirm": "تأكيد",
  "common.confirmDelete": "حذف هذا السجل؟",
  "common.confirmDeleteBody": "هذه نسخة تجريبية، فلا يغادر شيء المتصفح — لكن الصف سيختفي من هذه الجلسة.",
  "common.view": "عرض",
  "common.details": "التفاصيل",
  "common.back": "رجوع",
  "common.next": "التالي",
  "common.previous": "السابق",
  "common.of": "من",
  "common.showing": "عرض",
  "common.results": "نتيجة",
  "common.noResults": "لا نتائج",
  "common.uncategorised": "غير مصنّف",
  "common.rowsPerPage": "صفوف في الصفحة",
  "common.total": "الإجمالي",
  "common.subtotal": "المجموع الفرعي",
  "common.actions": "إجراءات",
  "common.status": "الحالة",
  "common.date": "التاريخ",
  "common.time": "الوقت",
  "common.name": "الاسم",
  "common.code": "الرمز",
  "common.value": "القيمة",
  "common.quantity": "الكمية",
  "common.unit": "الوحدة",
  "common.reason": "السبب",
  "common.notes": "ملاحظات",
  "common.branch": "الفرع",
  "common.brand": "العلامة",
  "common.location": "الموقع",
  "common.category": "الفئة",
  "common.reference": "المرجع",
  "common.target": "المستهدف",
  "common.actual": "الفعلي",
  "common.variance": "الفرق",
  "common.approve": "اعتماد",
  "common.reject": "رفض",
  "common.approved": "معتمد",
  "common.rejected": "مرفوض",
  "common.pending": "قيد الانتظار",
  "common.yes": "نعم",
  "common.no": "لا",
  "common.enabled": "مفعّل",
  "common.disabled": "معطّل",
  "common.active": "نشط",
  "common.inactive": "غير نشط",
  "common.today": "اليوم",
  "common.yesterday": "أمس",
  "common.last7": "آخر ٧ أيام",
  "common.last30": "آخر ٣٠ يومًا",
  "common.thisMonth": "هذا الشهر",
  "common.period": "الفترة",
  "common.vsPrevious": "مقارنة بالفترة السابقة",
  "common.updated": "آخر تحديث",
  "common.created": "أُنشئ",
  "common.by": "بواسطة",
  "common.at": "في",
  "common.none": "لا شيء",
  "common.unknown": "غير معروف",
  "common.required": "مطلوب",
  "common.optional": "اختياري",
  "common.copy": "نسخ",
  "common.copied": "تم النسخ",
  "common.moreFilters": "تصفية إضافية",
  "common.sortBy": "الترتيب حسب",
  "common.grouping": "التجميع حسب",
  "common.percentOfSales": "٪ من صافي المبيعات",
  "common.perUnit": "للوحدة",
  "common.spec": "مرجعه",

  // -- State panels --------------------------------------------------------
  "state.loading": "جارٍ التحميل",
  "state.loadingData": "جارٍ تحميل البيانات…",
  "state.emptyTitle": "لا يوجد شيء هنا بعد",
  "state.emptyBody": "لا توجد سجلات مطابقة للنطاق وعوامل التصفية الحالية.",
  "state.emptyAction": "مسح التصفية",
  "state.errorTitle": "تعذّر تحميل هذه البيانات",
  "state.errorRetry": "أعد المحاولة",
  "state.deniedTitle": "لا تملك صلاحية الوصول",
  "state.deniedBody": "تتطلب هذه الشاشة صلاحية لا يحملها دورك الحالي. بدّل الدور من قائمة الحساب لاستكشافها.",
  "state.deniedPermission": "الصلاحية المطلوبة",
  "state.notFoundTitle": "غير موجود",
  "state.notFoundBody": "هذا السجل غير موجود، أو غير ظاهر في نطاقك الحالي.",
  "state.unsupportedTitle": "غير متاح من هذا الخادم",
  "state.unsupportedBody": "واجهة البرمجة المتصلة لا توفّر هذا بعد. لا نعرض بيانات تجريبية بديلة، فما تراه هو ما لدى الخادم فقط.",
  "state.unsupportedDetail": "نقطة نهاية غير موجودة",
  "state.serverNote": "فحوص الصلاحيات في الواجهة للعرض فقط. الخادم هو من يطبّق القاعدة الفعلية في كل طلب.",

  // -- Theme, language, account -------------------------------------------
  "pref.theme": "المظهر",
  "pref.light": "فاتح",
  "pref.dark": "داكن",
  "pref.system": "حسب النظام",
  "pref.language": "اللغة",
  "pref.numerals": "الأرقام",
  "pref.numeralsWestern": "غربية (0–9)",
  "pref.numeralsArabic": "عربية هندية (٠–٩)",
  "pref.toggleTheme": "تبديل المظهر",
  "pref.account": "الحساب",
  "pref.switchRole": "تبديل الدور التجريبي",
  "pref.profile": "الملف الشخصي",
  "pref.role": "الدور",
  "pref.permissions": "صلاحية",

  // -- Dashboard -----------------------------------------------------------
  "dash.title": "لوحة المعلومات",
  "dash.subtitle": "الاستثناء قبل التعداد. كل رقم يُفتح على المعاملات التي أنتجته.",
  "dash.activityTitle": "نشاط الطلبات",
  "dash.activityHint": "مُصفّى مباشرة من الطلبات الفعلية — غيّر أي فلتر وستُعاد حساب كل رقم أدناه من نفس السجلات.",
  "dash.grossSales": "إجمالي المبيعات",
  "dash.totalOrders": "إجمالي الطلبات",
  "dash.openShifts": "الورديات المفتوحة",
  "dash.closedShifts": "الورديات المغلقة",
  "dash.cashDrawerDiff": "فرق درج النقدية",
  "dash.offlineOrders": "الطلبات دون اتصال",
  "dash.pendingSyncOrders": "طلبات بانتظار المزامنة",
  "dash.syncedOfflineOrders": "طلبات دون اتصال تمت مزامنتها",
  "dash.byCashier": "المبيعات حسب الكاشير",
  "dash.byBranch": "المبيعات حسب الفرع",
  "dash.byCategory": "المبيعات حسب الفئة",
  "dash.bestSelling": "الأصناف الأكثر مبيعًا",
  "dash.lowestSelling": "الأصناف الأقل مبيعًا",
  "dash.ordersByHour": "الطلبات حسب الساعة",
  "dash.netSales": "صافي المبيعات",
  "dash.transactions": "عدد المعاملات",
  "dash.aov": "متوسط قيمة الطلب",
  "dash.foodCost": "تكلفة الطعام",
  "dash.labourCost": "تكلفة العمالة",
  "dash.primeCost": "التكلفة الأولية",
  "dash.waste": "الهدر",
  "dash.grossProfit": "إجمالي الربح",
  "dash.salesTrend": "صافي المبيعات، آخر ١٤ يومًا",
  "dash.salesTrendHint": "خط المقارنة هو اليوم نفسه من الفترة السابقة.",
  "dash.hourly": "المبيعات بالساعة مع تكلفة العمالة",
  "dash.hourlyHint": "المبيعات والعمالة على محور واحد، ليظهر فائض أو نقص التوظيف بالساعة.",
  "dash.categoryMix": "مزيج الفئات",
  "dash.branchRanking": "ترتيب الفروع",
  "dash.branchRankingHint": "مرتب حسب صافي المبيعات. الفروع الشاذة تتجاوز ١٫٥ انحراف معياري عن متوسط المجموعة في التكلفة الأولية.",
  "dash.alerts": "التنبيهات",
  "dash.alertsHint": "محدودة المعدل وغير مكررة لكل مستلم ونوع وفترة.",
  "dash.wasteByReason": "الهدر حسب السبب",
  "dash.profitability": "الربحية",
  "dash.live": "العمليات المباشرة",
  "dash.dataAsOf": "البيانات حتى",
  "dash.partialDay": "اليوم جزئي — لم يُغلق يوم العمل بعد.",
  "dash.noAlerts": "لا تنبيهات مفتوحة في هذا النطاق.",
  "dash.viewAll": "عرض الكل",
  "dash.acknowledge": "إقرار",
  "dash.rank": "الترتيب",
  "dash.outlier": "شاذ",
  "dash.prime": "الأولية",

  "pl.grossSales": "إجمالي المبيعات",
  "pl.discounts": "الخصومات",
  "pl.refunds": "المرتجعات",
  "pl.netSales": "صافي المبيعات (بدون ضريبة)",
  "pl.cogs": "تكلفة البضاعة المباعة",
  "pl.grossProfit": "إجمالي الربح",
  "pl.labour": "تكلفة العمالة",
  "pl.contribution": "المساهمة بعد العمالة",
  "pl.opex": "المصروفات التشغيلية",
  "pl.operatingProfit": "الربح التشغيلي للفرع",

  "live.openOrders": "طلبات مفتوحة",
  "live.tables": "طاولات مشغولة",
  "live.queue": "طابور المطبخ",
  "live.avgWait": "متوسط الانتظار",
  "live.terminals": "أجهزة نشطة",
  "live.staff": "موظفون في الوردية",
  "live.delayed": "تذاكر متأخرة",
  "live.syncBacklog": "تراكم المزامنة",
  "live.operations": "عملية",

  // -- Orders --------------------------------------------------------------
  "orders.title": "الطلبات",
  "orders.subtitle": "كل طلب مكتمل غير قابل للتعديل. التصحيحات مرتجعات تشير إليه.",
  "orders.number": "الطلب",
  "orders.type": "النوع",
  "orders.channel": "القناة",
  "orders.table": "الطاولة",
  "orders.guests": "عدد الضيوف",
  "orders.server": "النادل",
  "orders.opened": "فُتح",
  "orders.completed": "اكتمل",
  "orders.sync": "المزامنة",
  "orders.syncedAt": "وقت المزامنة",
  "orders.terminal": "الجهاز",
  "orders.customer": "العميل",
  "orders.lines": "الأصناف",
  "orders.payments": "المدفوعات",
  "orders.tender": "وسيلة الدفع",
  "orders.cogs": "تكلفة البضاعة",
  "orders.margin": "الهامش",
  "orders.paid": "المدفوع",
  "orders.tip": "الإكرامية",
  "orders.serviceCharge": "رسوم الخدمة",
  "orders.rounding": "تقريب نقدي",
  "orders.tax": "الضريبة",
  "orders.syncState": "المزامنة",
  "orders.aggregatorRef": "مرجع المنصة",
  "orders.detailTitle": "تفاصيل الطلب",
  "orders.timeline": "التسلسل الزمني",
  "orders.snapshotNote": "اسم الصنف والسعر وفئة الضريبة والتكلفة تُلتقط لحظة البيع ولا يُعاد حسابها.",
  "orders.course": "الطبق",
  "orders.seat": "المقعد",
  "orders.voidReason": "سبب الإلغاء",
  "orders.comp": "مجاني",
  "orders.cancelled": "ملغى",
  "orders.cancelledAt": "وقت الإلغاء",
  "orders.cancelledBy": "ألغاه",
  "orders.cancelReason": "سبب الإلغاء",
  "orders.originalTotal": "الإجمالي الأصلي",
  "orders.paymentStatus": "حالة الدفع",
  "orders.neverCharged": "لم يُحصَّل",
  "orders.refunded": "مسترد",
  "orders.partiallyRefunded": "مسترد جزئيًا",
  "orders.refundPending": "الاسترداد معلّق",
  "orders.refundAmount": "مبلغ الاسترداد",
  "orders.discountsApplied": "الخصومات المطبقة",
  "orders.appliedBy": "طبّقه",
  "orders.approvedBy": "اعتمده",
  "orders.openOrdersTitle": "الطلبات المفتوحة",
  "orders.openOrdersSubtitle": "الطلبات التي ما زالت في الصالة: مسودات ومعلّقة ومركونة ومدفوعة جزئيًا.",

  "tables.title": "حالة الطاولات",
  "tables.subtitle": "حالة الصالة المباشرة لكل فرع، مع زمن الجلوس.",
  "tables.area": "المنطقة",
  "tables.capacity": "السعة",
  "tables.seatedFor": "الجلوس منذ",
  "tables.occupancy": "نسبة الإشغال",
  "tables.free": "متاحة",
  "tables.selectBranch": "اختر فرعًا واحدًا لعرض مخطط صالته.",

  "kitchen.title": "طابور المطبخ",
  "kitchen.subtitle": "ما تنظر إليه المحطات الآن، ملوّنًا حسب الزمن المنقضي مقابل المستهدف.",
  "kitchen.station": "المحطة",
  "kitchen.elapsed": "المنقضي",
  "kitchen.targetTime": "المستهدف",
  "kitchen.priority": "الأولوية",
  "kitchen.queueDepth": "عمق الطابور",
  "kitchen.throughput": "السعة / ساعة",
  "kitchen.bottleneck": "الاختناق",
  "kitchen.byStation": "حسب المحطة",
  "kitchen.allTickets": "كل التذاكر",
  "kitchen.noTickets": "لا توجد تذاكر مباشرة في هذا النطاق.",

  "terminals.title": "الأجهزة",
  "terminals.subtitle": "التسجيل والإصدار وآخر اتصال وعمق صندوق الصادر لكل جهاز.",
  "terminals.lastSeen": "آخر ظهور",
  "terminals.version": "إصدار التطبيق",
  "terminals.queued": "عمليات في الطابور",
  "terminals.battery": "البطارية",
  "terminals.ip": "عنوان IP",
  "terminals.kind": "النوع",
  "terminals.revoke": "إلغاء التسجيل",
  "terminals.offlineNote": "الجهاز غير المتصل يواصل البيع. الطابور هو العمل المنتظر للمزامنة، لا مبيعات مفقودة.",
  "terminals.online": "متصل",
  "terminals.notOnline": "غير متصل أو متدهور",
  "terminals.queuedHint": "عمليات كُتبت محليًا وتنتظر الإرسال. الطابور القصير طبيعي، أما الطويل فيعني أن أرقام لوحة التحكم متأخرة عن الصالة.",
  "terminals.versionSpread": "إصدارات التطبيق المستخدمة",
  "terminals.versionHint": "تعدد الإصدارات أثناء الطرح متوقع، واستمراره مشكلة — فحل التعارضات يفترض أن الطرفين يفهمان المخطط نفسه.",
  "terminals.registrationNote": "التسجيل لكل جهاز على حدة، فإلغاء جهاز لوحي مفقود لا يستلزم تغيير كلمة مرور أحد.",

  // -- Menu ----------------------------------------------------------------
  "menu.categoriesTitle": "الفئات",
  "menu.categoriesSubtitle": "تسلسل القائمة: قائمة ← فئة ← صنف ← متغيّر.",
  "menu.itemsTitle": "أصناف القائمة",
  "menu.itemsSubtitle": "الأسماء قابلة للضبط لكل سطح عرض، لأن الاسم المناسب يختلف بحسب السياق.",
  "menu.modifiersTitle": "مجموعات الإضافات",
  "menu.modifiersSubtitle": "تحمل الإضافة فرق سعر وفرق وصفة. برجر «بدون جبنة» لا يستهلك جبنة.",
  "menu.combosTitle": "الوجبات المركّبة",
  "menu.combosSubtitle": "وجبات قائمة على خانات مع استراتيجية تسعير قابلة للضبط.",
  "menu.pricingTitle": "قوائم الأسعار",
  "menu.pricingSubtitle": "النطاق ونافذة الصلاحية والتكرار والأولوية. الأولوية الأعلى تفوز.",
  "menu.itemName": "الصنف",
  "menu.kitchenName": "اسم المطبخ",
  "menu.receiptName": "اسم الإيصال",
  "menu.variants": "المتغيّرات",
  "menu.price": "السعر",
  "menu.taxClass": "فئة الضريبة",
  "menu.station": "المحطة",
  "menu.prepTime": "زمن التحضير",
  "menu.availability": "التوفر",
  "menu.available": "متوفر",
  "menu.unavailable": "غير متوفر",
  "menu.remainingSellable": "الكمية القابلة للبيع",
  "menu.remainingHint": "الحد الأدنى عبر المكونات من المخزون المتاح مقسومًا على الكمية لكل حصة.",
  "menu.allergens": "المواد المسببة للحساسية",
  "menu.toggle86": "وضعه كغير متوفر",
  "menu.toggleAvailable": "إعادته كمتوفر",
  "menu.86Reason": "سبب جعله غير متوفر",
  "menu.sortOrder": "ترتيب العرض",
  "menu.itemCount": "الأصناف",
  "menu.minMax": "الأدنى / الأقصى",
  "menu.required": "إلزامي",
  "menu.attachedItems": "الأصناف المرتبطة",
  "menu.priceDelta": "فرق السعر",
  "menu.recipeDelta": "فرق الوصفة",
  "menu.modifierKind": "النوع",
  "menu.slots": "الخانات",
  "menu.strategy": "استراتيجية التسعير",
  "menu.scope": "النطاق",
  "menu.priority": "الأولوية",
  "menu.validity": "الصلاحية",
  "menu.recurrence": "التكرار",
  "menu.orderTypes": "أنواع الطلبات",
  "menu.entries": "المدخلات",
  "menu.searchPlaceholder": "ابحث بالصنف أو اسم المطبخ أو الوصف",
  "menu.categoriesEmpty": "فئة بلا أصناف",
  "menu.openPrice": "سعر مفتوح",
  "menu.weighed": "يباع بالوزن",
  "menu.lowRemaining": "أوشك على النفاد",
  "menu.restored": "أصبح الصنف متاحًا من جديد",
  "menu.eightySixed": "تم تعليم الصنف كغير متاح",
  "menu.86Placeholder": "نفد صدر الدجاج؛ متوقع توفره غدًا",
  "menu.modifierCount": "الإضافات",
  "menu.requiredGroups": "إلزامية",
  "menu.withRecipeDelta": "مجموعات تؤثر على المخزون",
  "menu.recipeDeltaHint": "الإضافة المرتبطة بفارق في الوصفة تغيّر ما يخصم من المخزون — «بدون جبن» يعيد الجبن للمخزون، و«جبن إضافي» يخصم أكثر.",
  "menu.allowRepeat": "يسمح بالتكرار",
  "menu.freeThreshold": "مجاني حتى",
  "menu.default": "افتراضي",
  "menu.deltaAdd": "يضيف إلى الوصفة",
  "menu.deltaRemoveAll": "يحذف المكوّن بالكامل",
  "menu.deltaScale": "يغيّر كمية المكوّن",
  "menu.noSurcharge": "بدون فرق سعر",
  "menu.priorityHint": "عند تغطية أكثر من قائمة للصنف نفسه في اللحظة نفسها، تُطبَّق القائمة ذات الأولوية الأعلى.",
  "menu.precedenceNote": "يتبع تحديد السعر المتطلب FR-POS-040: من بين القوائم السارية على الصنف ونوع الطلب والنطاق، يأخذ الجهاز القائمة ذات الأولوية الأعلى.",
  "menu.previousPrice": "السعر السابق",
  "menu.noEntries": "لا تحتوي هذه القائمة على أي أصناف.",

  // -- Recipes -------------------------------------------------------------
  "recipes.title": "الوصفات",
  "recipes.subtitle": "حيث يلتقي العالم القابل للبيع بالعالم المادي. مُصدَّرة بنسخ، والطلبات المكتملة تحتفظ بنسختها.",
  "recipes.type": "النوع",
  "recipes.version": "النسخة",
  "recipes.yield": "الناتج",
  "recipes.yieldPercent": "نسبة الناتج",
  "recipes.cost": "التكلفة",
  "recipes.costPerPortion": "التكلفة لكل حصة",
  "recipes.sellingPrice": "سعر البيع",
  "recipes.marginPercent": "نسبة الهامش",
  "recipes.components": "المكوّنات",
  "recipes.component": "المكوّن",
  "recipes.wastage": "فاقد التجهيز",
  "recipes.lineCost": "تكلفة السطر",
  "recipes.instructions": "التعليمات",
  "recipes.incomplete": "الوصفة غير مكتملة",
  "recipes.incompleteBody": "يمكن بيع هذا الصنف رغم ذلك. تُسجَّل التكلفة صفرًا ويظهر الصنف في تقرير الوصفات التي تحتاج استكمالًا.",
  "recipes.publish": "نشر النسخة",
  "recipes.costBreakdown": "تفصيل التكلفة",
  "recipes.subRecipe": "وصفة فرعية",
  "recipes.stockItem": "صنف مخزون",
  "recipes.completeness": "اكتمال الوصفات",
  "recipes.itemsWithout": "صنفًا في القائمة بلا وصفة منشورة",
  "recipes.formulaNote": "التكلفة = مجموع (الكمية × (١ + فاقد التجهيز) × تكلفة الوحدة) ÷ نسبة الناتج.",
  "recipes.complete": "مكتملة",
  "recipes.noComponents": "لا تحتوي هذه الوصفة على مكوّنات بعد، لذا تُحتسب تكلفتها صفرًا.",

  // -- Inventory -----------------------------------------------------------
  "inv.levelsTitle": "مستويات المخزون",
  "inv.levelsSubtitle": "إسقاط فوق دفتر الحركات، تتم مطابقته يوميًا.",
  "inv.itemsTitle": "أصناف المخزون",
  "inv.itemsSubtitle": "سجل الأصناف الرئيسي. وحدة الأساس غير قابلة للتغيير بمجرد وجود أي حركة.",
  "inv.countsTitle": "جلسات الجرد",
  "inv.countsSubtitle": "أعمى افتراضيًا. تُجمَّد الكمية المتوقعة لحظة فتح الجلسة.",
  "inv.transfersTitle": "التحويلات",
  "inv.transfersSubtitle": "الإرسال والاستلام خطوتان منفصلتان؛ المخزون في الطريق مرئي بينهما.",
  "inv.batchesTitle": "الدفعات",
  "inv.batchesSubtitle": "رقم الدفعة وتواريخ الإنتاج والانتهاء والقيمة المعرّضة للخطر.",
  "inv.expiryTitle": "مراقبة الصلاحية",
  "inv.expirySubtitle": "الأصناف المقتربة من الانتهاء، الأقرب أولًا، مع القيمة المعرّضة للخطر.",
  "inv.wasteTitle": "الهدر",
  "inv.wasteSubtitle": "الهدر الحقيقي يُعرض منفصلًا عن الاستهلاك المنضبط.",
  "inv.wasteReportTitle": "تقرير الهدر",
  "inv.wasteReportHint": "كل الفروع، وليس جلسة هذا الجهاز فقط.",
  "inv.totalWasteCost": "إجمالي تكلفة الهدر",
  "inv.wasteByItem": "الهدر حسب الصنف",
  "inv.wasteByCategory": "الهدر حسب الفئة",
  "inv.wasteByBranch": "الهدر حسب الفرع",
  "inv.wasteByReason": "الهدر حسب السبب",
  "inv.adjustmentsTitle": "التسويات",
  "inv.adjustmentsSubtitle": "تصحيحات يدوية. كل واحدة تحتاج سببًا، والكبيرة تحتاج اعتمادًا.",
  "inv.movementsTitle": "حركات المخزون",
  "inv.movementsSubtitle": "الدفتر غير القابل للتعديل. كل كمية في النظام مشتقة منه.",
  "inv.sku": "رمز الصنف",
  "inv.onHand": "المتاح",
  "inv.allocated": "المحجوز",
  "inv.onOrder": "قيد الطلب",
  "inv.reorderPoint": "نقطة إعادة الطلب",
  "inv.par": "المستوى المعياري",
  "inv.unitCost": "تكلفة الوحدة",
  "inv.stockValue": "قيمة المخزون",
  "inv.daysOfCover": "أيام التغطية",
  "inv.lastCounted": "آخر جرد",
  "inv.baseUnit": "وحدة الأساس",
  "inv.purchaseUnit": "وحدة الشراء",
  "inv.costingMethod": "طريقة التكلفة",
  "inv.storage": "التخزين",
  "inv.shelfLife": "العمر الافتراضي",
  "inv.batchTracked": "متتبَّع بالدفعة",
  "inv.expiryTracked": "متتبَّع بالصلاحية",
  "inv.batchNumber": "الدفعة",
  "inv.productionDate": "تاريخ الإنتاج",
  "inv.expiryDate": "تاريخ الانتهاء",
  "inv.daysToExpiry": "أيام حتى الانتهاء",
  "inv.valueAtRisk": "القيمة المعرّضة",
  "inv.mode": "الوضع",
  "inv.blind": "أعمى",
  "inv.open": "مفتوح",
  "inv.scope": "النطاق",
  "inv.countedBy": "نفّذ الجرد",
  "inv.expected": "المتوقع",
  "inv.counted": "المعدود",
  "inv.flagged": "مُعلَّم",
  "inv.netVariance": "صافي الفرق",
  "inv.blindNote": "الكميات المتوقعة مخفية أثناء الجرد الأعمى.",
  "inv.postCount": "ترحيل الجرد",
  "inv.from": "من",
  "inv.to": "إلى",
  "inv.dispatched": "المُرسل",
  "inv.received": "المستلم",
  "inv.discrepancy": "الفارق",
  "inv.inTransit": "في الطريق",
  "inv.movementType": "نوع الحركة",
  "inv.balanceAfter": "الرصيد بعدها",
  "inv.performedBy": "نفّذها",
  "inv.trueWaste": "هدر حقيقي",
  "inv.controlledConsumption": "استهلاك منضبط",
  "inv.recordWaste": "تسجيل هدر",
  "inv.negativeNote": "المخزون السالب يُسجَّل ولا يُحظر. وهو يشير إلى استلام لم يُدخَل قط.",
  "inv.markWasted": "تسجيله كهدر",
  "inv.transferOut": "تحويل للخارج",
  "inv.searchPlaceholder": "ابحث بالاسم أو رمز الصنف أو الفئة",
  "inv.batchSearchPlaceholder": "ابحث بالصنف أو رقم التشغيلة أو الموقع",
  "inv.days": "يوم",
  "inv.defaultSupplier": "المورد الافتراضي",
  "inv.baseUnitNote": "تثبت وحدة القياس الأساسية بمجرد وجود أي حركة — فكل الكميات في السجل مقوّمة بها، وتغييرها يعيد حساب التاريخ كله.",
  "inv.countsOpen": "جرد قيد التنفيذ",
  "inv.countsAwaiting": "بانتظار الترحيل",
  "inv.countLines": "بنود الجرد",
  "inv.netVarianceHint": "الأخطاء المتعاكسة يبلغ صافيها صفرًا ومع ذلك يظل صنفان خاطئين — اقرأ عدد البنود المُعلَّمة إلى جانب هذا الرقم.",
  "inv.recount": "إعادة عد",
  "inv.submitted": "أُرسل",
  "inv.posted": "رُحِّل",
  "inv.inTransitValue": "القيمة في الطريق",
  "inv.inTransitHint": "المخزون الذي غادر الموقع المرسِل ولم يُستلم بعد في الوجهة.",
  "inv.receiveTransfer": "استلام التحويل",
  "inv.discrepancyNote": "الكميات المُرسلة والمستلمة غير متطابقة. يبقى التحويل مفتوحًا حتى يُفسَّر الفارق أو يُعدم — وإغلاقه بصمت يدفع الخسارة إلى تقارير الفروقات في فرعين دون أن يتحملها أحد.",
  "inv.atRiskHint": "القيمة المحتجزة في تشغيلات تنتهي صلاحيتها خلال ثلاثة أيام.",
  "inv.expiredNote": "انتهت صلاحية هذه التشغيلة وما زالت مُقيَّدة بقيمتها الكاملة. تحتاج إلى إعدام.",
  "inv.fefoNote": "يتبع الاستهلاك قاعدة FEFO — الأقرب انتهاءً يُصرف أولًا — فتُخصم التشغيلة الأقرب لتاريخ انتهائها أولًا.",
  "inv.expiryUrgent": "مخزون يحتاج تدخلًا اليوم",
  "inv.expiryUrgentBody": "التشغيلات أدناه منتهية الصلاحية أو تنتهي اليوم، وما زالت مُقيَّدة بقيمتها الكاملة حتى تُعدم.",
  "inv.expiringToday": "ينتهي اليوم",
  "inv.expiringSoon": "خلال ٣ أيام",
  "inv.expiringLater": "لاحقًا",
  "inv.batchesLower": "تشغيلة",
  "inv.writeOff": "إعدام",
  "inv.expiryClear": "لا شيء قارب على الانتهاء",
  "inv.expiryClearBody": "لا توجد تشغيلة ضمن النطاق داخل أفق انتهاء الصلاحية.",
  "inv.writeUp": "زيادة بالتسوية",
  "inv.writeUpHint": "تسويات رفعت الرصيد — غالبًا استلام بضائع لم يُسجَّل.",
  "inv.writeDown": "خفض بالتسوية",
  "inv.adjustmentNote": "التسوية قيد في السجل بلا حدث تشغيلي وراءه. ورمز السبب هو ما يخبر وحدة التكاليف بما إذا كان الفارق مُفسَّرًا.",

  // -- Purchasing ----------------------------------------------------------
  "pur.suppliersTitle": "الموردون",
  "pur.suppliersSubtitle": "البيانات الرئيسية والشروط وبطاقة الأداء التي تُظهر زحف الأسعار.",
  "pur.requisitionsTitle": "طلبات الشراء",
  "pur.requisitionsSubtitle": "الفروع تطلب والمقر يشتري. التجميع يحتفظ بنسبة كل فرع.",
  "pur.ordersTitle": "أوامر الشراء",
  "pur.ordersSubtitle": "نطاقات القيمة تحدد من يعتمد. مقدم الطلب لا يكون معتمِدًا أبدًا.",
  "pur.receivingTitle": "إيصالات الاستلام",
  "pur.receivingSubtitle": "الاستلام يُنشئ حركة المخزون والدفعة وفحص فرق السعر.",
  "pur.invoicesTitle": "فواتير الموردين",
  "pur.invoicesSubtitle": "مطابقة ثلاثية بين أمر الشراء وإيصال الاستلام والفاتورة.",
  "pur.supplier": "المورد",
  "pur.contact": "جهة الاتصال",
  "pur.terms": "شروط الدفع",
  "pur.leadTime": "مدة التوريد",
  "pur.minOrder": "الحد الأدنى للطلب",
  "pur.deliveryDays": "أيام التوصيل",
  "pur.outstanding": "المستحق",
  "pur.scorecard": "بطاقة الأداء",
  "pur.onTime": "التسليم في الموعد",
  "pur.fillRate": "نسبة التلبية",
  "pur.priceStability": "استقرار السعر",
  "pur.qualityRejection": "رفض الجودة",
  "pur.invoiceAccuracy": "دقة الفواتير",
  "pur.avgLeadTime": "متوسط مدة التوريد",
  "pur.requestedBy": "طلبها",
  "pur.neededBy": "مطلوبة بحلول",
  "pur.estimatedTotal": "الإجمالي التقديري",
  "pur.expectedDelivery": "التسليم المتوقع",
  "pur.approvalTier": "فئة الاعتماد",
  "pur.approver": "المعتمِد",
  "pur.autoApproved": "اعتماد تلقائي",
  "pur.ordered": "المطلوب",
  "pur.rejectedQty": "المرفوض",
  "pur.rejectionReason": "سبب الرفض",
  "pur.temperature": "درجة الحرارة",
  "pur.temperatureOk": "ضمن النطاق",
  "pur.temperatureBad": "خارج النطاق",
  "pur.priceVariance": "فرق السعر",
  "pur.match": "المطابقة",
  "pur.matchNote": "نتيجة المطابقة",
  "pur.invoiceNumber": "رقم الفاتورة",
  "pur.invoiceDate": "تاريخ الفاتورة",
  "pur.dueDate": "الاستحقاق",
  "pur.ageing": "أعمار الديون",
  "pur.approveOrder": "اعتماد الأمر",
  "pur.directReceipt": "استلام مباشر — بلا أمر شراء",
  "pur.noPo": "بلا أمر شراء",
  "pur.threeWayNote": "تسامح الكمية ٠٪، وتسامح سعر الوحدة ٢٪، والإجماليات في حدود وحدة صغرى واحدة.",
  "pur.supplierSearchPlaceholder": "ابحث بالاسم أو الرمز أو جهة الاتصال أو البريد",
  "pur.netDays": "صافي ",
  "pur.taxRegistration": "التسجيل الضريبي",
  "pur.lowerIsBetter": "(الأقل أفضل)",
  "pur.underperforming": "دون مستهدف التسليم",
  "pur.underperformingHint": "الموردون الذين تقل نسبة التزامهم بمواعيد التسليم عن ٩٠٪.",
  "pur.awaitingApproval": "بانتظار الاعتماد",
  "pur.readyToConsolidate": "جاهز للتجميع",
  "pur.consolidatedNote": "دُمج هذا الطلب في أمر شراء مُجمّع. ويظل الفرع الطالب منسوبًا إليه، فتقع التكلفة على الفرع الذي طلب البضاعة.",
  "pur.approved": "تم اعتماد أمر الشراء",
  "pur.pendingValue": "القيمة بانتظار الاعتماد",
  "pur.openOrders": "أوامر مفتوحة",
  "pur.tierNote": "تضع قيمة هذا الأمر في شريحة يجب أن يعتمدها:",
  "pur.receivedValue": "قيمة المستلم",
  "pur.priceDrift": "استلامات بانحراف سعري",
  "pur.priceDriftHint": "الاستلامات التي اختلف فيها سعر الوحدة المسلَّم عن السعر المتفق عليه بأكثر من ٢٪.",
  "pur.temperatureNote": "قُبلت شحنة مبردة أو مجمدة خارج نطاق حرارتها. سجّل القرار — فأي مطالبة تلف لاحقة تعتمد على هذه القراءة.",
  "pur.matchFailures": "إخفاقات المطابقة",
  "pur.matchFailuresHint": "الفواتير التي تعذّرت تسويتها مقابل أمر الشراء وإذن الاستلام.",
  "pur.matchFailedNote": "لا تتطابق الفاتورة مع أمر الشراء وإذن الاستلام، ولا يمكن اعتمادها للدفع حتى يُحل الفارق.",

  // -- Costing -------------------------------------------------------------
  "cost.foodCostTitle": "تكلفة الطعام",
  "cost.foodCostSubtitle": "تكلفة البضاعة ÷ صافي المبيعات. قابلة للعرض حسب الفرع والعلامة والفئة والفترة.",
  "cost.varianceTitle": "الاستهلاك النظري مقابل الفعلي",
  "cost.varianceSubtitle": "أكثر رقم تشخيصي في تشغيل المطاعم. مرتب حسب القيمة لا الكمية.",
  "cost.wasteTitle": "تحليل الهدر",
  "cost.wasteSubtitle": "حسب السبب والصنف والموقع والموظف، مع فصل الهدر الحقيقي عن وجبات الموظفين.",
  "cost.marginTitle": "هامش المساهمة",
  "cost.marginSubtitle": "هندسة القائمة على محوري الرواج والربحية.",
  "cost.byBranch": "حسب الفرع",
  "cost.byBrand": "حسب العلامة",
  "cost.byCategory": "حسب الفئة",
  "cost.byReason": "حسب السبب",
  "cost.byItem": "حسب الصنف",
  "cost.byLocation": "حسب الموقع",
  "cost.byEmployee": "حسب الموظف",
  "cost.byChannel": "حسب القناة",
  "cost.foodCostPercent": "نسبة تكلفة الطعام",
  "cost.targetPercent": "النسبة المستهدفة",
  "cost.variancePoints": "الفرق",
  "cost.theoretical": "النظري",
  "cost.actualUsage": "الفعلي",
  "cost.recordedWaste": "الهدر المسجّل",
  "cost.unexplained": "غير مفسَّر",
  "cost.varianceValue": "قيمة الفرق",
  "cost.hypothesis": "السبب المرجّح",
  "cost.hypothesisNote": "يُعرض كفرضية للتحقيق، لا كاستنتاج.",
  "cost.percentOfCogs": "٪ من تكلفة البضاعة",
  "cost.records": "السجلات",
  "cost.revenueToOffset": "الإيراد اللازم للتعويض",
  "cost.revenueToOffsetHint": "قيمة الهدر مقسومة على متوسط هامش المساهمة — المبيعات الإضافية اللازمة لاستردادها.",
  "cost.unitsSold": "الوحدات المباعة",
  "cost.sellingPrice": "سعر البيع (بدون ضريبة)",
  "cost.directCost": "التكلفة المباشرة",
  "cost.contributionMargin": "هامش المساهمة",
  "cost.totalContribution": "إجمالي المساهمة",
  "cost.classification": "التصنيف",
  "cost.commission": "العمولة",
  "cost.packaging": "التغليف",
  "cost.netContribution": "صافي المساهمة",
  "cost.channelNote": "طبق بهامش جيد في الصالة قد يكون خاسرًا على منصة توصيل بعد احتساب العمولة والتغليف.",
  "cost.revenue": "الإيراد",
  "cost.marginPercent": "نسبة الهامش",
  "cost.matrixTitle": "مصفوفة هندسة القائمة",
  "cost.popularity": "الرواج",
  "cost.profitability": "الربحية",
  "cost.blendedHint": "مرجّحة بصافي المبيعات لا بمتوسط النسب — وإلا لصار وزن فرع صغير كوزن فرع رئيسي.",
  "cost.overTarget": "أعلى من المستهدف",
  "cost.varianceLoss": "خسارة الفروقات",
  "cost.unexplainedHint": "الأصناف التي لا يغطي فيها تسجيل هدر الفجوةَ بين الاستهلاك النظري والفعلي.",
  "cost.worstItem": "أكبر انحراف",
  "cost.hypothesisBadge": "للتحقيق",
  "cost.controlledHint": "وجبات الموظفين والتذوق وحصص التدريب. لها تكلفة لكنها قرار لا خسارة.",
  "cost.wasteSeparationNote": "يُعرض الهدر الحقيقي منفصلًا عن الاستهلاك المنضبط. فدمجهما يضخّم الرقم حتى يفقد ثقة الجميع، ويختبئ التلف الفعلي داخل رقم تعوّد الكل على تجاهله.",
  "cost.rankingNote": "الترتيب بإجمالي المساهمة لا بنسبة الهامش. فهامش ٧٨٪ على طبق لا يطلبه أحد يساهم بأقل من هامش ٥٢٪ على الطبق الذي يحمل خدمة الغداء.",

  // -- Workforce -----------------------------------------------------------
  "wf.employeesTitle": "الموظفون",
  "wf.employeesSubtitle": "الموظف شخص في وظيفة. المستخدم بيانات اعتماد. وهما كيانان منفصلان.",
  "wf.schedulesTitle": "الجداول",
  "wf.schedulesSubtitle": "ورديات مُتحقق منها مقابل قواعد الراحة والأيام المتتالية والشهادات.",
  "wf.attendanceTitle": "الحضور",
  "wf.attendanceSubtitle": "أحداث التسجيل بطريقتها وإشاراتها، والساعات التي تغذّي تصدير الرواتب.",
  "wf.overtimeTitle": "العمل الإضافي",
  "wf.overtimeSubtitle": "العمل الإضافي غير المعتمد يُعرض منفصلًا، ولا يُدرج ضمنيًا أبدًا.",
  "wf.performanceTitle": "الأداء",
  "wf.performanceSubtitle": "مؤشرات لكل موظف، مرتبة داخل الفرع والوظيفة.",
  "wf.employee": "الموظف",
  "wf.position": "الوظيفة",
  "wf.department": "القسم",
  "wf.homeBranch": "الفرع الأساسي",
  "wf.employmentType": "نوع التوظيف",
  "wf.hiredOn": "تاريخ التعيين",
  "wf.hourlyRate": "الأجر بالساعة",
  "wf.documents": "الوثائق",
  "wf.documentExpiry": "تنتهي في",
  "wf.hasLogin": "لديه حساب دخول",
  "wf.noLogin": "بلا بيانات اعتماد",
  "wf.shift": "الوردية",
  "wf.hours": "الساعات",
  "wf.projectedCost": "التكلفة المتوقعة",
  "wf.violations": "مخالفات القواعد",
  "wf.clockIn": "تسجيل الدخول",
  "wf.clockOut": "تسجيل الخروج",
  "wf.method": "الطريقة",
  "wf.regularHours": "عادية",
  "wf.overtimeHours": "إضافية",
  "wf.breaks": "الاستراحة",
  "wf.flags": "الإشارات",
  "wf.corrected": "مصحَّح",
  "wf.labourCost": "تكلفة العمالة",
  "wf.weekStarting": "الأسبوع يبدأ",
  "wf.multiplier": "المعامل",
  "wf.orderCount": "الطلبات",
  "wf.itemsPerOrder": "أصناف / طلب",
  "wf.upsellRate": "معدل البيع الإضافي",
  "wf.serviceTime": "زمن الخدمة",
  "wf.voidCount": "الإلغاءات",
  "wf.voidValue": "قيمة الإلغاءات",
  "wf.discountValue": "قيمة الخصومات",
  "wf.cashVariance": "الفرق النقدي",
  "wf.salesPerHour": "المبيعات / ساعة عمل",
  "wf.compensationHidden": "الأجور مخفية. تتطلب صلاحية صريحة.",
  "wf.expiringDocs": "وثائق على وشك الانتهاء",
  "wf.exportPayroll": "تصدير مدخلات الرواتب",
  "wf.payrollNote": "يصدّر TRENDOW مدخلات الرواتب. ولا يحسب صافي الأجر أو الاستقطاعات أو الاشتراكات.",
  "wf.searchPlaceholder": "ابحث بالاسم أو الرمز أو الوظيفة أو بيانات الاتصال",
  "wf.expiringDocsHint": "الموظفون الذين تحمل شهاداتهم أو تصاريحهم تاريخ انتهاء قريبًا أو منتهيًا — فشهادة تداول أغذية منتهية تعني شخصًا لا يمكن جدولته.",
  "wf.docsValid": "سارية",
  "wf.docsExpiring": "تقارب الانتهاء",
  "wf.docsExpired": "منتهية",
  "wf.permittedBranches": "الفروع المسموح بها",
  "wf.scheduledHours": "الساعات المجدولة",
  "wf.violationsNote": "بعض الورديات تخالف قاعدة راحة أو أيام متتالية أو شهادة مطلوبة. النشر ما زال متاحًا — فالجداول الواقعية تحتاج استثناءات — لكن الاستثناء يُسجَّل على السطر.",
  "wf.draftHint": "الورديات المسودة غير مرئية للموظفين حتى يُنشر الجدول.",
  "wf.flagsHint": "السجلات التي تحمل وصولًا متأخرًا أو خروجًا غير مسجّل أو خروجًا عن النطاق الجغرافي أو تصحيحًا يدويًا.",
  "wf.unapprovedHours": "ساعات غير معتمدة",
  "wf.unapprovedHint": "عمل إضافي جرى دون اعتماد مسبق. الساعات والتكلفة حقيقية في الحالتين، وفصلها هو ما يُظهر الجدول الذي يتعثر باستمرار.",
  "wf.unapprovedCost": "تكلفة غير معتمدة",
  "wf.multiplierNote": "مُعامل العمل الإضافي وساعات الأسبوع المعيارية يأتيان من حزمة الدولة لا من هذه الوحدة — فالمستأجر العامل في ثلاث دول لديه ثلاثة منها.",
  "wf.sphHint": "صافي المبيعات مقسومًا على ساعات العمل — المقياس الوحيد هنا الذي يقارن نادل غداء الثلاثاء بنادل ليلة الجمعة.",
  "wf.voidRate": "نسبة الإلغاء",
  "wf.controlMetrics": "مؤشرات الرقابة",
  "wf.performanceNote": "هذه الأرقام مدخل لحوار لا حكم نهائي. فارتفاع عدد الإلغاءات له تفسيرات سليمة بقدر ما له تفسيرات غير سليمة، والرقم وحده لا يفرّق بينها.",

  // -- Finance -------------------------------------------------------------
  "fin.cashTitle": "جلسات النقد",
  "fin.cashSubtitle": "كل وحدة عملة منسوبة إلى شخص ووردية ودرج.",
  "fin.expensesTitle": "المصروفات",
  "fin.expensesSubtitle": "مصروفات تشغيل الفرع بفئتها وطريقة دفعها وحالة اعتمادها.",
  "fin.dayCloseTitle": "إغلاق اليوم",
  "fin.dayCloseSubtitle": "محظور ما دامت أي جلسة نقدية مفتوحة. ينتج تقرير Z المتسلسل.",
  "fin.paymentsTitle": "ملخص المدفوعات",
  "fin.paymentsSubtitle": "الإجماليات حسب وسيلة الدفع، وهي أساس مطابقة كل تسوية.",
  "fin.taxTitle": "ملخص الضريبة",
  "fin.taxSubtitle": "تُحسب على مستوى السطر بمحرك ضرائب حزمة الدولة، ثم تُجمع.",
  "fin.drawer": "الدرج",
  "fin.cashier": "الكاشير",
  "fin.openingFloat": "الرصيد الافتتاحي",
  "fin.cashSales": "المبيعات النقدية",
  "fin.cashRefunds": "المرتجعات النقدية",
  "fin.payIns": "الإيداعات",
  "fin.payOuts": "المصروفات النقدية",
  "fin.safeDrops": "إيداعات الخزنة",
  "fin.expectedCash": "النقد المتوقع",
  "fin.countedCash": "النقد المعدود",
  "fin.varianceApproval": "اعتماد الفرق",
  "fin.denominations": "عدّ الفئات النقدية",
  "fin.expectedFormula": "الرصيد الافتتاحي + المبيعات النقدية + الإيداعات − المرتجعات − المصروفات − إيداعات الخزنة",
  "fin.expenseCategory": "الفئة",
  "fin.paymentMethod": "طريقة الدفع",
  "fin.incurredOn": "تاريخ الاستحقاق",
  "fin.recurring": "متكرر",
  "fin.attachment": "مرفق",
  "fin.businessDay": "يوم العمل",
  "fin.zReport": "تقرير Z",
  "fin.zNumber": "رقم Z",
  "fin.closeDay": "إغلاق يوم العمل",
  "fin.closing": "جارٍ الإغلاق",
  "fin.blockedBy": "محظور بجلسات مفتوحة",
  "fin.grossSales": "إجمالي المبيعات",
  "fin.netSales": "صافي المبيعات",
  "fin.transactionCount": "عدد المعاملات",
  "fin.voids": "الإلغاءات",
  "fin.comps": "المجانيات",
  "fin.tenderType": "وسيلة الدفع",
  "fin.count": "العدد",
  "fin.amount": "المبلغ",
  "fin.taxRate": "النسبة",
  "fin.netAmount": "الصافي",
  "fin.taxAmount": "الضريبة",
  "fin.grossAmount": "الإجمالي",
  "fin.rounding": "تسوية التقريب",
  "fin.roundingNote": "التقريب النقدي يُطبّق على الجزء النقدي فقط ويُسجَّل منفصلًا، ولا يُدمج في الإيراد أو الضريبة.",
  "fin.missingReceipt": "نثرية بلا إيصال",
  "fin.missingReceiptHint": "النثرية هي وسيلة الدفع الوحيدة التي لا يقابلها سجل في مكان آخر — فالتحويل يُطابق كشف حساب، والبطاقة ملف تسوية، أما النثرية فلا يقابلها سوى الإيصال.",
  "fin.daysOpen": "أيام ما زالت مفتوحة",
  "fin.openSessions": "جلسة مفتوحة",
  "fin.blockedHint": "لا يمكن إغلاق اليوم وجلسة نقدية ما زالت تستقبل أموالًا. فتقرير Z غير قابل للتعديل بعد إصداره، ولذلك يجب ألا يصدر مبكرًا.",
  "fin.dayClosed": "أُغلق يوم العمل",
  "fin.zSequenceNote": "أرقام Z متسلسلة لكل فرع ولا تُعاد أبدًا. والفجوة في التسلسل هي أول ما يبحث عنه المدقق، ولذلك يصدر الرقم من عملية الإغلاق لا بالاختيار.",
  "fin.taxInclusive": "شامل الضريبة",
  "fin.taxExclusive": "غير شامل الضريبة",
  "fin.perLine": "على مستوى البند",
  "fin.perOrder": "على مستوى الطلب",

  // -- Organisation --------------------------------------------------------
  "org.tenantsTitle": "المستأجرون",
  "org.tenantsSubtitle": "إدارة عابرة للمستأجرين. لطاقم المنصة فقط.",
  "org.brandsTitle": "العلامات التجارية",
  "org.brandsSubtitle": "مفهوم مطعم يملكه مستأجر، بقائمته وهويته الخاصة.",
  "org.branchesTitle": "الفروع",
  "org.branchesSubtitle": "كل فرع يملك مخزونه وأدراجه وجدوله وساعاته وعملته وإعداده الضريبي.",
  "org.warehousesTitle": "المستودعات",
  "org.warehousesSubtitle": "مواقع تحتفظ بالمخزون ولا تبيع للعملاء النهائيين.",
  "org.kitchensTitle": "المطابخ المركزية",
  "org.kitchensSubtitle": "منشآت إنتاج تستهلك مخزون المدخلات وتنتج مخزون المخرجات.",
  "org.plan": "الباقة",
  "org.state": "الحالة",
  "org.region": "منطقة البيانات",
  "org.country": "الدولة",
  "org.currency": "العملة",
  "org.timezone": "المنطقة الزمنية",
  "org.dayBoundary": "حد يوم العمل",
  "org.seats": "المقاعد",
  "org.area": "المساحة",
  "org.openedOn": "تاريخ الافتتاح",
  "org.franchise": "امتياز",
  "org.address": "العنوان",
  "org.branchCount": "الفروع",
  "org.attachedTo": "مرتبط بـ",
  "org.serves": "يخدم",
  "org.standalone": "مستقل",
  "org.tenantIsolationNote": "كل استعلام في النظام يُرشَّح بالمستأجر قبل أي شرط آخر. والقراءة عبر المستأجرين ليست صلاحية يمكن لأي دور امتلاكها — بل مستحيلة بحكم البناء.",
  "org.atRisk": "تحت الخطر",
  "org.atRiskHint": "متأخر السداد أو مقيّد أو موقوف. المتأخر ما زال يعمل، والمقيّد يواصل البيع ويفقد لوحة التحكم، والموقوف يتوقف.",
  "org.residencyNote": "تُحدَّد منطقة البيانات عند إنشاء المستأجر. ونقلها ترحيل لا إعداد.",
  "org.brandScopeNote": "ترتبط القوائم وقوائم الأسعار ومجموعات الإضافات بالعلامة لا بالفرع — وإلا لاضطر مطبخ سحابي يشغّل ست علامات من عنوان واحد إلى صيانة ست نسخ من كل شيء يدويًا.",
  "org.branchSearchPlaceholder": "ابحث بالاسم أو الرمز أو العنوان",
  "org.dayBoundaryHint": "الفرع الذي يغلق في الثانية صباحًا يحتاج أن ينتهي يومه التجاري في الرابعة لا في منتصف الليل — وإلا انقسمت كل ليلة متأخرة بين تقريرين لا يصف أي منهما وردية عمل أحد.",
  "org.franchiseHint": "صاحب الامتياز يرى فرعه فقط ولا شيء غيره، مهما قال الهيكل التنظيمي.",
  "org.driveThrough": "خدمة السيارات",
  "org.driveThroughEnabled": "تفعيل خدمة السيارات",
  "org.driveThroughHint": "عند التعطيل، لن تظهر خدمة السيارات كنوع طلب في نقطة بيع هذا الفرع.",
  "org.driveThroughUpdated": "تم حفظ إعداد خدمة السيارات",
  "org.standaloneHint": "مستودع ليس خلف مطعم. المستودعات المرتبطة ترث نطاق صلاحيات فرعها، والمستقلة لا ترث.",
  "org.warehouseNote": "المستودع يحفظ المخزون ولا يبيع — يشارك في التحويلات والجرد والتقييم، ولا يشارك في المبيعات أو الأدراج أو توجيه المطبخ.",
  "org.branchesServed": "الفروع المخدومة",
  "org.productionCostNote": "ناتج أمر الإنتاج صنف مخزني بتكلفته الخاصة — مكونات إضافة إلى عمالة الإنتاج وفاقد الناتج. وإن لم تنتقل هذه التكلفة مع البضاعة، بخّس كل فرع مستلم تكلفة طعامه.",

  // -- Reports, approvals, audit ------------------------------------------
  "rep.title": "التقارير",
  "rep.subtitle": "التقارير تصل، ولا تُطلب. كل رقم مجمّع يُفتح على معاملاته.",
  "rep.run": "تشغيل",
  "rep.running": "جارٍ التشغيل",
  "rep.schedule": "جدولة",
  "rep.async": "يعمل بشكل غير متزامن",
  "rep.category": "الفئة",
  "rep.cashierTitle": "تقرير الكاشير",
  "rep.cashierSubtitle": "كل وردية، وكل كاشير، وكل فرع — بنفس الأرقام التي أُغلقت بها الوردية.",
  "filter.today": "اليوم",
  "filter.yesterday": "أمس",
  "filter.last7": "آخر ٧ أيام",
  "filter.customRange": "نطاق مخصص",
  "rep.exportNote": "كل تصدير يُكتب في سجل التدقيق مع المستخدم الطالب وعوامل التصفية وعدد الصفوف.",
  "rep.ranTitle": "أُدرج التقرير في الطابور",
  "rep.ranBody": "في النظام الفعلي يعيد هذا معرّف تشغيل ويسلّم النتيجة عبر إشعار.",

  "apr.title": "الاعتمادات",
  "apr.subtitle": "الخصومات والمرتجعات وأوامر الشراء والهدر والجرد والمصروفات وتغييرات الأسعار.",
  "apr.kind": "النوع",
  "apr.entity": "الموضوع",
  "apr.requested": "طُلب",
  "apr.expires": "ينتهي",
  "apr.requiredPermission": "الصلاحية المطلوبة",
  "apr.decision": "القرار",
  "apr.comment": "تعليق",
  "apr.decidedBy": "قرّره",
  "apr.approveConfirm": "اعتماد هذا الطلب؟",
  "apr.rejectConfirm": "رفض هذا الطلب؟",
  "apr.cannotSelfApprove": "لا يمكنك اعتماد طلب قدّمته بنفسك.",
  "apr.noPermission": "دورك لا يحمل الصلاحية التي يتطلبها هذا الطلب.",
  "apr.queue": "طابور الانتظار",
  "apr.history": "السجل",
  "apr.queueEmpty": "لا شيء ينتظر قرارًا",
  "apr.escalatedHint": "طلبات تجاوزت أول معتمد لها دون قرار فانتقلت إلى مستوى أعلى.",
  "apr.commentHint": "يُسجَّل مع القرار في سجل التدقيق.",
  "apr.expiryNote": "الطلب المنتهي لا يُعتمد ضمنًا — بل يسقط ويجب رفعه من جديد. فالخصم الذي لم يلتفت أحد لاعتماده خصم لم يُعتمد قط.",

  "audit.title": "سجل التدقيق",
  "audit.subtitle": "إضافة فقط ومسلسل بالتجزئة. والوصول إلى السجل نفسه يُسجَّل.",
  "audit.action": "الإجراء",
  "audit.actor": "المنفّذ",
  "audit.actorType": "نوع المنفّذ",
  "audit.entity": "الكيان",
  "audit.occurred": "وقت العمل",
  "audit.recorded": "وقت النظام",
  "audit.impersonated": "انتحل الهوية",
  "audit.correlation": "معرّف الارتباط",
  "audit.hash": "التجزئة",
  "audit.previousHash": "التجزئة السابقة",
  "audit.before": "قبل",
  "audit.after": "بعد",
  "audit.chainVerified": "السلسلة موثّقة",
  "audit.chainNote": "تجزئة كل قيد تغطي محتواه وتجزئة القيد السابق، لكل مستأجر.",
  "audit.viewEntry": "عرض القيد",

  "anom.title": "إشارات الشذوذ",
  "anom.subtitle": "كل إشارة دعوة للتحقيق، لا اتهام.",
  "anom.evidence": "الأدلة",
  "anom.observed": "المرصود",
  "anom.baseline": "خط الأساس",
  "anom.sigma": "الانحراف",
  "anom.detected": "رُصد",
  "anom.severity": "الخطورة",
  "anom.subject": "الموضوع",
  "anom.dismiss": "تجاهل",
  "anom.confirm": "تأكيد للتحقيق",

  // -- Users, roles, settings ---------------------------------------------
  "usr.title": "المستخدمون",
  "usr.subtitle": "بيانات الاعتماد وإسنادات الأدوار. كل إسناد يحمل نطاقًا وقد تنتهي صلاحيته.",
  "usr.email": "البريد الإلكتروني",
  "usr.phone": "الهاتف",
  "usr.mfa": "المصادقة الثنائية",
  "usr.mfaEnrolled": "مُفعّلة",
  "usr.mfaMissing": "غير مُفعّلة",
  "usr.lastLogin": "آخر دخول",
  "usr.assignments": "إسنادات الأدوار",
  "usr.scopeLevel": "النطاق",
  "usr.validity": "الصلاحية",
  "usr.temporary": "ترقية مؤقتة",
  "usr.linkedEmployee": "الموظف المرتبط",
  "usr.forceLogout": "تسجيل الخروج من كل الأجهزة",
  "usr.locale": "لغة الواجهة",

  "role.title": "الأدوار",
  "role.subtitle": "الصلاحية تحدد «ماذا» والنطاق يحدد «أين». الأدوار المعرّفة مسبقًا تُنسخ ولا تُحذف.",
  "role.system": "معرّف مسبقًا",
  "role.custom": "مخصص",
  "role.users": "المستخدمون",
  "role.permissionCount": "الصلاحيات",
  "role.defaultScope": "النطاق الافتراضي",
  "role.editor": "محرر الصلاحيات",
  "role.sensitive": "حسّاسة",
  "role.sodTitle": "فصل المهام",
  "role.sodSubtitle": "أزواج الصلاحيات المتعارضة التي يحملها المستخدم نفسه.",
  "role.sodBlocking": "محظور",
  "role.sodWarning": "تحذير",
  "role.sodRisk": "المخاطرة",
  "role.clone": "نسخ الدور",
  "role.noConflicts": "لا توجد تعارضات في فصل المهام لدى هذا المستأجر.",

  "set.title": "الإعدادات",
  "set.subtitle": "القيم تُحسم عبر تسلسل. المستوى الأدنى يتجاوز الأعلى ما لم يكن مقفلًا.",
  "set.cascade": "تسلسل الإعدادات",
  "set.cascadeNote": "الافتراضي للمنصة ← حزمة الدولة ← المستأجر ← العلامة ← الفرع ← الجهاز.",
  "set.effectiveValue": "القيمة الفعّالة",
  "set.suppliedBy": "مصدرها",
  "set.locked": "مقفل",
  "set.lockedAt": "مقفل عند",
  "set.general": "عام",
  "set.localisation": "التوطين",
  "set.pos": "نقطة البيع وشاشة المطبخ",
  "set.thresholds": "حدود الاعتماد",
  "set.demo": "أدوات العرض التجريبي",
  "set.security": "الأمان",
  "set.demoNote": "تُشغّل هذه المفاتيح حالات التحميل والفراغ والخطأ دون خادم.",
  "set.dataMode": "وضع البيانات",
  "set.dataNormal": "عادي",
  "set.dataEmpty": "استجابات فارغة",
  "set.dataError": "خطأ في الخدمة",
  "set.dataSlow": "شبكة بطيئة",
  "set.posSettings": "نقطة البيع",
  "set.kdsSettings": "شاشة المطبخ",
  "set.autoFire": "الإرسال إلى المطبخ تلقائيًا عند إدخال الصنف",
  "set.blindCount": "عدّ نقدي أعمى عند إغلاق الوردية",
  "set.blindStockCount": "جرد مخزون أعمى افتراضيًا",
  "set.requireTable": "اشتراط تعيين الطاولة قبل الإرسال",
  "set.staggerRelease": "إطلاق متدرّج حسب زمن التحضير",
  "set.bumpConfirm": "اشتراط تفاعل مقصود لإنهاء التذكرة",
  "set.ticketTarget": "الزمن المستهدف للتذكرة",
  "set.discountLimit": "أقصى خصم دون اعتماد",
  "set.wasteThreshold": "حد اعتماد الهدر",
  "set.varianceTolerance": "تسامح فرق الجرد",
  "set.cashTolerance": "تسامح الفرق النقدي",
  "set.poTier1": "سقف الفئة الأولى لأوامر الشراء",
  "set.poTier2": "سقف الفئة الثانية لأوامر الشراء",
  "set.sessionIdle": "مهلة خمول لوحة التحكم",
  "set.minutes": "دقيقة",
  "set.seconds": "ثانية",

  "cp.title": "حزم الدول",
  "cp.subtitle": "السلوك الخاص بكل ولاية قضائية بيانات لا شفرة. الحزم موقّعة ومُصدَّرة بنسخ.",
  "cp.version": "النسخة",
  "cp.effectiveFrom": "سارية من",
  "cp.signed": "موقّعة",
  "cp.unsigned": "غير موقّعة",
  "cp.taxEngine": "محرك الضريبة",
  "cp.pricingMode": "وضع التسعير",
  "cp.rounding": "التقريب",
  "cp.computationLevel": "تُحسب الضريبة عند",
  "cp.taxClasses": "فئات الضريبة",
  "cp.fiscal": "مزوّد الفوترة الضريبية",
  "cp.weekStart": "بداية الأسبوع",
  "cp.weekend": "عطلة نهاية الأسبوع",
  "cp.weeklyHours": "ساعات العمل الأسبوعية",
  "cp.overtimeMultiplier": "معامل العمل الإضافي",
  "cp.retention": "الاحتفاظ بالبيانات",
  "cp.conformance": "مجموعة اختبارات المطابقة",
  "cp.conformancePassed": "اجتازت",
  "cp.conformanceFailed": "لم تجتز",
  "cp.activationBlocked": "لا يمكن تفعيل حزمة في الإنتاج قبل اجتياز اختبارات المطابقة وتوقيعها.",
  "cp.years": "سنوات",
  "cp.branchesUsing": "الفروع المستخدمة لهذه الحزمة",
  "cp.cannotActivate": "لا يمكن تفعيلها",

  "int.title": "التكاملات",
  "int.subtitle": "صحة الموصّل مرئية: آخر نجاح ومعدل الأخطاء وعمق الطابور.",
  "int.vendor": "المزوّد",
  "int.lastSuccess": "آخر نجاح",
  "int.errorRate": "معدل الأخطاء",
  "int.queueDepth": "عمق الطابور",
  "int.circuitOpen": "قاطع الدائرة مفتوح",
  "int.circuitNote": "بعد تجاوز حد الفشل، تُعلَّق الاستدعاءات وتُوضع في الطابور مع فحص دوري للتعافي.",
  "int.configure": "ضبط",
  "int.enable": "تفعيل",
  "int.disable": "تعطيل",
  "int.rotate": "تدوير بيانات الاعتماد",
  "int.branchesConnected": "الفروع المتصلة",
  "int.category": "الفئة",
  "int.healthy": "سليمة",
  "int.unhealthy": "متدهورة أو متعثرة",
  "int.queueHint": "طلبات محتجزة أثناء تعذّر الموصّل. يفرغ الطابور عند التعافي — فهو عمل مؤجل لا عمل ضائع.",
  "int.notConfiguredNote": "لم يُعدّ أحد هذا الموصّل بعد. وهذا يختلف عن تعطيله: فموصّل ضرائب غير مُعد يمر دون انتباه حتى موعد الإقرار.",
  "int.aclNote": "يقف كل موصّل خلف طبقة عزل، فتغيير المورد لشكل بياناته يصبح تعديلًا في مُهايئ واحد بدل انتشاره في نموذج المجال كله.",

  "common.type": "النوع",

  // -- Morning brief, added -----------------------------------------------
  "dash.briefTitle": "الموجز الصباحي",
  "dash.briefHint": "يوم العمل السابق في صيغة تُقرأ على الهاتف في أقل من ٣٠ ثانية — الاستثناءات أولًا لا الإجماليات.",
  "dash.briefAllClear": "لا شيء خارج الحدود. كل مؤشر متابَع عند مستهدفه أو دونه، ولا تنبيه مفتوح.",
  "dash.briefOverTarget": "فوق المستهدف",
  "dash.briefWatchBranch": "يحتاج انتباهًا — الأبعد عن متوسط المجموعة",
  "dash.briefAlerts": "تنبيهًا مفتوحًا، منها",
  "dash.briefCritical": "حرج أو مرتفع",
  "dash.briefNothingToday": "لا يوجد فرع يبتعد أكثر من ١٫٥ انحراف معياري عن متوسط المجموعة.",

  // -- Auth shell, added ---------------------------------------------------
  "auth.brandLine": "كل عملية بيع هي معاملة على المنشأة بكاملها، لا على درج النقدية وحده.",
  "auth.brandSub": "لوحة إدارة نظام تشغيل المطاعم: المبيعات والمطبخ والوصفات والمخزون والمشتريات والموظفون والنقدية والضريبة بساعة واحدة.",
  "auth.pointOffline": "اثنتان وسبعون ساعة عمل بلا خادم، ثم مزامنة لا تُضيع شيئًا ولا تكرر شيئًا.",
  "auth.pointArabic": "العربية والإنجليزية درجة أولى على كل سطح — مكتوبة من اليمين ثم تُعكس إلى الإنجليزية.",
  "auth.pointAudit": "كل عملية تغيّر الحالة تكتب قيد تدقيق مسلسلًا بالتجزئة لا يستطيع العبث إخفاءه.",
  "auth.docNote": "ROS-SRS-001 v1.0 · ٢١٢ وظيفي · ١٤٨ غير وظيفي",
  "auth.backToSite": "عودة إلى الموقع",

  // -- Users and roles, added -------------------------------------------
  "common.notInBuild": "موصَّف في خط الأساس، وغير منفَّذ في هذا البناء.",
  "common.actionFailed": "لم يتم تنفيذ ذلك. رفضه الخادم.",
  "terminals.revoked": "تم إلغاء تسجيل الجهاز. لم يعد بإمكانه استقبال الطلبات أو المدفوعات.",
  "common.invite": "دعوة مستخدم",
  "common.never": "لم يحدث",
  "common.role": "الدور",
  "usr.employeeNote": "المستخدم بيانات دخول، والموظف شخص في وظيفة. وهما سجلان منفصلان بينهما ارتباط اختياري، لأن خلطهما ينتج نموذج صلاحيات لا يعبّر عن أيٍّ منهما.",
  "usr.searchPlaceholder": "ابحث بالاسم أو البريد أو الهاتف",
  "usr.mfaRequiredMissing": "مطلوب وغير مُفعَّل",
  "usr.scopeNote": "الصلاحيات السارية هي اتحاد الإسنادات، ويُقيَّم كلٌّ منها داخل نطاقه هو.",
  "usr.scopeAll": "المستوى كاملًا",
  "role.surfaces": "الأسطح",
  "role.mfaRequired": "تحقق ثنائي إلزامي",
  "role.searchPlaceholder": "ابحث في الأدوار",
  "role.permissionsIn": "صلاحية",
  "role.blockedNote": "التركيبات الممنوعة تُرفض تمامًا مهما كانت تهيئة الدور — FR-SEC-016.",
  "role.cloneNote": "الأدوار الجاهزة تُستخدم كما هي. وللمستأجر أن ينسخ واحدًا ويعدّله، لكن لا يحذفه أبدًا — FR-SEC-010.",

  // -- Live console framing ------------------------------------------------
  "live.title": "مباشر",
  "live.note": "كل ما يلي يأتي من الأجهزة على هذا الجهاز. سجّل طلبًا على نقطة البيع فيظهر هنا لحظيًا — المبيعات وتذاكر المطبخ وحركات المخزون ودرج النقدية.",
  "live.empty": "لا يوجد شيء بعد.",
  "live.emptyBody": "افتح نقطة البيع، وأعلن الرصيد الافتتاحي، وسجّل طلبًا. سيظهر هنا فور تسجيله.",
  "live.httpTitle": "خادم مباشر",
  "live.httpNote": "كل ما يلي هو سجل المستأجر نفسه، مقروءًا من الخادم — من كل الأجهزة، لا من هذا الجهاز وحده.",
  "live.deviceOnlyTitle": "هذا الجهاز فقط",
  "live.deviceOnlyNote": "لا يقدّم الخادم واجهة لهذا بعد، فما يلي هو ما فعلته أجهزة هذا الجهاز. ليس سجل المستأجر، وليس ما سيعرضه جهاز آخر.",
  "live.emptyBackend": "لا شيء هنا بعد.",
  "live.emptyBackendBody": "لا صفوف لدى الخادم في النطاق الحالي. وسّع منتقي الفرع، أو سجّل عملية على جهاز مرتبط بهذا المستأجر.",
  "live.openPos": "فتح نقطة البيع",
  "live.openKds": "فتح شاشة المطبخ",
  "live.todayOnDevice": "على هذا الجهاز اليوم",
  "live.seededNote": "السجل التمهيدي السابق للوردية لم يتغيّر؛ هذه الأرقام هي ما أضافته الأجهزة إليه.",
  "nav.terminalsGroup": "الأجهزة",
  "nav.pos": "نقطة البيع",
  "nav.kds": "شاشة المطبخ",
  "nav.notBuilt": "غير مُنفَّذ في هذه النسخة",
  "nav.notBuiltHint": "هذه الوحدة موصَّفة لكنها غير منفّذة هنا. أما النواة التشغيلية — البيع والمطبخ والمخزون والدرج — فمنفّذة.",

  // -- Terminals: shared chrome -------------------------------------------
  "term.pos": "نقطة البيع",
  "term.kds": "شاشة المطبخ",
  "term.console": "وحدة التحكم",
  "term.branch": "الفرع",
  "term.terminal": "الجهاز",
  "term.station": "المحطة",
  "term.allStations": "كل المحطات",
  "term.pass": "المُمرِّر",
  "term.reset": "تصفير الجهاز",
  "term.resetConfirm": "هل تريد مسح كل الطلبات والتذاكر والدرج وحركات المخزون التي تمت على هذا الجهاز وبدء الوردية من جديد؟",
  "term.resetNote": "البيانات الرئيسية — القائمة والوصفات والفروع والموظفون — لا تتأثر. يُمسح فقط ما نفّذه هذا الجهاز.",
  "term.offline": "يعمل محليًا",
  "term.offlineNote": "لا يوجد خادم في هذه النسخة. الطلبات والتذاكر والمخزون ودرج النقدية تعيش في هذا المتصفح وتتزامن بين التبويبات، فتتحدث نقطة البيع وشاشة المطبخ معًا.",
  "term.loading": "جارٍ تشغيل الجهاز",

  // -- Shift and drawer ----------------------------------------------------
  "shift.title": "الوردية",
  "shift.none": "لا توجد وردية مفتوحة",
  "shift.noneLede": "يعلن الكاشير الرصيد الافتتاحي قبل أول عملية بيع. حتى ذلك الحين لن يقبل الجهاز أي طلب.",
  "shift.open": "فتح وردية",
  "shift.cashier": "الكاشير",
  "shift.openingFloat": "الرصيد الافتتاحي",
  "shift.floatInvalid": "أدخل الرصيد الافتتاحي كرقم.",
  "shift.countInvalid": "أحد الأعداد ليس رقمًا. صحّحه قبل الإقفال.",
  "shift.openedAt": "وقت الفتح",
  "shift.cashSales": "مبيعات نقدية",
  "shift.cashRefunds": "مرتجعات نقدية",
  "shift.payIn": "إيداع في الدرج",
  "shift.payOut": "صرف من الدرج",
  "shift.safeDrop": "إيداع في الخزنة",
  "shift.drawerOps": "الدرج",
  "shift.amount": "المبلغ",
  "shift.reason": "السبب",
  "shift.record": "تسجيل",
  "shift.expected": "المتوقع في الدرج",
  "shift.xReport": "تقرير X",
  "shift.xReportNote": "ملخص أثناء الوردية لا يصفّر الأرصدة. الدرج يستمر كما هو.",
  "shift.close": "إغلاق الوردية",
  "shift.countDrawer": "عدّ الدرج",
  "shift.blindNote": "عدّ أعمى. يظل المبلغ المتوقع مخفيًا حتى تُدخل كل الفئات — فالكاشير الذي يرى الرقم المستهدف يعدّه بدلًا من عدّ النقود.",
  "shift.denomination": "الفئة",
  "shift.count": "العدد",
  "shift.countedTotal": "المعدود",
  "shift.variance": "الفرق",
  "shift.varianceOver": "زيادة",
  "shift.varianceShort": "عجز",
  "shift.varianceReason": "سبب الفرق",
  "shift.acknowledge": "إقرار المدير",
  "shift.acknowledgeHint": "الفرق الذي يتجاوز حد التسامح يحتاج إلى مدير مُسمّى.",
  "shift.confirmClose": "إغلاق وتسليم",
  "shift.drawerLimit": "تجاوز الدرج حدّه — سجّل إيداعًا في الخزنة.",
  "shift.closed": "أُغلقت الوردية",
  "shift.ordersTaken": "الطلبات",
  "shift.tenderBreakdown": "حسب وسيلة الدفع",
  "shift.summary": "ملخص الوردية",
  "shift.grossSales": "إجمالي المبيعات",
  "shift.netSales": "صافي المبيعات",
  "shift.cardSales": "مبيعات البطاقة",
  "shift.otherSales": "وسائل دفع أخرى",
  "shift.refunds": "المرتجعات",
  "shift.cancelledOrders": "الطلبات الملغاة",
  "shift.deposits": "الإيداعات",
  "shift.withdrawals": "السحوبات",
  "shift.balanced": "متوازن",
  "shift.closingCash": "النقد عند الإغلاق",

  // -- POS -----------------------------------------------------------------
  "pos.newOrder": "طلب جديد",
  "pos.orderType": "نوع الطلب",
  "pos.floorPlan": "الصالة",
  "pos.openOrders": "الطلبات المفتوحة",
  "pos.menu": "القائمة",
  "pos.searchItems": "ابحث بالاسم أو الباركود أو رمز الصنف",
  "pos.searchNote": "البحث العربي يتجاهل التشكيل ويعامل أ إ آ ا حرفًا واحدًا.",
  "pos.allCategories": "الكل",
  "pos.favourites": "مفاتيح سريعة",
  "pos.noItems": "لا يوجد ما يطابق البحث.",
  "pos.eightySix": "إيقاف",
  "pos.eightySixed": "موقوف",
  "pos.eightySixReason": "لماذا أُوقف الصنف؟",
  "pos.restore": "إعادة التفعيل",
  "pos.overrideOnce": "اعتماد لهذا الطلب",
  "pos.overrideApprover": "المدير المعتمِد",
  "pos.overrideChoose": "اختر مديرًا",
  "pos.overrideNote":
    "يسمح بهذا الصنف في الطلب الحالي فقط، ويبقى موقوفًا في كل طلب آخر على هذا الجهاز.",
  "pos.overrideActive": "مُعتمَد لهذا الطلب",
  "pos.overrideActiveNote":
    "اعتمد مدير هذا الصنف للطلب المفتوح، ويظل الإيقاف ساريًا في ما عداه.",
  "pos.remaining": "متبقٍ {n}",
  "pos.noRecipe": "بلا وصفة",
  "pos.selectTable": "اختر طاولة",
  "pos.tableRequired": "طلب الصالة يحتاج طاولة قبل إرساله إلى المطبخ.",
  "pos.guests": "عدد الضيوف",
  "pos.area": "المنطقة",
  "pos.seats": "مقعد",
  "pos.emptyOrder": "لا توجد أصناف بعد. اختر من القائمة.",
  "pos.startPrompt": "ابدأ طلبًا جديدًا أو تابع طلبًا مفتوحًا.",
  "pos.course": "الطبق",
  "pos.seat": "المقعد",
  "pos.lineNote": "ملاحظة للمطبخ",
  "pos.noteChips": "ملاحظات شائعة",
  "pos.subtotal": "المجموع الفرعي",
  "pos.discountTotal": "الخصومات",
  "pos.serviceCharge": "رسم الخدمة",
  "pos.tax": "الضريبة",
  "pos.taxIncluded": "شاملة",
  "pos.rounding": "تقريب نقدي",
  "pos.total": "الإجمالي",
  "pos.paid": "المدفوع",
  "pos.balance": "المتبقي",
  "pos.fire": "إرسال إلى المطبخ",
  "pos.fireCourse": "إرسال الطبق {n}",
  "pos.fired": "أُرسل",
  "pos.park": "تعليق",
  "pos.parked": "معلّق",
  "pos.resume": "استئناف",
  "pos.pay": "الدفع",
  "pos.cancelOrder": "إلغاء الطلب",
  "pos.cancelReason": "ما سبب إلغاء الطلب؟",
  "pos.moveTable": "نقل الطاولة",
  "pos.void": "إلغاء الصنف",
  "pos.voidReason": "سبب الإلغاء",
  "pos.voidPreFire": "لم يُحضَّر شيء بعد، لذا يُرفع الصنف من الفاتورة فحسب.",
  "pos.voidPostFire": "المطبخ حضّر هذا الصنف بالفعل. حدّد أين ذهب الطعام.",
  "pos.disposition": "أين ذهب؟",
  "pos.dispositionReturn": "أُعيد إلى المخزون",
  "pos.dispositionWaste": "هالك",
  "pos.dispositionStaff": "أُعطي للموظفين",
  "pos.dispositionNote": "الإلغاءات غير المصنّفة تظهر لاحقًا كفروقات غير مبررة، ولا أحد يسجّلها بعد وقوعها.",
  "pos.comp": "ضيافة",
  "pos.compNote": "الضيافة تمنح الصنف مجانًا: الإيراد صفر، لكن التكلفة تُحتسب والمخزون يُستهلك.",
  "pos.discount": "خصم",
  "pos.discountLine": "خصم على الصنف",
  "pos.discountOrder": "خصم على الطلب",
  "pos.discountPercent": "نسبة مئوية",
  "pos.discountAmount": "مبلغ",
  "pos.discountReason": "السبب",
  "pos.needsApproval": "ما يزيد عن {n}٪ يحتاج موافقة مدير.",
  "pos.approver": "المدير المعتمد",
  "pos.apply": "تطبيق",
  "pos.modifiers": "الخيارات",
  "pos.required": "مطلوب",
  "pos.chooseAtLeast": "اختر {n} على الأقل",
  "pos.chooseUpTo": "اختر حتى {n}",
  "pos.addToOrder": "إضافة إلى الطلب",
  "pos.variant": "الحجم",
  "pos.quantity": "الكمية",
  "pos.payment": "الدفع",
  "pos.tender": "وسيلة الدفع",
  "pos.tendered": "النقد المستلم",
  "pos.changeDue": "الباقي",
  "pos.amountPaid": "المبلغ المدفوع",
  "pos.splitEqually": "تقسيم بالتساوي",
  "pos.parties": "عدد الأجزاء",
  "pos.takePayment": "تحصيل الدفع",
  "pos.settle": "تسوية",
  "pos.paymentDone": "اكتمل الطلب",
  "pos.receipt": "الإيصال",
  "pos.printReceipt": "طباعة",
  "pos.newOrderAfter": "الطلب التالي",
  "pos.refund": "استرداد",
  "pos.refundAmount": "مبلغ الاسترداد",
  "pos.refundReason": "سبب الاسترداد",
  "pos.refundReturnStock": "إعادة المكونات إلى المخزون",
  "pos.refundNote": "يعود الاسترداد إلى وسيلة الدفع الأصلية ولا يتجاوز ما حُصِّل.",
  "pos.recent": "المكتملة اليوم",
  "pos.priceFrom": "السعر من {source}",
  "pos.priceBase": "السعر الأساسي",
  "pos.priceList": "قائمة أسعار",
  "pos.priceOverride": "تعديل يدوي",

  // -- KDS -----------------------------------------------------------------
  "kds.title": "شاشة المطبخ",
  "kds.queue": "الطابور",
  "kds.noTickets": "لا يوجد شيء على هذه المحطة.",
  "kds.noTicketsNote": "تصل التذاكر هنا لحظة إرسال نقطة البيع للطبق.",
  "kds.bump": "إنهاء",
  "kds.bumpAll": "إنهاء التذكرة",
  "kds.holdToBump": "اضغط مطولًا للإنهاء",
  "kds.bumpNote": "الإنهاء يحتاج ضغطة مطوّلة مقصودة. شاشات المطبخ تُلمس بالمرافق والأكمام والماء.",
  "kds.start": "بدء",
  "kds.started": "جاري التحضير",
  "kds.waiting": "لم يبدأ فيه أحد بعد",
  "kds.waitTotal": "انتظار الضيف",
  "kds.cookTime": "وقت التحضير",
  "kds.pickup": "في الطابور",
  "kds.recall": "استرجاع",
  "kds.recalled": "مُسترجَعة",
  "kds.allDay": "الإجمالي اليومي",
  "kds.allDayNote": "كل ما هو معلّق على هذه المحطة، مجموعًا.",
  "kds.elapsed": "المنقضي",
  "kds.target": "المستهدف",
  "kds.onTarget": "ضمن المستهدف",
  "kds.approaching": "يقترب",
  "kds.exceeded": "تجاوز",
  "kds.critical": "حرِج",
  "kds.rush": "عاجل",
  "kds.vip": "كبار الزوار",
  "kds.remake": "معدّلة",
  "kds.amended": "أصناف مضافة",
  "kds.voidedLine": "أُلغي — أوقف التحضير",
  "kds.orderCancelled": "الطلب ملغي",
  "kds.stopMaking": "توقف عن تحضير هذا الطلب.",
  "kds.cancelReason": "السبب",
  "kds.ackCancel": "تمام — إخفاء",
  "kds.passTitle": "المُمرِّر",
  "kds.passNote": "تُجمَّع الطلبات هنا بعد انتهاء كل المحطات.",
  "kds.ready": "جاهز للتجميع",
  "kds.waitingOn": "بانتظار {stations}",
  "kds.serve": "قُدِّم",
  "kds.sortBy": "الترتيب",
  "kds.sortOldest": "الأقدم أولًا",
  "kds.sortTarget": "حسب الوقت المستهدف",
  "kds.sortCourse": "حسب الطبق",
  "kds.bottleneck": "أكثر المحطات ازدحامًا",
  "kds.avgTicket": "متوسط زمن التذكرة",

  // -- النماذج -------------------------------------------------------------
  "form.required": "مطلوب",
  "form.optional": "اختياري",
  "form.errorCount": "‏{n} من الحقول تحتاج إلى مراجعة قبل الحفظ.",
  "form.saving": "جارٍ الحفظ",
  "form.saved": "تم الحفظ",
  "form.save": "حفظ",
  "form.cancel": "إلغاء",
  "form.back": "رجوع",
  "form.next": "التالي",
  "form.finish": "إنهاء",
  "form.skip": "تخطّي هذه الخطوة",
  "form.discard": "تجاهل التغييرات",
  "form.keepEditing": "متابعة التحرير",
  "form.unsavedTitle": "لديك تغييرات غير محفوظة",
  "form.unsavedBody": "الخروج الآن يتجاهل كل ما كُتب منذ آخر حفظ، ولا يمكن التراجع عن ذلك.",
  "form.addRow": "إضافة",
  "form.removeRow": "حذف",
  "form.retry": "إعادة المحاولة",
  "form.readOnly": "للقراءة فقط",
  "form.readOnlyWhy": "دورك يتيح الاطلاع على هذا السجل دون تعديله.",

  // -- التحقق ---------------------------------------------------------------
  "validation.invalid": "هذه القيمة غير صالحة.",
  "validation.required": "هذا الحقل مطلوب.",
  "validation.email": "أدخل بريدًا إلكترونيًا صحيحًا، مثل name@restaurant.com.",
  "validation.phone": "أدخل رقم هاتف صحيحًا، أرقام وعلامة + فقط.",
  "validation.minLength": "استخدم ‏{n}‏ حرفًا على الأقل.",
  "validation.maxLength": "لا تتجاوز ‏{n}‏ حرفًا.",
  "validation.minValue": "أدخل ‏{n}‏ أو أكثر.",
  "validation.maxValue": "أدخل ‏{n}‏ أو أقل.",
  "validation.positive": "أدخل رقمًا أكبر من صفر.",
  "validation.nonNegative": "لا يمكن أن تكون القيمة سالبة.",
  "validation.integer": "أدخل رقمًا صحيحًا.",
  "validation.digits": "أدخل ‏{n}‏ أرقام بالضبط.",
  "validation.passwordWeak": "أضف حرفًا كبيرًا وآخر صغيرًا ورقمًا.",
  "validation.passwordMismatch": "كلمتا المرور غير متطابقتين.",
  "validation.passwordReused": "يجب أن تختلف كلمة المرور الجديدة عن الحالية.",
  "validation.url": "أدخل عنوان موقع صحيحًا.",
  "validation.date": "أدخل تاريخًا صحيحًا.",
  "validation.dateOrder": "تاريخ النهاية لا يسبق تاريخ البداية.",
  "validation.atLeastOne": "اختر خيارًا واحدًا على الأقل.",
  "validation.duplicate": "هذه القيمة مستخدمة بالفعل.",
  "validation.arabicRequired": "الاسم بالعربية مطلوب.",
  "validation.englishRequired": "الاسم بالإنجليزية مطلوب.",
  "validation.currencyMismatch": "المبالغ بعملات مختلفة ولا يمكن جمعها.",
  "validation.percentRange": "أدخل نسبة بين ٠ و ١٠٠.",

  // -- تتمة المصادقة ---------------------------------------------------------
  "auth.forgotTitle": "إعادة تعيين كلمة المرور",
  "auth.forgotLede": "أدخل البريد الذي تسجّل الدخول به. إن كان مطابقًا لحساب قائم، يُرسل إليه رابط إعادة التعيين.",
  "auth.forgotSubmit": "إرسال رابط إعادة التعيين",
  "auth.forgotSentTitle": "راجع بريدك الإلكتروني",
  "auth.forgotSentBody": "إن كان هناك حساب بهذا العنوان، فالرابط في طريقه إليه. الرابط صالح ثلاثين دقيقة ويُستخدم مرة واحدة.",
  "auth.forgotDemoNote": "نسخة تجريبية: لا يُرسل أي بريد. تابع إلى شاشة إعادة التعيين للاطلاع عليها.",
  "auth.continueToReset": "المتابعة إلى شاشة إعادة التعيين",
  "auth.backToSignIn": "العودة إلى تسجيل الدخول",
  "auth.resetTitle": "اختر كلمة مرور جديدة",
  "auth.resetLede": "سيؤدي هذا إلى تسجيل خروجك من كل الأجهزة الأخرى.",
  "auth.resetNoToken": "رابط إعادة التعيين غير مكتمل. اطلب رابطًا جديدًا — فالرابط في البريد يحمل رمزًا لمرة واحدة تحتاجه هذه الصفحة.",
  "auth.changePassword": "تغيير كلمة المرور",
  "auth.currentPassword": "كلمة المرور الحالية",
  "auth.changePasswordDemo": "الوضع التجريبي لا يحتوي على مخزن حسابات، فلا توجد كلمة مرور لتغييرها. وجّه NEXT_PUBLIC_API_URL إلى الخادم لاستخدام هذا.",
  "auth.errorCurrentPassword": "هذه ليست كلمة المرور الحالية.",
  "auth.resetDone": "تم تغيير كلمة المرور. سجّل الدخول بالكلمة الجديدة.",
  "auth.passwordChanged": "تم تغيير كلمة المرور. تم تسجيل الخروج من كل الجلسات الأخرى.",
  "auth.newPassword": "كلمة المرور الجديدة",
  "auth.confirmPassword": "تأكيد كلمة المرور",
  "auth.resetSubmit": "تعيين كلمة المرور وتسجيل الدخول",
  "auth.passwordRules": "يجب أن تحتوي كلمة المرور على",
  "auth.ruleLength": "اثني عشر حرفًا على الأقل",
  "auth.ruleCase": "حرف كبير وحرف صغير",
  "auth.ruleDigit": "رقم واحد على الأقل",
  "auth.demoAccounts": "الحسابات التجريبية",
  "auth.demoAccountsHint": "حساب لكل دور. جميع الحسابات تستخدم كلمة المرور نفسها الموضحة أدناه. اختيار صف يملأ النموذج.",
  "auth.demoPassword": "كلمة المرور لكل الحسابات التجريبية",
  "auth.pinLabel": "رمز الجهاز",
  "auth.use": "استخدام",
  "auth.copied": "تم النسخ",
  "auth.errorUnknownEmail": "لا يوجد حساب بهذا البريد الإلكتروني.",
  "auth.errorBadPassword": "كلمة المرور غير صحيحة.",
  "auth.errorLocked": "محاولات فاشلة كثيرة. الحساب مقفل حتى يفكّه أحد المسؤولين.",
  "auth.attemptsLeft": "بقيت ‏{n}‏ محاولات قبل قفل الحساب.",
  "auth.mfaCodeHint": "الرمز التجريبي",

  "auth.selectTenantTitle": "اختر المنشأة",
  "auth.selectTenantLede": "حسابك يصل إلى أكثر من منشأة. كل ما تراه بعد ذلك محصور في المنشأة التي تختارها.",
  "auth.selectBrandTitle": "اختر العلامة التجارية",
  "auth.selectBrandLede": "التقارير والقوائم والأسعار تختلف بين العلامات. يمكنك تغيير ذلك لاحقًا من الشريط العلوي.",
  "auth.selectBranchTitle": "اختر الفرع",
  "auth.selectBranchLede": "حدّد مكان عملك اليوم. العمليات المباشرة والنقد والمخزون كلها تتبع هذا الاختيار.",
  "auth.allBrands": "كل العلامات",
  "auth.allBranches": "كل الفروع",
  "auth.continue": "متابعة",
  "auth.branchCount": "‏{n} فروع",
  "auth.scopeLocked": "دورك مسند إلى فرع واحد، ولذلك لا يمكن تغيير هذا.",

  "auth.sessionExpiredTitle": "انتهت جلستك",
  "auth.sessionExpiredBody": "تم تسجيل خروجك بعد فترة من عدم النشاط. هذا يحمي نقطة البيع ودرج النقد عند ترك الجهاز دون مراقبة.",
  "auth.sessionExpiredWhat": "لم يُفقد شيء مما حفظته. أي طلب مفتوح على جهاز ما لا يزال مفتوحًا.",
  "auth.signInAgain": "تسجيل الدخول من جديد",

  "auth.accessDeniedTitle": "لا تملك صلاحية الوصول إلى هذه الصفحة",
  "auth.accessDeniedBody": "دورك لا يحمل الصلاحية التي تتطلبها هذه الصفحة. لم يتغيّر شيء، وقد سُجّلت هذه المحاولة في سجل التدقيق.",
  "auth.accessDeniedNeeds": "الصلاحية المطلوبة",
  "auth.accessDeniedRole": "دورك الحالي",
  "auth.requestAccess": "طلب صلاحية",
  "auth.requestSent": "أُرسل الطلب إلى المسؤول عنك.",
  "auth.goBack": "رجوع",
  "auth.goHome": "الذهاب إلى لوحتي",

  "auth.deviceTitle": "تسجيل هذا الجهاز",
  "auth.deviceLede": "يجب تسجيل الجهاز على فرع قبل أن يتمكن من أخذ طلب أو فتح درج النقد.",
  "auth.deviceName": "اسم الجهاز",
  "auth.deviceNameHint": "كيف يظهر هذا الجهاز في التقارير، مثل «كاشير أمامي ٢».",
  "auth.pairingCode": "رمز الإقران",
  "auth.pairingHint": "ثمانية أرقام، يصدرها مدير من الإعدادات ‹ الأجهزة.",
  "auth.deviceType": "نوع الجهاز",
  "auth.deviceBranch": "الفرع",
  "auth.printerAttached": "طابعة إيصالات متصلة",
  "auth.registerDevice": "تسجيل الجهاز",
  "auth.deviceRegisteredTitle": "تم تسجيل الجهاز",
  "auth.deviceRegisteredBody": "أصبح هذا الجهاز مقترنًا، ومعرّفه يُرفق بكل معاملة يسجّلها.",
  "auth.deviceId": "معرّف الجهاز",
  "auth.deviceKiosk": "كشك طلب ذاتي",
  "auth.deviceLedeLive": "اربط هذا الجهاز بأحد الأجهزة الطرفية المسجَّلة للمستأجر. سيُسجَّل كل طلب ودفعة يتم إجراؤها باسم ذلك الجهاز.",
  "auth.deviceNeedsSession": "تسجيل جهاز طرفي إجراء يتطلب صلاحية. سجّل الدخول أولًا ثم عد إلى هنا.",
  "auth.deviceNoTerminals": "لا توجد أجهزة طرفية مسجَّلة لهذا المستأجر بعد. أضف الأول أدناه.",
  "auth.deviceRegisterNew": "تسجيل جهاز طرفي جديد",
  "auth.deviceDemoNote": "لا يوجد خادم مهيّأ، لذلك لم يُربط أي جهاز. اضبط NEXT_PUBLIC_API_URL ثم سجّل مرة أخرى لربط هذا الجهاز فعليًا.",
  "auth.openPos": "فتح نقطة البيع",

  "auth.posPinTitle": "أدخل رمزك",
  "auth.posPinLede": "أربعة أرقام. راجع المشرف إن نسيت رمزك.",
  "auth.pinWrong": "الرمز غير معروف.",
  "auth.pinClear": "مسح",
  "auth.switchUser": "تبديل المستخدم",
  "auth.signedInAs": "مسجّل الدخول باسم",

  // -- التهيئة ---------------------------------------------------------------
  "onb.title": "تهيئة مطعمك",
  "onb.lede": "خمس عشرة خطوة من حساب فارغ إلى أول طلب. يمكنك المغادرة في أي لحظة والعودة إلى حيث توقفت.",
  "onb.stepOf": "الخطوة ‏{n}‏ من ١٥",
  "onb.saveAndExit": "حفظ والمتابعة لاحقًا",
  "onb.savedDraft": "حُفظ التقدّم. سجّل الدخول مجددًا للمتابعة.",
  "onb.resume": "متابعة التهيئة",
  "onb.restart": "البدء من جديد",
  "onb.completed": "مكتملة",
  "onb.current": "جارية",
  "onb.upcoming": "لم تبدأ",
  "onb.skipped": "متخطّاة",
  "onb.optional": "اختيارية",
  "onb.example": "مثال",
  "onb.importMenu": "الاستيراد من ملف جدول بدلًا من ذلك",
  "onb.importMenuHint": "ارفع ملف CSV بالأعمدة: التصنيف، الاسم بالإنجليزية، الاسم بالعربية، السعر. يتوفر قالب جاهز.",
  "onb.importPreview": "قُرئ ‏{n}‏ صفًا",
  "onb.downloadTemplate": "تنزيل القالب",

  "onb.tenantTitle": "أنشئ منشأتك",
  "onb.tenantLede": "المنشأة هي قمة الهيكل. العلامات والفروع والموظفون وكل تقرير تقع تحتها.",
  "onb.tenantNameEn": "اسم المنشأة (بالإنجليزية)",
  "onb.tenantNameAr": "اسم المنشأة (بالعربية)",
  "onb.country": "بلد التشغيل",

  "onb.businessTitle": "بيانات النشاط",
  "onb.businessLede": "تُستخدم في الإيصالات والإقرارات الضريبية ومستندات الموردين. يمكن إكمالها لاحقًا، لكن الإيصالات ستعرض قيمة مؤقتة حتى ذلك الحين.",
  "onb.legalName": "الاسم القانوني المسجّل",
  "onb.taxNumber": "رقم التسجيل الضريبي",
  "onb.commercialReg": "رقم السجل التجاري",
  "onb.addressLine": "عنوان الشارع",
  "onb.city": "المدينة",
  "onb.contactPhone": "هاتف التواصل",
  "onb.contactEmail": "بريد التواصل",

  "onb.brandTitle": "أنشئ أول علامة تجارية",
  "onb.brandLede": "العلامة تملك قائمة وقائمة أسعار. المجموعات التي تدير أكثر من مفهوم تفصل بينها هنا.",
  "onb.brandNameEn": "اسم العلامة (بالإنجليزية)",
  "onb.brandNameAr": "اسم العلامة (بالعربية)",
  "onb.concept": "المفهوم",
  "onb.conceptCasual": "مطعم عائلي",
  "onb.conceptQsr": "خدمة سريعة",
  "onb.conceptCafe": "مقهى",
  "onb.conceptCloud": "مطبخ سحابي",
  "onb.conceptFine": "مطعم فاخر",
  "onb.accentColour": "لون العلامة",

  "onb.branchTitle": "أضف أول فرع",
  "onb.branchLede": "الفرع مكان فعلي يمارس البيع. المخزون والنقد والموظفون كلهم ينتمون إلى فرع.",
  "onb.branchNameEn": "اسم الفرع (بالإنجليزية)",
  "onb.branchNameAr": "اسم الفرع (بالعربية)",
  "onb.seats": "عدد المقاعد",
  "onb.seatsHint": "صفر للمطبخ السحابي أو فرع التوصيل فقط.",
  "onb.orderTypes": "أنواع الطلبات التي يقبلها الفرع",

  "onb.localeTitle": "البلد والعملة",
  "onb.localeLede": "حزمة الدولة تحدّد محرك الضريبة والتقريب وبداية الأسبوع ومتطلبات الإيصال. لا يمكن تغييرها بعد أول عملية بيع.",
  "onb.currency": "العملة",
  "onb.timezone": "المنطقة الزمنية",
  "onb.defaultLocale": "لغة الواجهة الافتراضية",
  "onb.numerals": "استخدام الأرقام العربية الهندية (٠١٢٣)",
  "onb.numeralsHint": "يؤثر على العرض فقط. القيم تُخزَّن بالطريقة نفسها في الحالتين.",

  "onb.taxTitle": "إعدادات الضريبة",
  "onb.taxLede": "كون أسعار القائمة شاملة للضريبة أو لا يغيّر كل إجمالي في النظام. تأكّد من مطابقتها لطريقة تسعيرك الحالية.",
  "onb.pricingMode": "أسعار القائمة",
  "onb.taxInclusive": "شاملة الضريبة — السعر المعروض هو ما يدفعه العميل",
  "onb.taxExclusive": "غير شاملة — تُضاف الضريبة عند الدفع",
  "onb.standardRate": "النسبة القياسية (٪)",
  "onb.reducedRate": "النسبة المخفّضة (٪)",
  "onb.roundingMode": "التقريب",
  "onb.computationLevel": "حساب الضريبة على مستوى",
  "onb.perLine": "السطر",
  "onb.perOrder": "الطلب",

  "onb.dayTitle": "اليوم التشغيلي",
  "onb.dayLede": "المطعم الذي يغلق بعد منتصف الليل يقيّد تلك المبيعات على اليوم الذي فتح فيه. حدّد الساعة التي ينتهي عندها اليوم التجاري.",
  "onb.closingTime": "ينتهي اليوم التشغيلي عند",
  "onb.closingHint": "المبيعات قبل هذا الوقت تُحسب على التاريخ السابق.",
  "onb.weekStart": "يبدأ الأسبوع يوم",
  "onb.autoClose": "إغلاق اليوم التشغيلي تلقائيًا في هذا الوقت",

  "onb.categoriesTitle": "تصنيفات القائمة",
  "onb.categoriesLede": "الصف العلوي من الأزرار على نقطة البيع. من أربعة إلى ثمانية هو الأنسب لشاشة عشر بوصات.",
  "onb.addCategory": "إضافة تصنيف",
  "onb.categoryNameEn": "اسم التصنيف (بالإنجليزية)",
  "onb.categoryNameAr": "اسم التصنيف (بالعربية)",

  "onb.itemsTitle": "أصناف القائمة",
  "onb.itemsLede": "ما يكفي لأخذ طلب حقيقي. الوصفات والإضافات والصور يمكن أن تنتظر — الصنف يُباع دونها.",
  "onb.addItem": "إضافة صنف",
  "onb.itemNameEn": "اسم الصنف (بالإنجليزية)",
  "onb.itemNameAr": "اسم الصنف (بالعربية)",
  "onb.itemCategory": "التصنيف",
  "onb.itemPrice": "السعر",
  "onb.itemTaxClass": "الفئة الضريبية",
  "onb.itemPrep": "زمن التحضير (دقائق)",
  "onb.taxStandard": "قياسية",
  "onb.taxReduced": "مخفّضة",
  "onb.taxZero": "بنسبة صفر",
  "onb.taxExempt": "معفاة",

  "onb.paymentsTitle": "وسائل الدفع",
  "onb.paymentsLede": "ما يجوز لنقطة البيع قبوله. أي وسيلة معطّلة هنا لا تظهر في شاشة الدفع.",
  "onb.cashRounding": "تقريب المبالغ النقدية إلى",
  "onb.cashRoundingHint": "أصغر عملة معدنية لا تزال متداولة. مبالغ البطاقة والمحفظة لا تُقرَّب أبدًا.",

  "onb.employeeTitle": "أضف أول موظف",
  "onb.employeeLede": "لا بد من شخص يستطيع فتح نقطة البيع. يمكن إضافة بقية الفريق لاحقًا.",
  "onb.employeeNameEn": "الاسم الكامل (بالإنجليزية)",
  "onb.employeeNameAr": "الاسم الكامل (بالعربية)",
  "onb.position": "الوظيفة",
  "onb.employeePin": "رمز الجهاز (٤ أرقام)",
  "onb.startDate": "تاريخ المباشرة",
  "onb.assignRole": "الدور",

  "onb.terminalTitle": "تسجيل جهاز",
  "onb.terminalLede": "الجهاز الذي سيأخذ الطلب. يُولَّد له رمز إقران هنا.",
  "onb.terminalName": "اسم الجهاز",
  "onb.cashDrawer": "درج نقد متصل",

  "onb.previewTitle": "راجع إعداداتك",
  "onb.previewLede": "كل ما يلي قابل للتغيير لاحقًا من الإعدادات. راجع وضع الضريبة واليوم التشغيلي بعناية — تصحيحهما بعد بدء البيع مرهق.",
  "onb.previewEdit": "تعديل",
  "onb.previewIncomplete": "غير محدد",

  "onb.shiftTitle": "افتح أول وردية",
  "onb.shiftLede": "احسب النقد في الدرج وأعلنه. كل فرق عند الإغلاق يُقاس على هذا الرقم.",
  "onb.openingFloat": "الرصيد الافتتاحي",
  "onb.openShift": "فتح الوردية",

  "onb.sampleTitle": "خذ طلبًا تجريبيًا",
  "onb.sampleLede": "طلب واحد يمرّ بالنظام كله: نقطة البيع تأخذه، المطبخ يراه، المخزون يتحرك، والدرج يتوازن.",
  "onb.sampleRun": "إنشاء الطلب التجريبي",
  "onb.sampleRunning": "جارٍ الإرسال إلى المطبخ",
  "onb.sampleDone": "أول طلب لك جاهز على منصة التقديم.",
  "onb.checklistTitle": "قائمة التحقق",
  "onb.checklistLede": "ما هو جاهز، وما يستحق الإنجاز قبل فتح الأبواب.",
  "onb.goToConsole": "الذهاب إلى لوحة الإدارة",
  "onb.goToPos": "فتح نقطة البيع",
  "onb.laterRecipes": "أضف الوصفات ليعمل حساب تكلفة الطعام وخصم المخزون",
  "onb.laterSuppliers": "أضف الموردين وأصدر أول أمر شراء",
  "onb.laterStaff": "أضف بقية الفريق وابنِ جدول الورديات",
  "onb.laterStations": "وجّه الأصناف إلى محطات المطبخ",

  // -- الهيكل والبحث والتنبيهات والمزامنة ------------------------------------
  "shell.search": "بحث",
  "shell.searchPlaceholder": "ابحث في الطلبات والأصناف والموردين والموظفين…",
  "shell.searchHint": "اضغط / للبحث، و⌘K للأوامر",
  "shell.noResults": "لا نتائج مطابقة",
  "shell.noResultsHint": "راجع الإملاء، أو وسّع مرشّحات الفرع والتاريخ.",
  "shell.recent": "الأحدث",
  "shell.commands": "الأوامر",
  "shell.goTo": "الانتقال إلى",
  "shell.notifications": "التنبيهات",
  "shell.noNotifications": "لا شيء يحتاج انتباهك",
  "shell.noNotificationsHint": "تنبيهات فروق النقد ونفاد المخزون والطلبات المتأخرة تظهر هنا.",
  "shell.markAllRead": "تعليم الكل كمقروء",
  "shell.approvals": "الاعتمادات",
  "shell.approvalsPending": "‏{n} بالانتظار",
  "shell.noApprovals": "لا اعتمادات منتظرة",
  "shell.viewAll": "عرض الكل",
  "shell.businessDay": "اليوم التشغيلي",
  "shell.dateRange": "الفترة",
  "shell.today": "اليوم",
  "shell.yesterday": "أمس",
  "shell.last7": "آخر ٧ أيام",
  "shell.last30": "آخر ٣٠ يومًا",
  "shell.thisMonth": "هذا الشهر",
  "shell.lastMonth": "الشهر الماضي",
  "shell.custom": "فترة مخصّصة",
  "shell.from": "من",
  "shell.to": "إلى",
  "shell.apply": "تطبيق",
  "shell.dismiss": "إخفاء",

  "sync.online": "متصل",
  "sync.degraded": "اتصال بطيء",
  "sync.offline": "غير متصل",
  "sync.syncing": "جارٍ المزامنة",
  "sync.conflict": "تعارض مزامنة",
  "sync.synced": "تمت المزامنة",
  "sync.pending": "‏{n} بانتظار الإرسال",
  "sync.queueTitle": "تغييرات معلّقة",
  "sync.queueLede": "سُجّلت هذه على هذا الجهاز ولم تصل الخادم بعد. لا شيء مفقود — تُرسل فور عودة الاتصال.",
  "sync.queueEmpty": "أُرسل كل ما على هذا الجهاز.",
  "sync.lastSynced": "آخر مزامنة",
  "sync.retryNow": "إرسال الآن",
  "sync.conflictTitle": "هذا التغيير يتعارض مع الخادم",
  "sync.conflictBody": "تغيّر السجل على الخادم بينما كان الجهاز غير متصل. اختر النسخة التي تريد الاحتفاظ بها.",
  "sync.keepLocal": "الاحتفاظ بنسخة هذا الجهاز",
  "sync.keepServer": "التجاهل والاحتفاظ بنسخة الخادم",
  "sync.offlineNote": "العمل دون اتصال. الطلبات تُحفظ على هذا الجهاز وتُرسل عند عودة الاتصال.",
  "sync.simulate": "محاكاة الاتصال",
  "sync.statusPending": "بانتظار المزامنة",
  "sync.statusFailed": "فشلت المزامنة",
  "menu.priceSaved": "تم حفظ السعر.",
  "menu.priceListCreated": "تم إنشاء قائمة الأسعار.",
  "menu.priceHint": "أدخل السعر المعروض، لا الوحدات الصغرى.",
  "menu.currentPrice": "السعر الحالي",
  "menu.newPriceList": "قائمة أسعار جديدة",
  "menu.scopeTenant": "كل المستأجر",
  "menu.scopeBrand": "علامة واحدة",
  "menu.scopeBranch": "فرع واحد",
  "nav.menus": "القوائم",
  "menu.menusTitle": "القوائم",
  "menu.menusSubtitle": "القائمة التي يقدّمها كل فرع، وأيّها تُرجَّح عند تعدّدها.",
  "menu.menuPriorityHint": "تُرجَّح الأولوية الأعلى السارية. امنح القوائم المتداخلة أولويات مختلفة.",
  "menu.assignedBranches": "الفروع المسندة",
  "menu.noBranches": "غير مسندة إلى أي فرع، فلا أحد يقدّمها.",
  "menu.assignBranch": "إسناد إلى فرع",
  "menu.branchAssigned": "تم إسناد الفرع.",
  "menu.branchUnassigned": "تمت إزالة الفرع.",
  "menu.menuCreated": "تم إنشاء القائمة.",
  "menu.menuActivated": "تم تفعيل القائمة.",
  "menu.menuDeactivated": "تم تعطيل القائمة.",
  "menu.newMenu": "قائمة جديدة",
  "menu.ambiguousTitle": "ترجيح غير محسوم",
  "menu.ambiguousNote": "قائمتان فعّالتان أو أكثر تتشاركان الأولوية نفسها على الفرع ذاته، فلا يمكن حسم أيّها تُطبَّق.",
  "menu.resolutionTitle": "ما يُرجَّح لهذا الفرع",
  "menu.resolutionClear": "الترجيح محسوم — تُطبَّق القائمة الأولى أدناه.",
  "common.branches": "فروع",
  "common.remove": "إزالة",
  "common.add": "إضافة",
  "common.activate": "تفعيل",
  "common.deactivate": "تعطيل",
  "menu.itemCreated": "تم إنشاء الصنف.",
  "menu.itemPlaced": "تم تحديث الفئة.",
  "menu.variantActivated": "تم تفعيل الخيار.",
  "menu.variantDeactivated": "تم تعطيل الخيار.",
  "menu.variantAdded": "تمت إضافة الخيار.",
  "menu.groupLinked": "تم ربط مجموعة الإضافات.",
  "menu.noVariants": "لا توجد خيارات بعد. يحتاج الصنف إلى خيار واحد على الأقل ليكون قابلًا للبيع.",
  "menu.newVariant": "خيار جديد",
  "menu.newItem": "صنف جديد",
  "menu.barcode": "الباركود",
  "menu.variantPriceNote": "يبدأ الخيار الجديد بلا سعر. حدّد سعره في قائمة أسعار قبل بيعه.",
  "menu.placementHint": "لا يظهر الصنف في القائمة إلا بعد وضعه في فئة.",
  "menu.attachGroup": "ربط مجموعة إضافات",
  "menu.attachGroupHint": "لا يمكن للواجهة سرد مجموعات الصنف المرتبطة، بل الإضافة إليها فقط.",
  "menu.modifierGroups": "مجموعات الإضافات",
  "menu.kitchenNameHint": "الاسم المختصر الذي يقرأه الطاهي على التذكرة.",
  "menu.category": "الفئة",
  "menu.groupCreated": "تم إنشاء مجموعة الإضافات.",
  "menu.modifierAdded": "تمت إضافة الإضافة.",
  "menu.noModifiers": "لا تحتوي هذه المجموعة على إضافات بعد.",
  "menu.newModifier": "إضافة جديدة",
  "menu.newGroup": "مجموعة إضافات جديدة",
  "menu.modifierKindHint": "يحدّد كيف يستهلك السطر المخزون — إضافة أو إزالة أو استبدال.",
  "menu.minSelections": "أقل عدد اختيارات",
  "menu.maxSelections": "أكبر عدد اختيارات",
  "role.newRole": "دور جديد",
  "role.newRoleNote": "يبدأ الدور الجديد بلا صلاحيات. امنحها من محرّر الدور بعد إنشائه.",
  "role.created": "تم إنشاء الدور.",
  "role.assigned": "تم إسناد الدور.",
  "role.removed": "تمت إزالة الدور.",
  "role.assignRole": "الدور",
  "role.membershipsTitle": "عضوياتك",
  "role.membershipsNote": "تتيح الواجهة عضويات الحساب المسجّل فقط، لذا يمكن إسناد الأدوار هنا لهذا الحساب وحده.",
  "common.description": "الوصف",
  "inv.countOpened": "تم فتح جلسة الجرد.",
  "inv.countPosted": "تم ترحيل الجرد. المخزون الآن مطابق لما تم عدّه.",
  "inv.countRecorded": "تم تسجيل الكمية المعدودة.",
  "inv.countedHint": "ما هو موجود فعليًا على الرف.",
  "inv.newCount": "فتح جرد",
  "inv.newCountNote": "فتح الجلسة يجمّد الكمية المتوقعة لكل صنف ضمن النطاق، فلا تغيّر حركة لاحقة ما يُقاس عليه الجرد.",
  "inv.blindCount": "جرد أعمى",
  "inv.transferDispatched": "تم إرسال التحويل.",
  "inv.transferReceived": "تم استلام التحويل.",
  "inv.newTransfer": "تحويل جديد",
  "inv.dispatch": "إرسال",
  "inv.sameLocation": "اختر وجهة مختلفة.",
  "inv.quantity": "الكمية",
  "inv.item": "الصنف",
  "inv.reason": "السبب",
  "inv.reorderTitle": "عند نقطة إعادة الطلب أو تحتها",
  "inv.reorderNote": "يحسبها الخادم مقابل نقطة إعادة الطلب لكل موقع، لا تُرشَّح من الجدول أعلاه.",
  "inv.reorderClear": "لا شيء عند نقطة إعادة الطلب.",
  "inv.reorderQuantity": "كمية إعادة الطلب",
  "inv.reorderQuantityHint": "الكمية التي تُطلب عند بلوغ النقطة.",
  "inv.reorderPointHint": "أعد الطلب متى بلغ المتاح هذا الحد.",
  "inv.reorderSaved": "تم حفظ إعداد إعادة الطلب.",
  "inv.reorderConfigNote": "هذه الحدود لكل صنف ولكل موقع، فيمكن للفرع والمستودع إعادة الطلب عند نقاط مختلفة.",
  "inv.negativeClear": "لا يوجد موقع برصيد سالب.",
  "inv.negativeAction": "الرصيد السالب يعني تسجيل حركة بلا إيصالها. ابحث عن الإيصال المفقود بدل تعديل الرصيد.",
  "inv.reconciliationTitle": "مطابقة دفتر الحركات",
  "inv.reconciliationNote": "مجموع الحركات مقابل إسقاط مستويات المخزون الذي يُفترض أن يساويه.",
  "inv.reconciled": "دفتر الحركات والإسقاط متطابقان.",
  "inv.notReconciled": "دفتر الحركات والإسقاط غير متطابقين. كل أرقام التكلفة اللاحقة مشكوك فيها حتى يُحل هذا.",
  "inv.ledger": "الدفتر",
  "inv.projected": "الإسقاط",
  "org.newBrand": "علامة جديدة",
  "org.brandCreated": "تم إنشاء العلامة.",
  "org.newWarehouse": "مستودع جديد",
  "org.warehouseCreated": "تم إنشاء المستودع.",
  "org.warehouseType": "النوع",
  "org.warehouseCentral": "مركزي",
  "org.warehouseBranch": "تابع لفرع",
  "org.warehouseVirtual": "افتراضي",
  "org.newKitchen": "مطبخ مركزي جديد",
  "org.kitchenCreated": "تم إنشاء المطبخ المركزي.",
  "org.colour": "اللون",
  "menu.newCategory": "فئة جديدة",
  "menu.categoryCreated": "تم إنشاء الفئة.",
  "inv.newItem": "صنف مخزون جديد",
  "inv.itemCreated": "تم إنشاء صنف المخزون.",
  "inv.baseUnitId": "معرّف الوحدة الأساسية",
  "inv.baseUnitIdHint": "معرّف inventory.uom حقيقي. لا تنشر الواجهة كتالوج وحدات للاختيار منه.",
  "inv.newItemUnitNote": "لا يمكن تغيير الوحدة الأساسية بعد وجود أي حركة على الصنف (FR-INV-002)، فاخترها بعناية.",
  "inv.costingWeighted": "المتوسط المرجّح",
  "inv.costingFifo": "الوارد أولًا صادر أولًا",
  "inv.costingStandard": "معياري",
  "org.newBranch": "فرع جديد",
  "org.branchCreated": "تم إنشاء الفرع.",
  "org.reassignBrand": "النقل إلى علامة أخرى",
  "org.reassignBrandHint": "ضمن المستأجر نفسه فقط.",
  "org.brandReassigned": "تم نقل الفرع إلى العلامة الجديدة.",
  "org.operatingHours": "ساعات العمل",
  "org.noOperatingHours": "لم تُحدَّد ساعات عمل لهذا الفرع.",
  "org.newOperatingHours": "إضافة ساعات عمل",
  "org.operatingHoursAdded": "تمت إضافة ساعات العمل.",
  "org.dayOfWeek": "اليوم",
  "org.opensAt": "يفتح في",
  "org.closesAt": "يغلق في",
  "org.overnight": "يمتد بعد منتصف الليل",
  "org.printRouting": "توجيه الطباعة",
  "org.noPrintRouting": "لا يوجد توجيه إلى طابعة بعد.",
  "org.newPrintRouting": "إضافة توجيه طباعة",
  "org.printRoutingAdded": "تمت إضافة توجيه الطباعة.",
  "org.documentType": "المستند",
  "org.docReceipt": "الإيصال",
  "org.docKitchen": "تذكرة المطبخ",
  "org.docBar": "تذكرة البار",
  "org.printerTarget": "الطابعة",
  "org.stationRouting": "توجيه المحطات",
  "org.noStationRouting": "لا قواعد توجيه، فلا شيء يصل إلى محطة تلقائيًا.",
  "org.newStationRouting": "إضافة قاعدة توجيه",
  "org.stationRoutingAdded": "تمت إضافة قاعدة التوجيه.",
  "org.stationRoutingHint": "تفوز المطابقة الأدق ذات الأولوية الأعلى. اترك الفئة فارغة لقاعدة شاملة.",
  "org.station": "المحطة",
  "common.sunday": "الأحد",
  "common.monday": "الاثنين",
  "common.tuesday": "الثلاثاء",
  "common.wednesday": "الأربعاء",
  "common.thursday": "الخميس",
  "common.friday": "الجمعة",
  "common.saturday": "السبت",
  "recipes.newRecipe": "وصفة جديدة",
  "recipes.newRecipeNote": "تبدأ الوصفة بلا نسخ. أنشئ نسخة مسوّدة، أضف بنودها، ثم انشرها.",
  "recipes.created": "تم إنشاء الوصفة.",
  "recipes.published": "تم نشر النسخة. أصبحت السابقة متجاوَزة.",
  "recipes.typeMenuItem": "صنف قائمة",
  "recipes.typeSubRecipe": "وصفة فرعية",
  "recipes.typeProduction": "صنف إنتاج",
  "recipes.versions": "النسخ",
  "recipes.noVersions": "لا توجد نسخ بعد.",
  "recipes.substituteGroups": "مجموعات البدائل",
  "recipes.substituteGroupsNote": "يمكن لبند الوصفة تسمية مجموعة بدل مكوّن واحد، فلا يجعل نفاد أحد الأعضاء الوصفة غير قابلة للتكلفة.",
  "recipes.noSubstituteGroups": "لا توجد مجموعات بدائل معرّفة.",
  "recipes.newSubstituteGroup": "مجموعة بدائل جديدة",
  "recipes.substituteGroupCreated": "تم إنشاء مجموعة البدائل.",
  "recipes.addSubstituteMember": "إضافة عضو",
  "recipes.substituteMemberAdded": "تمت إضافة العضو.",
  "ops.tableDefinitions": "مخطط الصالة",
  "ops.tableDefinitionsNote": "الطاولات التي يملكها الفرع. الإشغال الحي أعلاه حالة جهاز — تنمذج الواجهة اسم الطاولة وقسمها ومقاعدها، لا ما يجري عليها.",
  "ops.noTables": "لا توجد طاولات معرّفة لهذا الفرع.",
  "ops.newTable": "طاولة جديدة",
  "ops.tableLabel": "الاسم",
  "ops.section": "القسم",
  "ops.tableCreated": "تم إنشاء الطاولة.",
  "ops.tableUpdated": "تم تحديث الطاولة.",
  "pos.noTerminal": "هذا الجهاز غير مرتبط بجهاز طرفي",
  "pos.noTerminalNote": "يُسجَّل كل طلب ودفعة باسم جهاز طرفي، فلا يمكن فتح نقطة البيع قبل ربط هذا الجهاز بواحد.",
  "pos.orderOpened": "تم فتح الطلب.",
  "pos.openOrder": "فتح الطلب",
  "pos.branchFromTerminal": "يأتي الفرع من الجهاز الطرفي المرتبط، لا من محدّد النطاق في لوحة التحكم.",
  "pos.searchPlaceholder": "ابحث في القائمة",
  "pos.lineAdded": "تمت إضافة السطر.",
  "pos.lineVoided": "تم إلغاء السطر.",
  "pos.noSellableVariant": "لا يحتوي هذا الصنف على خيارات، فلا شيء لتسجيله. أضف خيارًا من شاشة القائمة.",
  "pos.noActiveOrder": "لا يوجد طلب مفتوح.",
  "pos.noLines": "لا شيء على الفاتورة بعد.",
  "pos.pending": "لم يُرسَل بعد",
  "pos.capturePayment": "تسجيل الدفعة",
  "pos.paymentCaptured": "تم تسجيل الدفعة.",
  "pos.closeOrder": "مغادرة هذا الطلب",
  "pos.voidReasonHint": "إلزامي. ترفض قاعدة البيانات سطرًا ملغى بلا سبب.",
  "pos.noReasonCodes": "لا توجد رموز أسباب لهذا المستأجر، فلا يمكن إلغاء سطر. أضف واحدًا من المخزون.",
  "pos.settleNote": "الدفعة التي تغطي كامل المتبقي تُسدّد الطلب وتُتمّه في الطلب نفسه. وما دون ذلك يُسجَّل دفعةً جزئية ويبقى الرصيد مفتوحًا.",
  "pos.tenderedHint": "ما سلّمه الضيف. يشتق الخادم تقريب النقد من هذا.",
  "pos.terminalRefHint": "سجلك الخاص لعملية البطاقة الخارجية المكتملة بالفعل.",
  "pos.unsupportedTitle": "غير متاح مع هذا الخادم",
  "pos.unsupportedNote": "تُعرَض بدل إخفائها، لأن نقطة بيع تبدو وكأنها تطبّق خصمًا ولا تفعل أسوأ من واحدة تقول إنها لا تستطيع.",
  "pos.unsupportedDiscount": "الخصومات وتجاوز الأسعار — لا توجد واجهة.",
  "pos.unsupportedComp": "الأصناف المجانية — لا توجد واجهة.",
  "pos.unsupportedSplit": "تقسيم الفواتير — لا توجد واجهة. أما التسديد الكامل فمدعوم.",
  "pos.unsupportedRefund": "المبالغ المستردة والإلغاء بعد الإرسال — لا توجد واجهة.",
  "pos.unsupportedTable": "حالة الطاولة ونقل الطلب بينها — غير مُنمذجة.",
  "pos.unsupportedCourse": "الأطباق وأرقام المقاعد وملاحظات السطر بعد التسجيل — لا توجد واجهة.",
  "pos.unsupportedKds": "استلام شاشة المطبخ واستدعاؤها — لا توجد واجهة.",
  "shift.openTitle": "فتح الدرج",
  "shift.drawer": "الدرج",
  "shift.openingFloatHint": "النقد المعدود في الدرج عند بداية الوردية.",
  "pos.orderSettled": "سُدِّد الطلب وأُتمّ.",
  "shift.liveTitle": "هذا الدرج",
  "shift.movementRecorded": "سُجِّلت الحركة.",
  "shift.movementAmountHint": "مبلغ موجب. الزر الذي تضغطه هو ما يحدد الاتجاه.",
  "shift.reasonRequired": "مطلوب في الأنواع الثلاثة جميعها — والفارغ مرفوض.",
  "shift.closeDrawer": "إغلاق الدرج",
  "shift.countMode": "نمط العدّ",
  "shift.countModeBlind": "أعمى",
  "shift.countModeOpen": "مكشوف",
  "shift.blindLiveNote": "عدّ أعمى. يحجب الخادم المبلغ المتوقَّع وحدّ التسامح حتى يُثبَّت عدّك، فلا يوجد هنا — عن قصد — ما تقيس نفسك عليه.",
  "shift.openCountNote": "عدّ مكشوف. المبلغ المتوقَّع هنا معاينة فقط — يعيد الخادم احتسابه فعليًا عند تثبيت العدّ.",
  "shift.noPolicy": "لا توجد سياسة إغلاق نقدي لهذا الفرع، فلا حدّ تسامح يُحكَم به على العدّ. انشر سياسة قبل الإغلاق.",
  "shift.tolerance": "حدّ التسامح",
  "shift.countBy": "طريقة العدّ",
  "shift.countByTotal": "مجموع واحد",
  "shift.countByDenomination": "بالفئات",
  "shift.faceValue": "القيمة الاسمية",
  "shift.addDenomination": "إضافة فئة",
  "shift.declare": "تثبيت العدّ",
  "shift.declared": "ثُبِّت العدّ.",
  "shift.closedWithin": "ضمن حدّ التسامح. أُغلق الدرج.",
  "shift.frozenTitle": "تجاوز حدّ التسامح — مجمَّد بانتظار مدير",
  "shift.frozenNote": "قرار المدير هو المخرج الوحيد من هذه الحالة. تبقى الجلسة مجمَّدة حتى يُسجَّل قرار، والرفض يبقيها مجمَّدة لمحاولة أخرى.",
  "shift.managerCode": "رمز موظف المدير",
  "shift.managerPin": "رمز المدير السري",
  "shift.decisionReason": "السبب",
  "shift.decisionReasonHint": "مطلوب فوق حدّ التسامح — FR-FIN-006.",
  "shift.comment": "تعليق",
  "shift.approveClose": "اعتماد وإغلاق",
  "shift.rejectClose": "رفض",
  "shift.approvedOutcome": "اعتُمد. أُغلق الدرج.",
  "shift.rejectedOutcome": "رُفض. يبقى الدرج مجمَّدًا — ويمكن تسجيل قرار جديد.",
  "shift.policyTitle": "سياسة الإغلاق النقدي",
  "shift.policyNote": "كل حفظ ينشر نسخة جديدة غير قابلة للتعديل. لا شيء يُعدَّل في مكانه، ووقت السريان في الماضي مرفوض.",
  "shift.policyTolerance": "حدّ تسامح الفروق",
  "shift.policyToleranceHint": "قيمة مطلقة، والصفر صالح — ومعناه أن كل فرق يذهب إلى مدير.",
  "shift.policyExpiry": "انتهاء صلاحية الاعتماد (ثوانٍ)",
  "shift.policyEffectiveFrom": "يسري من",
  "shift.policyEffectiveFromHint": "الفراغ يعني فورًا، محسوبًا على وقت قاعدة البيانات.",
  "shift.publishPolicy": "نشر نسخة",
  "shift.policyPublished": "نُشرت نسخة السياسة.",
  "shift.selectBranch": "اختر فرعًا لنشر سياسة له.",
  "menu.recipeEffects": "آثار الوصفة",
  "menu.recipeEffectsNote": "ما يفعله هذا التعديل بالخصم من المخزون، بالترتيب. بدونها يخصم البيع المعدَّل الوصفة الأساسية، فينحرف سجل المخزون بمقدار التعديل تمامًا.",
  "menu.noRecipeEffects": "لا آثار على الوصفة — هذا التعديل يحرّك المال فقط.",
  "menu.editEffects": "تحرير الآثار",
  "menu.effectsSaved": "حُفظت آثار الوصفة.",
  "menu.effectOperation": "العملية",
  "menu.effectAdd": "إضافة",
  "menu.effectRemoveAll": "إزالة الكل",
  "menu.effectComponent": "المكوّن",
  "menu.effectStockItem": "صنف مخزون",
  "menu.effectSubRecipe": "وصفة فرعية",
  "menu.effectQuantity": "الكمية",
  "menu.addEffect": "إضافة أثر",
  "menu.effectReplaceNote": "الحفظ يستبدل المجموعة كاملة — لا تحرير لأثر مفرد في الواجهة.",
  "menu.effectIncomplete": "كل أثر يحتاج مكوّنًا، و«الإضافة» تحتاج كمية.",
  "menu.effectNoUnit": "هذا الصنف لا يحمل معرّف وحدة، فلا يمكن حفظ «إضافة» عليه.",
  "orders.outstanding": "المتبقي",
  "orders.amount": "المبلغ",
  "orders.tendered": "المبلغ المُسلَّم",
  "orders.terminalReference": "مرجع الجهاز",
  "orders.card": "بطاقة (جهاز خارجي)",
  "orders.net": "المجموع الفرعي",
  "orders.grandTotal": "الإجمالي",
};
