/**
 * English dictionary for the management console.
 *
 * Flat keys rather than a nested object: the shape stays stable as the app
 * grows, and `ar.ts` is typed against `ConsoleCopy` so a missing Arabic key
 * is a build error rather than a blank label in production (FR-LOC-006/007).
 */

export const consoleEn = {
  // -- Product and chrome --------------------------------------------------
  "app.name": "TRENDOW",
  "app.subtitle": "Restaurant Operating System",
  "app.console": "Management Console",
  "app.skipToContent": "Skip to content",

  // -- Authentication ------------------------------------------------------
  "auth.signIn": "Sign in",
  "auth.signInTitle": "Sign in to TRENDOW",
  "auth.signInLede": "Management console for restaurant operations. Demo build — no credentials are sent anywhere.",
  "auth.email": "Email address",
  "auth.password": "Password",
  "auth.emailPlaceholder": "you@restaurant.example",
  "auth.forgot": "Forgot your password?",
  "auth.remember": "Keep me signed in on this device",
  "auth.signingIn": "Signing in",
  "auth.signOut": "Sign out",
  "auth.demoRole": "Sign in as",
  "auth.demoRoleHint": "Pick a role. Navigation, actions and data scope all change to match its permissions.",
  "auth.errorRequired": "Enter an email address and a password.",
  "auth.errorInvalid": "That email and password combination was not recognised.",
  "auth.mfaTitle": "Two-factor authentication",
  "auth.mfaLede": "Enter the six-digit code from your authenticator app.",
  "auth.mfaRequired": "This role holds privileged permissions, so MFA is mandatory.",
  "auth.mfaCode": "Verification code",
  "auth.mfaVerify": "Verify",
  "auth.mfaVerifying": "Verifying",
  "auth.mfaResend": "Send a new code",
  "auth.mfaHint": "Any six digits will do in this demo.",
  "auth.mfaError": "Enter all six digits.",
  "auth.mfaBack": "Use a different account",
  "auth.pinNote": "PIN authentication is terminal-bound and never grants dashboard access.",
  "auth.notSignedIn": "You are not signed in.",
  "auth.liveApi": "Signing in against the live backend at",
  "auth.mustReset": "This account must set a new password before its next sign-in.",
  "auth.chooseTenant": "Choose a business",
  "auth.chooseTenantHint": "This account works for more than one. The console reads nothing until one is selected.",
  "auth.errorNetwork": "The backend did not answer. Check the API address and that it is reachable from this device.",

  // -- Navigation ----------------------------------------------------------
  "nav.dashboard": "Dashboard",
  "nav.operations": "Orders & Operations",
  "nav.orders": "Orders",
  "nav.openOrders": "Open orders",
  "nav.tables": "Table status",
  "nav.kitchen": "Kitchen queue",
  "nav.terminals": "Terminals",
  "nav.menu": "Menu & Recipes",
  "nav.categories": "Categories",
  "nav.items": "Items",
  "nav.modifiers": "Modifiers",
  "nav.combos": "Combos",
  "nav.pricing": "Pricing",
  "nav.recipes": "Recipes",
  "nav.inventory": "Inventory",
  "nav.stockLevels": "Stock levels",
  "nav.stockItems": "Stock items",
  "nav.counts": "Counts",
  "nav.transfers": "Transfers",
  "nav.batches": "Batches",
  "nav.expiry": "Expiry",
  "nav.waste": "Waste",
  "nav.adjustments": "Adjustments",
  "nav.movements": "Movements",
  "nav.purchasing": "Purchasing",
  "nav.suppliers": "Suppliers",
  "nav.requisitions": "Requisitions",
  "nav.purchaseOrders": "Purchase orders",
  "nav.receiving": "Receiving",
  "nav.invoices": "Supplier invoices",
  "nav.costing": "Costing & Profitability",
  "nav.foodCost": "Food cost",
  "nav.variance": "Theoretical vs actual",
  "nav.wasteAnalysis": "Waste analysis",
  "nav.margin": "Contribution margin",
  "nav.workforce": "Workforce",
  "nav.employees": "Employees",
  "nav.schedules": "Schedules",
  "nav.attendance": "Attendance",
  "nav.overtime": "Overtime",
  "nav.performance": "Performance",
  "nav.finance": "Finance",
  "nav.cashSessions": "Cash sessions",
  "nav.expenses": "Expenses",
  "nav.dayClose": "Day close",
  "nav.payments": "Payment summary",
  "nav.tax": "Tax summary",
  "nav.organisation": "Organisation",
  "nav.tenants": "Tenants",
  "nav.brands": "Brands",
  "nav.branches": "Branches",
  "nav.warehouses": "Warehouses",
  "nav.centralKitchens": "Central kitchens",
  "nav.reports": "Reports",
  "nav.approvals": "Approvals",
  "nav.audit": "Audit log",
  "nav.users": "Users",
  "nav.roles": "Roles",
  "nav.settings": "Settings",
  "nav.countryPacks": "Country packs",
  "nav.integrations": "Integrations",
  "nav.governance": "Governance",
  "nav.administration": "Administration",
  "nav.openMenu": "Open navigation",
  "nav.closeMenu": "Close navigation",
  "nav.collapse": "Collapse sidebar",
  "nav.expand": "Expand sidebar",

  // -- Scope switcher ------------------------------------------------------
  "scope.tenant": "Tenant",
  "scope.brand": "Brand",
  "scope.branch": "Branch",
  "scope.allBrands": "All brands",
  "scope.allBranches": "All branches",
  "scope.change": "Change scope",
  "scope.locked": "Your role is scoped to this location.",
  "scope.viewing": "Viewing",

  // -- Common actions and labels -------------------------------------------
  "common.search": "Search",
  "common.searchPlaceholder": "Search…",
  "common.filter": "Filter",
  "common.filters": "Filters",
  "common.clearFilters": "Clear filters",
  "common.all": "All",
  "common.export": "Export",
  "common.exportCsv": "Export CSV",
  "common.refresh": "Refresh",
  "common.create": "Create",
  "common.new": "New",
  "common.edit": "Edit",
  "common.save": "Save",
  "common.saving": "Saving",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.delete": "Delete",
  "common.confirm": "Confirm",
  "common.confirmDelete": "Delete this record?",
  "common.confirmDeleteBody": "This is a demo, so nothing leaves the browser — but the row will disappear from this session.",
  "common.view": "View",
  "common.details": "Details",
  "common.back": "Back",
  "common.next": "Next",
  "common.previous": "Previous",
  "common.of": "of",
  "common.showing": "Showing",
  "common.results": "results",
  "common.noResults": "No results",
  "common.uncategorised": "Uncategorised",
  "common.rowsPerPage": "Rows per page",
  "common.total": "Total",
  "common.subtotal": "Subtotal",
  "common.actions": "Actions",
  "common.status": "Status",
  "common.date": "Date",
  "common.time": "Time",
  "common.name": "Name",
  "common.code": "Code",
  "common.value": "Value",
  "common.quantity": "Quantity",
  "common.unit": "Unit",
  "common.reason": "Reason",
  "common.notes": "Notes",
  "common.branch": "Branch",
  "common.brand": "Brand",
  "common.location": "Location",
  "common.category": "Category",
  "common.reference": "Reference",
  "common.target": "Target",
  "common.actual": "Actual",
  "common.variance": "Variance",
  "common.approve": "Approve",
  "common.reject": "Reject",
  "common.approved": "Approved",
  "common.rejected": "Rejected",
  "common.pending": "Pending",
  "common.yes": "Yes",
  "common.no": "No",
  "common.enabled": "Enabled",
  "common.disabled": "Disabled",
  "common.active": "Active",
  "common.inactive": "Inactive",
  "common.today": "Today",
  "common.yesterday": "Yesterday",
  "common.last7": "Last 7 days",
  "common.last30": "Last 30 days",
  "common.thisMonth": "This month",
  "common.period": "Period",
  "common.vsPrevious": "vs previous period",
  "common.updated": "Updated",
  "common.created": "Created",
  "common.by": "by",
  "common.at": "at",
  "common.none": "None",
  "common.unknown": "Unknown",
  "common.required": "Required",
  "common.optional": "Optional",
  "common.copy": "Copy",
  "common.copied": "Copied",
  "common.moreFilters": "More filters",
  "common.sortBy": "Sort by",
  "common.grouping": "Group by",
  "common.percentOfSales": "% of net sales",
  "common.perUnit": "per unit",
  "common.spec": "Traced to",

  // -- State panels --------------------------------------------------------
  "state.loading": "Loading",
  "state.loadingData": "Loading data…",
  "state.emptyTitle": "Nothing here yet",
  "state.emptyBody": "No records match the current scope and filters.",
  "state.emptyAction": "Clear filters",
  "state.errorTitle": "Could not load this data",
  "state.errorRetry": "Try again",
  "state.deniedTitle": "You do not have access to this",
  "state.deniedBody": "This screen requires a permission your current role does not hold. Switch role from the account menu to explore it.",
  "state.deniedPermission": "Required permission",
  "state.notFoundTitle": "Not found",
  "state.notFoundBody": "That record does not exist, or is not visible in your current scope.",
  "state.serverNote": "Client-side permission checks are presentation only. The server enforces the real rule on every request.",

  // -- Theme, language, account -------------------------------------------
  "pref.theme": "Theme",
  "pref.light": "Light",
  "pref.dark": "Dark",
  "pref.system": "System",
  "pref.language": "Language",
  "pref.numerals": "Numerals",
  "pref.numeralsWestern": "Western (0–9)",
  "pref.numeralsArabic": "Arabic-Indic (٠–٩)",
  "pref.toggleTheme": "Toggle theme",
  "pref.account": "Account",
  "pref.switchRole": "Switch demo role",
  "pref.profile": "Profile",
  "pref.role": "Role",
  "pref.permissions": "permissions",

  // -- Dashboard -----------------------------------------------------------
  "dash.title": "Dashboard",
  "dash.subtitle": "Exception over enumeration. Every figure opens to the transactions behind it.",
  "dash.activityTitle": "Order activity",
  "dash.activityHint": "Filtered live off real orders — change any filter and every figure below recomputes from the same records.",
  "dash.grossSales": "Gross sales",
  "dash.totalOrders": "Total orders",
  "dash.openShifts": "Open shifts",
  "dash.closedShifts": "Closed shifts",
  "dash.cashDrawerDiff": "Cash drawer difference",
  "dash.offlineOrders": "Offline orders",
  "dash.pendingSyncOrders": "Pending sync orders",
  "dash.syncedOfflineOrders": "Synced offline orders",
  "dash.byCashier": "Sales by cashier",
  "dash.byBranch": "Sales by branch",
  "dash.byCategory": "Sales by category",
  "dash.bestSelling": "Best-selling items",
  "dash.lowestSelling": "Lowest-selling items",
  "dash.ordersByHour": "Orders by hour",
  "dash.netSales": "Net sales",
  "dash.transactions": "Transactions",
  "dash.aov": "Average order value",
  "dash.foodCost": "Food cost",
  "dash.labourCost": "Labour cost",
  "dash.primeCost": "Prime cost",
  "dash.waste": "Waste",
  "dash.grossProfit": "Gross profit",
  "dash.salesTrend": "Net sales, last 14 days",
  "dash.salesTrendHint": "Comparison line is the same weekday in the prior period.",
  "dash.hourly": "Hourly sales with labour overlay",
  "dash.hourlyHint": "Sales and labour on one axis, so over- and under-staffing by hour is visible.",
  "dash.categoryMix": "Category mix",
  "dash.branchRanking": "Branch ranking",
  "dash.branchRankingHint": "Ranked by net sales. Outliers are branches beyond 1.5σ from the group mean on prime cost.",
  "dash.alerts": "Alerts",
  "dash.alertsHint": "Rate-limited and de-duplicated per recipient, per type, per period.",
  "dash.wasteByReason": "Waste by reason",
  "dash.profitability": "Profitability",
  "dash.live": "Live operations",
  "dash.dataAsOf": "Data as of",
  "dash.partialDay": "Today is partial — the business day has not closed.",
  "dash.noAlerts": "No open alerts in this scope.",
  "dash.viewAll": "View all",
  "dash.acknowledge": "Acknowledge",
  "dash.rank": "Rank",
  "dash.outlier": "Outlier",
  "dash.prime": "Prime",

  // Profitability ladder
  "pl.grossSales": "Gross sales",
  "pl.discounts": "Discounts",
  "pl.refunds": "Refunds",
  "pl.netSales": "Net sales (excl. tax)",
  "pl.cogs": "Cost of goods sold",
  "pl.grossProfit": "Gross profit",
  "pl.labour": "Labour cost",
  "pl.contribution": "Contribution after labour",
  "pl.opex": "Operating expenses",
  "pl.operatingProfit": "Branch operating profit",

  // Live operations
  "live.openOrders": "Open orders",
  "live.tables": "Tables occupied",
  "live.queue": "Kitchen queue",
  "live.avgWait": "Average wait",
  "live.terminals": "Active terminals",
  "live.staff": "Staff on shift",
  "live.delayed": "Delayed tickets",
  "live.syncBacklog": "Sync backlog",
  "live.operations": "operations",

  // -- Orders --------------------------------------------------------------
  "orders.title": "Orders",
  "orders.subtitle": "Every completed order is immutable. Corrections are refunds that reference it.",
  "orders.number": "Order",
  "orders.type": "Type",
  "orders.channel": "Channel",
  "orders.table": "Table",
  "orders.guests": "Guests",
  "orders.server": "Server",
  "orders.opened": "Opened",
  "orders.completed": "Completed",
  "orders.sync": "Sync",
  "orders.syncedAt": "Synced at",
  "orders.terminal": "Terminal",
  "orders.customer": "Customer",
  "orders.lines": "Lines",
  "orders.payments": "Payments",
  "orders.tender": "Tender",
  "orders.cogs": "COGS",
  "orders.margin": "Margin",
  "orders.paid": "Paid",
  "orders.tip": "Tip",
  "orders.serviceCharge": "Service charge",
  "orders.rounding": "Cash rounding",
  "orders.tax": "Tax",
  "orders.syncState": "Sync",
  "orders.aggregatorRef": "Aggregator reference",
  "orders.detailTitle": "Order detail",
  "orders.timeline": "Timeline",
  "orders.snapshotNote": "Item name, price, tax class and cost are snapshotted at sale time and never recomputed.",
  "orders.course": "Course",
  "orders.seat": "Seat",
  "orders.voidReason": "Void reason",
  "orders.comp": "Comp",
  "orders.cancelled": "Cancelled",
  "orders.cancelledAt": "Cancelled at",
  "orders.cancelledBy": "Cancelled by",
  "orders.cancelReason": "Cancellation reason",
  "orders.originalTotal": "Original total",
  "orders.paymentStatus": "Payment status",
  "orders.neverCharged": "Never charged",
  "orders.refunded": "Refunded",
  "orders.partiallyRefunded": "Partially refunded",
  "orders.refundPending": "Refund pending",
  "orders.refundAmount": "Refund amount",
  "orders.discountsApplied": "Discounts applied",
  "orders.appliedBy": "Applied by",
  "orders.approvedBy": "Approved by",
  "orders.openOrdersTitle": "Open orders",
  "orders.openOrdersSubtitle": "Orders still on the floor: drafts, held, parked and partially paid.",

  // Tables
  "tables.title": "Table status",
  "tables.subtitle": "Live floor state per branch, with time since seated.",
  "tables.area": "Area",
  "tables.capacity": "Capacity",
  "tables.seatedFor": "Seated for",
  "tables.occupancy": "Occupancy",
  "tables.free": "Free",
  "tables.selectBranch": "Choose a single branch to see its floor plan.",

  // Kitchen
  "kitchen.title": "Kitchen queue",
  "kitchen.subtitle": "What the stations are looking at right now, coloured by elapsed time against target.",
  "kitchen.station": "Station",
  "kitchen.elapsed": "Elapsed",
  "kitchen.targetTime": "Target",
  "kitchen.priority": "Priority",
  "kitchen.queueDepth": "Queue depth",
  "kitchen.throughput": "Capacity / hour",
  "kitchen.bottleneck": "Bottleneck",
  "kitchen.byStation": "By station",
  "kitchen.allTickets": "All tickets",
  "kitchen.noTickets": "No live tickets in this scope.",

  // Terminals
  "terminals.title": "Terminals",
  "terminals.subtitle": "Registration, version, last contact and outbox depth per device.",
  "terminals.lastSeen": "Last seen",
  "terminals.version": "App version",
  "terminals.queued": "Queued operations",
  "terminals.battery": "Battery",
  "terminals.ip": "IP address",
  "terminals.kind": "Kind",
  "terminals.revoke": "Revoke registration",
  "terminals.offlineNote": "An offline terminal keeps selling. The queue is the work waiting to sync, not lost sales.",
  "terminals.online": "Online",
  "terminals.notOnline": "Offline or degraded",
  "terminals.queuedHint": "Operations written locally and waiting to send. A short queue is normal; a long one means the console's figures are behind the floor.",
  "terminals.versionSpread": "App versions in use",
  "terminals.versionHint": "Several versions trading at once is expected during a rollout and a problem if it persists — conflict resolution assumes both peers understand the same schema.",
  "terminals.registrationNote": "Registration is per device, so revoking a lost tablet does not require changing anybody's password.",

  // -- Menu ----------------------------------------------------------------
  "menu.categoriesTitle": "Categories",
  "menu.categoriesSubtitle": "Menu hierarchy: menu → category → item → variant.",
  "menu.itemsTitle": "Menu items",
  "menu.itemsSubtitle": "Names are configurable per surface, because the right name differs by context.",
  "menu.modifiersTitle": "Modifier groups",
  "menu.modifiersSubtitle": "Modifiers carry a price delta and a recipe delta. A 'no cheese' burger does not deplete cheese.",
  "menu.combosTitle": "Combos",
  "menu.combosSubtitle": "Slot-based meals with configurable pricing strategy.",
  "menu.pricingTitle": "Price lists",
  "menu.pricingSubtitle": "Scope, validity window, recurrence and priority. Highest priority wins.",
  "menu.itemName": "Item",
  "menu.kitchenName": "Kitchen name",
  "menu.receiptName": "Receipt name",
  "menu.variants": "Variants",
  "menu.price": "Price",
  "menu.taxClass": "Tax class",
  "menu.station": "Station",
  "menu.prepTime": "Prep time",
  "menu.availability": "Availability",
  "menu.available": "Available",
  "menu.unavailable": "Unavailable (86)",
  "menu.remainingSellable": "Remaining sellable",
  "menu.remainingHint": "The minimum across ingredients of available stock divided by the quantity per portion.",
  "menu.allergens": "Allergens",
  "menu.toggle86": "Mark unavailable",
  "menu.toggleAvailable": "Mark available",
  "menu.86Reason": "Reason for making this unavailable",
  "menu.sortOrder": "Sort order",
  "menu.itemCount": "Items",
  "menu.minMax": "Min / max",
  "menu.required": "Required",
  "menu.attachedItems": "Attached items",
  "menu.priceDelta": "Price delta",
  "menu.recipeDelta": "Recipe delta",
  "menu.modifierKind": "Kind",
  "menu.slots": "Slots",
  "menu.strategy": "Pricing strategy",
  "menu.scope": "Scope",
  "menu.priority": "Priority",
  "menu.validity": "Validity",
  "menu.recurrence": "Recurrence",
  "menu.orderTypes": "Order types",
  "menu.entries": "Entries",
  "menu.searchPlaceholder": "Search by item, kitchen name or description",
  "menu.categoriesEmpty": "have no items attached",
  "menu.openPrice": "Open price",
  "menu.weighed": "Sold by weight",
  "menu.lowRemaining": "Nearly out",
  "menu.restored": "Item is available again",
  "menu.eightySixed": "Item marked unavailable",
  "menu.86Placeholder": "Ran out of chicken thigh; expected back tomorrow",
  "menu.modifierCount": "Modifiers",
  "menu.requiredGroups": "required",
  "menu.withRecipeDelta": "Groups that move stock",
  "menu.recipeDeltaHint": "A modifier with a recipe delta changes what the sale depletes — 'no cheese' returns the cheese to stock, 'extra cheese' takes more.",
  "menu.allowRepeat": "Repeat allowed",
  "menu.freeThreshold": "Free up to",
  "menu.default": "Default",
  "menu.deltaAdd": "Adds to the recipe",
  "menu.deltaRemoveAll": "Removes the component entirely",
  "menu.deltaScale": "Scales the component",
  "menu.noSurcharge": "No surcharge",
  "menu.priorityHint": "When several lists cover the same item at the same moment, the highest priority wins.",
  "menu.precedenceNote": "Price resolution follows FR-POS-040: among the lists in force for the item, order type and scope, the terminal takes the one with the highest priority.",
  "menu.previousPrice": "Previous",
  "menu.noEntries": "This list carries no item entries.",

  // -- Recipes -------------------------------------------------------------
  "recipes.title": "Recipes",
  "recipes.subtitle": "Where the sellable world meets the physical one. Versioned; completed orders keep their version.",
  "recipes.type": "Type",
  "recipes.version": "Version",
  "recipes.yield": "Yield",
  "recipes.yieldPercent": "Yield %",
  "recipes.cost": "Cost",
  "recipes.costPerPortion": "Cost per portion",
  "recipes.sellingPrice": "Selling price",
  "recipes.marginPercent": "Margin %",
  "recipes.components": "Components",
  "recipes.component": "Component",
  "recipes.wastage": "Trim loss",
  "recipes.lineCost": "Line cost",
  "recipes.instructions": "Instructions",
  "recipes.incomplete": "Recipe incomplete",
  "recipes.incompleteBody": "This item can still be sold. Cost is recorded as zero and the item appears in the recipes-requiring-completion report.",
  "recipes.publish": "Publish version",
  "recipes.costBreakdown": "Cost breakdown",
  "recipes.subRecipe": "Sub-recipe",
  "recipes.stockItem": "Stock item",
  "recipes.completeness": "Recipe completeness",
  "recipes.itemsWithout": "menu items have no published recipe",
  "recipes.formulaNote": "Cost = Σ (quantity × (1 + trim loss) × unit cost) ÷ yield percentage.",
  "recipes.complete": "Complete",
  "recipes.noComponents": "This recipe has no components yet, so it books zero cost.",

  // -- Inventory -----------------------------------------------------------
  "inv.levelsTitle": "Stock levels",
  "inv.levelsSubtitle": "A projection over the movement ledger, reconciled daily.",
  "inv.itemsTitle": "Stock items",
  "inv.itemsSubtitle": "The item master. Base unit is immutable once any movement exists.",
  "inv.countsTitle": "Stock counts",
  "inv.countsSubtitle": "Blind by default. Expected quantity is frozen when the session opens.",
  "inv.transfersTitle": "Transfers",
  "inv.transfersSubtitle": "Dispatch and receipt are separate steps; stock in transit is visible between them.",
  "inv.batchesTitle": "Batches",
  "inv.batchesSubtitle": "Batch number, production and expiry dates, and the value at risk.",
  "inv.expiryTitle": "Expiry watch",
  "inv.expirySubtitle": "Items approaching expiry, nearest first, with the value at risk.",
  "inv.wasteTitle": "Waste",
  "inv.wasteSubtitle": "True waste is reported separately from controlled consumption.",
  "inv.wasteReportTitle": "Waste report",
  "inv.wasteReportHint": "Every branch, not only this terminal's session.",
  "inv.totalWasteCost": "Total waste cost",
  "inv.wasteByItem": "Waste by item",
  "inv.wasteByCategory": "Waste by category",
  "inv.wasteByBranch": "Waste by branch",
  "inv.wasteByReason": "Waste by reason",
  "inv.adjustmentsTitle": "Adjustments",
  "inv.adjustmentsSubtitle": "Manual corrections. Every one needs a reason; large ones need approval.",
  "inv.movementsTitle": "Stock movements",
  "inv.movementsSubtitle": "The immutable ledger. Every quantity in the system derives from this.",
  "inv.sku": "SKU",
  "inv.onHand": "On hand",
  "inv.allocated": "Allocated",
  "inv.onOrder": "On order",
  "inv.reorderPoint": "Reorder point",
  "inv.par": "Par level",
  "inv.unitCost": "Unit cost",
  "inv.stockValue": "Stock value",
  "inv.daysOfCover": "Days of cover",
  "inv.lastCounted": "Last counted",
  "inv.baseUnit": "Base unit",
  "inv.purchaseUnit": "Purchase unit",
  "inv.costingMethod": "Costing method",
  "inv.storage": "Storage",
  "inv.shelfLife": "Shelf life",
  "inv.batchTracked": "Batch tracked",
  "inv.expiryTracked": "Expiry tracked",
  "inv.batchNumber": "Batch",
  "inv.productionDate": "Produced",
  "inv.expiryDate": "Expires",
  "inv.daysToExpiry": "Days to expiry",
  "inv.valueAtRisk": "Value at risk",
  "inv.mode": "Mode",
  "inv.blind": "Blind",
  "inv.open": "Open",
  "inv.scope": "Scope",
  "inv.countedBy": "Counted by",
  "inv.expected": "Expected",
  "inv.counted": "Counted",
  "inv.flagged": "Flagged",
  "inv.netVariance": "Net variance",
  "inv.blindNote": "Expected quantities are hidden while a blind count is in progress.",
  "inv.postCount": "Post count",
  "inv.from": "From",
  "inv.to": "To",
  "inv.dispatched": "Dispatched",
  "inv.received": "Received",
  "inv.discrepancy": "Discrepancy",
  "inv.inTransit": "In transit",
  "inv.movementType": "Movement",
  "inv.balanceAfter": "Balance after",
  "inv.performedBy": "Performed by",
  "inv.trueWaste": "True waste",
  "inv.controlledConsumption": "Controlled consumption",
  "inv.recordWaste": "Record waste",
  "inv.negativeNote": "Negative stock is recorded, not blocked. It signals a receipt that was never entered.",
  "inv.markWasted": "Mark wasted",
  "inv.transferOut": "Transfer out",
  "inv.searchPlaceholder": "Search by name, SKU or category",
  "inv.batchSearchPlaceholder": "Search by item, batch number or location",
  "inv.days": "days",
  "inv.defaultSupplier": "Default supplier",
  "inv.baseUnitNote": "The base unit is fixed once any movement exists — every quantity in the ledger is denominated in it, so changing it would rescale history.",
  "inv.countsOpen": "Counts in progress",
  "inv.countsAwaiting": "Awaiting posting",
  "inv.countLines": "Counted lines",
  "inv.netVarianceHint": "Offsetting errors net to zero and still mean two items are wrong — read the flagged count alongside this.",
  "inv.recount": "Recount",
  "inv.submitted": "Submitted",
  "inv.posted": "Posted",
  "inv.inTransitValue": "Value in transit",
  "inv.inTransitHint": "Stock that has left the sending location and has not been receipted at the destination.",
  "inv.receiveTransfer": "Receive transfer",
  "inv.discrepancyNote": "Dispatched and received quantities disagree. The transfer stays open until the difference is explained or written off — closing it silently would push the loss into two branches' variance reports where nobody owns it.",
  "inv.atRiskHint": "Value held in batches that expire within the next three days.",
  "inv.expiredNote": "This batch is past its expiry date and is still carried at full value. It needs a write-off.",
  "inv.fefoNote": "Consumption follows FEFO — first expired, first out — so the batch nearest its expiry date is depleted first.",
  "inv.expiryUrgent": "Stock needs attention today",
  "inv.expiryUrgentBody": "Batches below have expired or expire today. They are still carried at full value until written off.",
  "inv.expiringToday": "Expires today",
  "inv.expiringSoon": "Within 3 days",
  "inv.expiringLater": "Later",
  "inv.batchesLower": "batches",
  "inv.writeOff": "Write off",
  "inv.expiryClear": "Nothing near expiry",
  "inv.expiryClearBody": "No batch in scope is within the expiry horizon.",
  "inv.writeUp": "Written up",
  "inv.writeUpHint": "Adjustments that increased the balance — usually a goods receipt that was never entered.",
  "inv.writeDown": "Written down",
  "inv.adjustmentNote": "An adjustment writes to the ledger with no business event behind it. The reason code is what tells the costing module whether a variance is explained.",

  // -- Purchasing ----------------------------------------------------------
  "pur.suppliersTitle": "Suppliers",
  "pur.suppliersSubtitle": "Master data, terms, and the scorecard that makes price creep visible.",
  "pur.requisitionsTitle": "Requisitions",
  "pur.requisitionsSubtitle": "Branches request; head office buys. Consolidation retains branch attribution.",
  "pur.ordersTitle": "Purchase orders",
  "pur.ordersSubtitle": "Value bands decide who approves. The requester is never an approver.",
  "pur.receivingTitle": "Goods receipts",
  "pur.receivingSubtitle": "Receipt creates the stock movement, the batch, and the price-variance check.",
  "pur.invoicesTitle": "Supplier invoices",
  "pur.invoicesSubtitle": "Three-way match across purchase order, goods receipt and invoice.",
  "pur.supplier": "Supplier",
  "pur.contact": "Contact",
  "pur.terms": "Payment terms",
  "pur.leadTime": "Lead time",
  "pur.minOrder": "Minimum order",
  "pur.deliveryDays": "Delivery days",
  "pur.outstanding": "Outstanding",
  "pur.scorecard": "Scorecard",
  "pur.onTime": "On-time delivery",
  "pur.fillRate": "Fill rate",
  "pur.priceStability": "Price stability",
  "pur.qualityRejection": "Quality rejection",
  "pur.invoiceAccuracy": "Invoice accuracy",
  "pur.avgLeadTime": "Average lead time",
  "pur.requestedBy": "Requested by",
  "pur.neededBy": "Needed by",
  "pur.estimatedTotal": "Estimated total",
  "pur.expectedDelivery": "Expected delivery",
  "pur.approvalTier": "Approval tier",
  "pur.approver": "Approver",
  "pur.autoApproved": "Auto-approved",
  "pur.ordered": "Ordered",
  "pur.rejectedQty": "Rejected",
  "pur.rejectionReason": "Rejection reason",
  "pur.temperature": "Temperature",
  "pur.temperatureOk": "In range",
  "pur.temperatureBad": "Out of range",
  "pur.priceVariance": "Price variance",
  "pur.match": "Match",
  "pur.matchNote": "Match result",
  "pur.invoiceNumber": "Invoice number",
  "pur.invoiceDate": "Invoice date",
  "pur.dueDate": "Due",
  "pur.ageing": "Ageing",
  "pur.approveOrder": "Approve order",
  "pur.directReceipt": "Direct receipt — no purchase order",
  "pur.noPo": "No PO",
  "pur.threeWayNote": "Quantity tolerance 0%, unit price tolerance 2%, totals to within one minor unit.",
  "pur.supplierSearchPlaceholder": "Search by name, code, contact or email",
  "pur.netDays": "Net ",
  "pur.taxRegistration": "Tax registration",
  "pur.lowerIsBetter": "(lower is better)",
  "pur.underperforming": "Below delivery target",
  "pur.underperformingHint": "Suppliers whose on-time delivery rate is under 90%.",
  "pur.awaitingApproval": "Awaiting approval",
  "pur.readyToConsolidate": "Ready to consolidate",
  "pur.consolidatedNote": "This requisition was merged into a consolidated purchase order. Branch attribution is retained, so the cost still lands on the branch that requested the goods.",
  "pur.approved": "Purchase order approved",
  "pur.pendingValue": "Value awaiting approval",
  "pur.openOrders": "Open orders",
  "pur.tierNote": "This order's value places it in a band that must be approved by:",
  "pur.receivedValue": "Received value",
  "pur.priceDrift": "Receipts with price drift",
  "pur.priceDriftHint": "Receipts where a delivered unit price differed from the agreed price by more than 2%.",
  "pur.temperatureNote": "A chilled or frozen delivery was accepted outside its temperature range. Record the decision — a later spoilage claim depends on this reading.",
  "pur.matchFailures": "Match failures",
  "pur.matchFailuresHint": "Invoices that could not be reconciled against their purchase order and goods receipt.",
  "pur.matchFailedNote": "The invoice does not agree with the purchase order and goods receipt. It cannot be approved for payment until the difference is resolved.",

  // -- Costing -------------------------------------------------------------
  "cost.foodCostTitle": "Food cost",
  "cost.foodCostSubtitle": "COGS ÷ net sales. Reportable by branch, brand, category and period.",
  "cost.varianceTitle": "Theoretical vs actual usage",
  "cost.varianceSubtitle": "The single most diagnostic number in restaurant operations. Sorted by value, not quantity.",
  "cost.wasteTitle": "Waste analysis",
  "cost.wasteSubtitle": "By reason, item, location and employee, with true waste separated from staff meals.",
  "cost.marginTitle": "Contribution margin",
  "cost.marginSubtitle": "Menu engineering on popularity against profitability.",
  "cost.byBranch": "By branch",
  "cost.byBrand": "By brand",
  "cost.byCategory": "By category",
  "cost.byReason": "By reason",
  "cost.byItem": "By item",
  "cost.byLocation": "By location",
  "cost.byEmployee": "By employee",
  "cost.byChannel": "By channel",
  "cost.foodCostPercent": "Food cost %",
  "cost.targetPercent": "Target %",
  "cost.variancePoints": "Variance",
  "cost.theoretical": "Theoretical",
  "cost.actualUsage": "Actual",
  "cost.recordedWaste": "Recorded waste",
  "cost.unexplained": "Unexplained",
  "cost.varianceValue": "Variance value",
  "cost.hypothesis": "Likely cause",
  "cost.hypothesisNote": "Presented as a hypothesis for investigation, never as a conclusion.",
  "cost.percentOfCogs": "% of COGS",
  "cost.records": "Records",
  "cost.revenueToOffset": "Revenue required to offset",
  "cost.revenueToOffsetHint": "Waste value divided by the average contribution margin — the extra sales needed to recover it.",
  "cost.unitsSold": "Units sold",
  "cost.sellingPrice": "Selling price (ex-tax)",
  "cost.directCost": "Direct cost",
  "cost.contributionMargin": "Contribution margin",
  "cost.totalContribution": "Total contribution",
  "cost.classification": "Classification",
  "cost.commission": "Commission",
  "cost.packaging": "Packaging",
  "cost.netContribution": "Net contribution",
  "cost.channelNote": "A dish with a healthy dine-in margin can be loss-making on an aggregator once commission and packaging are applied.",
  "cost.revenue": "Revenue",
  "cost.marginPercent": "Margin %",
  "cost.matrixTitle": "Menu engineering matrix",
  "cost.popularity": "Popularity",
  "cost.profitability": "Profitability",
  "cost.blendedHint": "Weighted by net sales, not an average of the percentages — otherwise a small branch counts as much as a flagship.",
  "cost.overTarget": "Above target",
  "cost.varianceLoss": "Variance loss",
  "cost.unexplainedHint": "Items where the gap between theoretical and actual usage is not covered by a recorded waste entry.",
  "cost.worstItem": "Largest deviation",
  "cost.hypothesisBadge": "For investigation",
  "cost.controlledHint": "Staff meals, tastings and training portions. These cost money but they are a decision, not a loss.",
  "cost.wasteSeparationNote": "True waste is reported apart from controlled consumption. Combining them inflates the figure until nobody trusts it, and the genuine spoilage hides inside a number everyone has learned to discount.",
  "cost.rankingNote": "Ranked by total contribution rather than margin percentage. A 78% margin on a dish nobody orders contributes less than a 52% margin on the one that carries lunch service.",

  // -- Workforce -----------------------------------------------------------
  "wf.employeesTitle": "Employees",
  "wf.employeesSubtitle": "An employee is a person in a job. A user is a credential. They are separate.",
  "wf.schedulesTitle": "Schedules",
  "wf.schedulesSubtitle": "Shifts validated against rest, consecutive-day and certification rules.",
  "wf.attendanceTitle": "Attendance",
  "wf.attendanceSubtitle": "Clock events with method, flags, and the hours that feed payroll export.",
  "wf.overtimeTitle": "Overtime",
  "wf.overtimeSubtitle": "Unapproved overtime is reported separately, never silently included.",
  "wf.performanceTitle": "Performance",
  "wf.performanceSubtitle": "Per-employee metrics, ranked within branch and position.",
  "wf.employee": "Employee",
  "wf.position": "Position",
  "wf.department": "Department",
  "wf.homeBranch": "Home branch",
  "wf.employmentType": "Employment type",
  "wf.hiredOn": "Hired",
  "wf.hourlyRate": "Hourly rate",
  "wf.documents": "Documents",
  "wf.documentExpiry": "Expires",
  "wf.hasLogin": "Has login",
  "wf.noLogin": "No login credential",
  "wf.shift": "Shift",
  "wf.hours": "Hours",
  "wf.projectedCost": "Projected cost",
  "wf.violations": "Rule violations",
  "wf.clockIn": "Clock in",
  "wf.clockOut": "Clock out",
  "wf.method": "Method",
  "wf.regularHours": "Regular",
  "wf.overtimeHours": "Overtime",
  "wf.breaks": "Break",
  "wf.flags": "Flags",
  "wf.corrected": "Corrected",
  "wf.labourCost": "Labour cost",
  "wf.weekStarting": "Week starting",
  "wf.multiplier": "Multiplier",
  "wf.orderCount": "Orders",
  "wf.itemsPerOrder": "Items / order",
  "wf.upsellRate": "Upsell rate",
  "wf.serviceTime": "Service time",
  "wf.voidCount": "Voids",
  "wf.voidValue": "Void value",
  "wf.discountValue": "Discount value",
  "wf.cashVariance": "Cash variance",
  "wf.salesPerHour": "Sales / labour hour",
  "wf.compensationHidden": "Compensation is hidden. It requires an explicit permission.",
  "wf.expiringDocs": "Expiring documents",
  "wf.exportPayroll": "Export payroll inputs",
  "wf.payrollNote": "TRENDOW exports inputs to payroll. It does not compute net pay, withholding or contributions.",
  "wf.searchPlaceholder": "Search by name, code, position or contact",
  "wf.expiringDocsHint": "Employees holding a certificate or permit that has expired or expires soon — a lapsed food-handler certificate is someone who cannot be rostered.",
  "wf.docsValid": "Valid",
  "wf.docsExpiring": "Expiring",
  "wf.docsExpired": "Expired",
  "wf.permittedBranches": "Permitted branches",
  "wf.scheduledHours": "Scheduled hours",
  "wf.violationsNote": "Some shifts break a rest, consecutive-day or certification rule. Publishing is still allowed — real rosters need exceptions — but the exception is recorded on the row.",
  "wf.draftHint": "Draft shifts are not visible to staff until the roster is published.",
  "wf.flagsHint": "Records carrying a late arrival, a missing clock-out, a geofence miss or a manual correction.",
  "wf.unapprovedHours": "Unapproved hours",
  "wf.unapprovedHint": "Overtime worked without prior approval. The hours and the cost are real either way; keeping them separate is what makes a roster that keeps failing visible.",
  "wf.unapprovedCost": "Unapproved cost",
  "wf.multiplierNote": "The overtime multiplier and the standard weekly hours come from the country pack, not from this module — a tenant operating in three countries has three of them.",
  "wf.sphHint": "Net sales divided by hours worked — the only metric here that compares a Tuesday lunch server with a Friday night one.",
  "wf.voidRate": "Void rate",
  "wf.controlMetrics": "Control metrics",
  "wf.performanceNote": "These figures are a prompt for a conversation, not a verdict. A high void count has honest explanations as often as dishonest ones, and the number alone does not distinguish them.",

  // -- Finance -------------------------------------------------------------
  "fin.cashTitle": "Cash sessions",
  "fin.cashSubtitle": "Every unit of currency attributable to a person, a shift and a drawer.",
  "fin.expensesTitle": "Expenses",
  "fin.expensesSubtitle": "Branch operating expenses with category, method and approval state.",
  "fin.dayCloseTitle": "Day close",
  "fin.dayCloseSubtitle": "Blocked while any cash session remains open. Produces the sequential Z report.",
  "fin.paymentsTitle": "Payment summary",
  "fin.paymentsSubtitle": "Totals by tender, the reconciliation basis for every settlement.",
  "fin.taxTitle": "Tax summary",
  "fin.taxSubtitle": "Computed per line by the country pack's tax engine, then summed.",
  "fin.drawer": "Drawer",
  "fin.cashier": "Cashier",
  "fin.openingFloat": "Opening float",
  "fin.cashSales": "Cash sales",
  "fin.cashRefunds": "Cash refunds",
  "fin.payIns": "Pay-ins",
  "fin.payOuts": "Pay-outs",
  "fin.safeDrops": "Safe drops",
  "fin.expectedCash": "Expected cash",
  "fin.countedCash": "Counted cash",
  "fin.varianceApproval": "Variance approval",
  "fin.denominations": "Denomination count",
  "fin.expectedFormula": "Float + cash sales + pay-ins − refunds − pay-outs − safe drops",
  "fin.expenseCategory": "Category",
  "fin.paymentMethod": "Payment method",
  "fin.incurredOn": "Incurred",
  "fin.recurring": "Recurring",
  "fin.attachment": "Attachment",
  "fin.businessDay": "Business day",
  "fin.zReport": "Z report",
  "fin.zNumber": "Z number",
  "fin.closeDay": "Close business day",
  "fin.closing": "Closing",
  "fin.blockedBy": "Blocked by open sessions",
  "fin.grossSales": "Gross sales",
  "fin.netSales": "Net sales",
  "fin.transactionCount": "Transactions",
  "fin.voids": "Voids",
  "fin.comps": "Comps",
  "fin.tenderType": "Tender",
  "fin.count": "Count",
  "fin.amount": "Amount",
  "fin.taxRate": "Rate",
  "fin.netAmount": "Net",
  "fin.taxAmount": "Tax",
  "fin.grossAmount": "Gross",
  "fin.rounding": "Rounding adjustment",
  "fin.roundingNote": "Cash rounding applies only to the cash portion and is recorded separately, never absorbed into revenue or tax.",
  "fin.missingReceipt": "Petty cash without a receipt",
  "fin.missingReceiptHint": "Petty cash is the one payment method with no counterparty record elsewhere — a transfer reconciles against a statement, a card against a settlement file, and petty cash against nothing but the receipt.",
  "fin.daysOpen": "Days still open",
  "fin.openSessions": "open sessions",
  "fin.blockedHint": "The day cannot close while a cash session is still taking money. The Z report is immutable once issued, so it must not be issued early.",
  "fin.dayClosed": "Business day closed",
  "fin.zSequenceNote": "Z numbers are sequential per branch and never reused. A gap in the sequence is the first thing an auditor looks for, which is why the number is issued by the close rather than chosen.",
  "fin.taxInclusive": "Tax-inclusive",
  "fin.taxExclusive": "Tax-exclusive",
  "fin.perLine": "Per line",
  "fin.perOrder": "Per order",

  // -- Organisation --------------------------------------------------------
  "org.tenantsTitle": "Tenants",
  "org.tenantsSubtitle": "Cross-tenant administration. Platform staff only.",
  "org.brandsTitle": "Brands",
  "org.brandsSubtitle": "A restaurant concept owned by a tenant, with its own menu and identity.",
  "org.branchesTitle": "Branches",
  "org.branchesSubtitle": "Each branch holds its own stock, drawers, roster, hours, currency and tax setup.",
  "org.warehousesTitle": "Warehouses",
  "org.warehousesSubtitle": "Stock-holding locations that do not sell to end customers.",
  "org.kitchensTitle": "Central kitchens",
  "org.kitchensSubtitle": "Production facilities that consume input stock and produce output stock.",
  "org.plan": "Plan",
  "org.state": "State",
  "org.region": "Data region",
  "org.country": "Country",
  "org.currency": "Currency",
  "org.timezone": "Timezone",
  "org.dayBoundary": "Business-day boundary",
  "org.seats": "Seats",
  "org.area": "Floor area",
  "org.openedOn": "Opened",
  "org.franchise": "Franchise",
  "org.address": "Address",
  "org.branchCount": "Branches",
  "org.attachedTo": "Attached to",
  "org.serves": "Serves",
  "org.standalone": "Standalone",
  "org.tenantIsolationNote": "Every query in the system is filtered by tenant before any other condition. Cross-tenant reads are not a permission a role can hold — they are impossible by construction.",
  "org.atRisk": "At risk",
  "org.atRiskHint": "Past due, restricted or suspended. A past-due tenant still trades; a restricted one keeps selling and loses the console; a suspended one stops.",
  "org.residencyNote": "The data region is fixed when the tenant is created. Moving it is a migration, not a setting.",
  "org.brandScopeNote": "Menus, price lists and modifier groups attach to the brand, not the branch — a ghost kitchen running six brands from one address would otherwise maintain six copies of everything by hand.",
  "org.branchSearchPlaceholder": "Search by name, code or address",
  "org.dayBoundaryHint": "A branch closing at 02:00 needs its trading day to end at 04:00, not midnight — otherwise every late night splits across two reports and neither describes a shift anybody worked.",
  "org.franchiseHint": "A franchisee sees its own branch and nothing else, whatever the organisation chart says.",
  "org.driveThrough": "Drive through",
  "org.driveThroughEnabled": "Drive through enabled",
  "org.driveThroughHint": "When off, drive through does not appear as an order type on this branch's POS.",
  "org.driveThroughUpdated": "Drive through setting saved",
  "org.standaloneHint": "A depot that is not behind a restaurant. Attached warehouses inherit their branch's permission scope; standalone ones do not.",
  "org.warehouseNote": "A warehouse holds stock and does not sell — it takes part in transfers, counts and valuation, and takes no part in sales, drawers or kitchen routing.",
  "org.branchesServed": "Branches served",
  "org.productionCostNote": "Output from a production run is a stock item with its own cost — ingredients plus production labour and yield loss. If that cost does not travel with the goods, every receiving branch understates its food cost.",

  // -- Reports, approvals, audit ------------------------------------------
  "rep.title": "Reports",
  "rep.subtitle": "Reports arrive; they are not fetched. Every aggregate opens to its transactions.",
  "rep.run": "Run",
  "rep.running": "Running",
  "rep.schedule": "Schedule",
  "rep.async": "Runs asynchronously",
  "rep.category": "Category",
  "rep.cashierTitle": "Cashier report",
  "rep.cashierSubtitle": "Every shift, every cashier, every branch — the same figures the shift itself closed with.",
  "filter.today": "Today",
  "filter.yesterday": "Yesterday",
  "filter.last7": "Last 7 days",
  "filter.customRange": "Custom range",
  "rep.exportNote": "Every export is written to the audit trail with the requesting user, the filters applied and the row count.",
  "rep.ranTitle": "Report queued",
  "rep.ranBody": "In the real system this returns a run identifier and delivers the result by notification.",

  "apr.title": "Approvals",
  "apr.subtitle": "Discounts, refunds, purchase orders, waste, counts, expenses and price changes.",
  "apr.kind": "Type",
  "apr.entity": "Subject",
  "apr.requested": "Requested",
  "apr.expires": "Expires",
  "apr.requiredPermission": "Required permission",
  "apr.decision": "Decision",
  "apr.comment": "Comment",
  "apr.decidedBy": "Decided by",
  "apr.approveConfirm": "Approve this request?",
  "apr.rejectConfirm": "Reject this request?",
  "apr.cannotSelfApprove": "You cannot approve a request you raised.",
  "apr.noPermission": "Your role does not hold the permission this request requires.",
  "apr.queue": "Pending queue",
  "apr.history": "History",
  "apr.queueEmpty": "Nothing waiting for a decision",
  "apr.escalatedHint": "Requests that passed their first approver without a decision and moved up a level.",
  "apr.commentHint": "Recorded with the decision in the audit trail.",
  "apr.expiryNote": "A request that expires is not silently approved — it lapses and must be raised again. A discount nobody got round to approving is a discount that was never approved.",

  "audit.title": "Audit log",
  "audit.subtitle": "Append-only and hash-chained. Access to the log is itself audited.",
  "audit.action": "Action",
  "audit.actor": "Actor",
  "audit.actorType": "Actor type",
  "audit.entity": "Entity",
  "audit.occurred": "Business time",
  "audit.recorded": "System time",
  "audit.impersonated": "Impersonated by",
  "audit.correlation": "Correlation ID",
  "audit.hash": "Hash",
  "audit.previousHash": "Previous hash",
  "audit.before": "Before",
  "audit.after": "After",
  "audit.chainVerified": "Chain verified",
  "audit.chainNote": "Each entry's hash covers its own content and the previous entry's hash, per tenant.",
  "audit.viewEntry": "View entry",

  "anom.title": "Anomaly flags",
  "anom.subtitle": "Every flag is a prompt for investigation, never an accusation.",
  "anom.evidence": "Evidence",
  "anom.observed": "Observed",
  "anom.baseline": "Baseline",
  "anom.sigma": "Deviation",
  "anom.detected": "Detected",
  "anom.severity": "Severity",
  "anom.subject": "Subject",
  "anom.dismiss": "Dismiss",
  "anom.confirm": "Confirm for investigation",

  // -- Users, roles, settings ---------------------------------------------
  "usr.title": "Users",
  "usr.subtitle": "Credentials and role assignments. Assignments carry a scope and may expire.",
  "usr.email": "Email",
  "usr.phone": "Phone",
  "usr.mfa": "MFA",
  "usr.mfaEnrolled": "Enrolled",
  "usr.mfaMissing": "Not enrolled",
  "usr.lastLogin": "Last sign-in",
  "usr.assignments": "Role assignments",
  "usr.scopeLevel": "Scope",
  "usr.validity": "Valid",
  "usr.temporary": "Temporary elevation",
  "usr.linkedEmployee": "Linked employee",
  "usr.forceLogout": "Sign out everywhere",
  "usr.locale": "Interface language",

  "role.title": "Roles",
  "role.subtitle": "RBAC for what, ABAC for where. Predefined roles may be cloned but not deleted.",
  "role.system": "Predefined",
  "role.custom": "Custom",
  "role.users": "Users",
  "role.permissionCount": "Permissions",
  "role.defaultScope": "Default scope",
  "role.editor": "Permission editor",
  "role.sensitive": "Sensitive",
  "role.sodTitle": "Segregation of duties",
  "role.sodSubtitle": "Incompatible permission pairs held by the same user.",
  "role.sodBlocking": "Blocked",
  "role.sodWarning": "Warned",
  "role.sodRisk": "Risk",
  "role.clone": "Clone role",
  "role.noConflicts": "No segregation-of-duties conflicts in this tenant.",

  "set.title": "Settings",
  "set.subtitle": "Values resolve through a cascade. A lower level overrides a higher one unless locked.",
  "set.cascade": "Configuration cascade",
  "set.cascadeNote": "Platform default → country pack → tenant → brand → branch → terminal.",
  "set.effectiveValue": "Effective value",
  "set.suppliedBy": "Supplied by",
  "set.locked": "Locked",
  "set.lockedAt": "Locked at",
  "set.general": "General",
  "set.localisation": "Localisation",
  "set.pos": "POS & KDS",
  "set.thresholds": "Approval thresholds",
  "set.demo": "Demo controls",
  "set.security": "Security",
  "set.demoNote": "These switches exercise the loading, empty and error states without a backend.",
  "set.dataMode": "Data mode",
  "set.dataNormal": "Normal",
  "set.dataEmpty": "Empty responses",
  "set.dataError": "Service error",
  "set.dataSlow": "Slow network",
  "set.posSettings": "Point of sale",
  "set.kdsSettings": "Kitchen display",
  "set.autoFire": "Fire to kitchen automatically on line entry",
  "set.blindCount": "Blind cash count at shift close",
  "set.blindStockCount": "Blind stock count by default",
  "set.requireTable": "Require table assignment before firing",
  "set.staggerRelease": "Prep-time-aware staggered release",
  "set.bumpConfirm": "Require a deliberate interaction to bump",
  "set.ticketTarget": "Ticket target time",
  "set.discountLimit": "Maximum discount without approval",
  "set.wasteThreshold": "Waste approval threshold",
  "set.varianceTolerance": "Count variance tolerance",
  "set.cashTolerance": "Cash variance tolerance",
  "set.poTier1": "PO approval tier 1 ceiling",
  "set.poTier2": "PO approval tier 2 ceiling",
  "set.sessionIdle": "Dashboard idle timeout",
  "set.minutes": "minutes",
  "set.seconds": "seconds",

  "cp.title": "Country packs",
  "cp.subtitle": "Jurisdiction-specific behaviour is data, not code. Packs are signed and versioned.",
  "cp.version": "Version",
  "cp.effectiveFrom": "Effective from",
  "cp.signed": "Signed",
  "cp.unsigned": "Unsigned",
  "cp.taxEngine": "Tax engine",
  "cp.pricingMode": "Pricing mode",
  "cp.rounding": "Rounding",
  "cp.computationLevel": "Tax computed at",
  "cp.taxClasses": "Tax classes",
  "cp.fiscal": "Fiscal provider",
  "cp.weekStart": "Week starts",
  "cp.weekend": "Weekend",
  "cp.weeklyHours": "Standard weekly hours",
  "cp.overtimeMultiplier": "Overtime multiplier",
  "cp.retention": "Data retention",
  "cp.conformance": "Conformance suite",
  "cp.conformancePassed": "Passed",
  "cp.conformanceFailed": "Not passed",
  "cp.activationBlocked": "A pack cannot be activated in production until it passes the conformance suite and is signed.",
  "cp.years": "years",
  "cp.branchesUsing": "Branches using this pack",
  "cp.cannotActivate": "Cannot be activated",

  "int.title": "Integrations",
  "int.subtitle": "Connector health is visible: last success, error rate, and queue depth.",
  "int.vendor": "Vendor",
  "int.lastSuccess": "Last success",
  "int.errorRate": "Error rate",
  "int.queueDepth": "Queue depth",
  "int.circuitOpen": "Circuit breaker open",
  "int.circuitNote": "After a failure threshold, calls are suspended and queued, with periodic probing for recovery.",
  "int.configure": "Configure",
  "int.enable": "Enable",
  "int.disable": "Disable",
  "int.rotate": "Rotate credentials",
  "int.branchesConnected": "Branches connected",
  "int.category": "Category",
  "int.healthy": "Healthy",
  "int.unhealthy": "Degraded or failing",
  "int.queueHint": "Calls held back while a connector is unavailable. The queue drains on recovery — it is deferred work, not lost work.",
  "int.notConfiguredNote": "Nobody has set this connector up. That is different from switching it off: an unconfigured tax connector goes unnoticed until a filing deadline.",
  "int.aclNote": "Every connector sits behind an anti-corruption layer, so a vendor changing their payload shape is a change in one adapter rather than throughout the domain.",

  "common.type": "Type",

  // -- Morning brief, added -----------------------------------------------
  "dash.briefTitle": "Morning brief",
  "dash.briefHint": "The prior business day in a form readable on a phone in under 30 seconds — exceptions first, not totals.",
  "dash.briefAllClear": "Nothing is outside tolerance. Every tracked metric is at or under its target and no alert is open.",
  "dash.briefOverTarget": "over target",
  "dash.briefWatchBranch": "needs attention — furthest from the group mean",
  "dash.briefAlerts": "open alerts, of which",
  "dash.briefCritical": "critical or high",
  "dash.briefNothingToday": "No branch is more than 1.5σ from the group mean.",

  // -- Auth shell, added ---------------------------------------------------
  "auth.brandLine": "Every sale is a transaction against the entire business, not merely against the cash drawer.",
  "auth.brandSub": "The management console for a restaurant operating system: sales, kitchen, recipes, inventory, purchasing, staff, cash and tax on one clock.",
  "auth.pointOffline": "Seventy-two hours of trading with no server, then a sync that loses nothing and duplicates nothing.",
  "auth.pointArabic": "Arabic and English are first-class on every surface — authored right-to-left, mirrored to English.",
  "auth.pointAudit": "Every state-changing operation writes a hash-chained audit entry that tampering cannot hide.",
  "auth.docNote": "ROS-SRS-001 v1.0 · 212 functional · 148 non-functional",
  "auth.backToSite": "Back to the site",

  // -- Users and roles, added -------------------------------------------
  "common.notInBuild": "Specified in the baseline, not implemented in this build.",
  "common.actionFailed": "That did not go through. The backend rejected it.",
  "terminals.revoked": "Terminal revoked. It can no longer take orders or payments.",
  "common.invite": "Invite user",
  "common.never": "Never",
  "common.role": "Role",
  "usr.employeeNote": "A user is a credential; an employee is a person in a job. They are separate records with an optional link, because conflating them produces a permission model that can express neither.",
  "usr.searchPlaceholder": "Search by name, email or phone",
  "usr.mfaRequiredMissing": "Required, not enrolled",
  "usr.scopeNote": "Effective permissions are the union across assignments, evaluated within each assignment's own scope.",
  "usr.scopeAll": "Whole level",
  "role.surfaces": "Surfaces",
  "role.mfaRequired": "MFA mandatory",
  "role.searchPlaceholder": "Search roles",
  "role.permissionsIn": "permissions",
  "role.blockedNote": "Blocked combinations are refused outright regardless of role configuration — FR-SEC-016.",
  "role.cloneNote": "Predefined roles ship ready to use. A tenant may clone and modify one, but never delete it — FR-SEC-010.",

  // -- Live console framing ------------------------------------------------
  "live.title": "Live",
  "live.note": "Everything below comes from the terminals on this device. Take an order on the POS and it lands here as it happens — sales, kitchen tickets, stock movements and the cash drawer.",
  "live.empty": "Nothing yet.",
  "live.emptyBody": "Open the point of sale, declare a float and take an order. It will appear here the moment it is rung up.",
  "live.openPos": "Open the POS",
  "live.openKds": "Open the kitchen display",
  "live.todayOnDevice": "On this device today",
  "live.seededNote": "The seeded ledger from before this shift is unchanged; these figures are what the terminals have added to it.",
  "nav.terminalsGroup": "Terminals",
  "nav.pos": "Point of sale",
  "nav.kds": "Kitchen display",
  "nav.notBuilt": "Not in this build",
  "nav.notBuiltHint": "This module is specified but not implemented here. The operational core — sale, kitchen, stock, drawer — is.",

  // -- Terminals: shared chrome -------------------------------------------
  "term.pos": "Point of sale",
  "term.kds": "Kitchen display",
  "term.console": "Console",
  "term.branch": "Branch",
  "term.terminal": "Terminal",
  "term.station": "Station",
  "term.allStations": "All stations",
  "term.pass": "Pass",
  "term.reset": "Reset terminal",
  "term.resetConfirm": "Clear every order, ticket, drawer and stock movement made on this device and start the shift again?",
  "term.resetNote": "Master data — menu, recipes, branches, employees — is untouched. Only the work this terminal has done is cleared.",
  "term.offline": "Working locally",
  "term.offlineNote": "This build has no server. Orders, tickets, stock and the cash drawer live in this browser and sync between tabs, so the POS and the kitchen display talk to each other.",
  "term.loading": "Starting terminal",

  // -- Shift and drawer ----------------------------------------------------
  "shift.title": "Shift",
  "shift.none": "No shift is open",
  "shift.noneLede": "A cashier declares the opening float before the first sale. Until then the terminal will not take an order.",
  "shift.open": "Open shift",
  "shift.cashier": "Cashier",
  "shift.openingFloat": "Opening float",
  "shift.floatInvalid": "Enter the opening float as a number.",
  "shift.countInvalid": "One or more counts is not a number. Correct them before closing.",
  "shift.openedAt": "Opened",
  "shift.cashSales": "Cash sales",
  "shift.cashRefunds": "Cash refunds",
  "shift.payIn": "Pay in",
  "shift.payOut": "Pay out",
  "shift.safeDrop": "Safe drop",
  "shift.drawerOps": "Drawer",
  "shift.amount": "Amount",
  "shift.reason": "Reason",
  "shift.record": "Record",
  "shift.expected": "Expected in drawer",
  "shift.xReport": "X report",
  "shift.xReportNote": "Non-resetting mid-shift summary. The drawer keeps running.",
  "shift.close": "Close shift",
  "shift.countDrawer": "Count the drawer",
  "shift.blindNote": "Blind count. The expected figure stays hidden until you have entered every denomination — a cashier who can see the target can count it rather than the cash.",
  "shift.denomination": "Denomination",
  "shift.count": "Count",
  "shift.countedTotal": "Counted",
  "shift.variance": "Variance",
  "shift.varianceOver": "Over",
  "shift.varianceShort": "Short",
  "shift.varianceReason": "Variance reason",
  "shift.acknowledge": "Manager acknowledgement",
  "shift.acknowledgeHint": "A variance past tolerance needs a named manager against it.",
  "shift.confirmClose": "Close and hand over",
  "shift.drawerLimit": "Drawer is over its limit — record a safe drop.",
  "shift.closed": "Shift closed",
  "shift.ordersTaken": "Orders",
  "shift.tenderBreakdown": "By tender",
  "shift.summary": "Shift summary",
  "shift.grossSales": "Gross sales",
  "shift.netSales": "Net sales",
  "shift.cardSales": "Card sales",
  "shift.otherSales": "Other payment methods",
  "shift.refunds": "Refunds",
  "shift.cancelledOrders": "Cancelled orders",
  "shift.deposits": "Deposits",
  "shift.withdrawals": "Withdrawals",
  "shift.balanced": "Balanced",
  "shift.closingCash": "Closing cash",

  // -- POS -----------------------------------------------------------------
  "pos.newOrder": "New order",
  "pos.orderType": "Order type",
  "pos.floorPlan": "Floor",
  "pos.openOrders": "Open orders",
  "pos.menu": "Menu",
  "pos.searchItems": "Search items, barcode or PLU",
  "pos.searchNote": "Arabic search ignores tashkeel and treats أ إ آ ا as one letter.",
  "pos.allCategories": "All",
  "pos.favourites": "Quick keys",
  "pos.noItems": "Nothing matches that search.",
  "pos.eightySix": "86",
  "pos.eightySixed": "86'd",
  "pos.eightySixReason": "Why is it off?",
  "pos.restore": "Bring back",
  "pos.overrideOnce": "Approve for this order",
  "pos.overrideApprover": "Manager approving",
  "pos.overrideChoose": "Choose a manager",
  "pos.overrideNote":
    "Lets this item onto the order in hand only. It stays 86'd for every other order on this terminal.",
  "pos.overrideActive": "Approved for this order",
  "pos.overrideActiveNote":
    "A manager has cleared this item for the open order. The 86 is still in force everywhere else.",
  "pos.remaining": "{n} left",
  "pos.noRecipe": "No recipe",
  "pos.selectTable": "Pick a table",
  "pos.tableRequired": "A dine-in order needs a table before it can be fired.",
  "pos.guests": "Guests",
  "pos.area": "Area",
  "pos.seats": "seats",
  "pos.emptyOrder": "No lines yet. Pick something from the menu.",
  "pos.startPrompt": "Start an order, or pick up one that is already open.",
  "pos.course": "Course",
  "pos.seat": "Seat",
  "pos.lineNote": "Kitchen note",
  "pos.noteChips": "Common notes",
  "pos.subtotal": "Subtotal",
  "pos.discountTotal": "Discounts",
  "pos.serviceCharge": "Service charge",
  "pos.tax": "Tax",
  "pos.taxIncluded": "included",
  "pos.rounding": "Cash rounding",
  "pos.total": "Total",
  "pos.paid": "Paid",
  "pos.balance": "Balance",
  "pos.fire": "Send to kitchen",
  "pos.fireCourse": "Send course {n}",
  "pos.fired": "Sent",
  "pos.park": "Park",
  "pos.parked": "Parked",
  "pos.resume": "Resume",
  "pos.pay": "Pay",
  "pos.cancelOrder": "Cancel order",
  "pos.cancelReason": "Why is the order being cancelled?",
  "pos.moveTable": "Move table",
  "pos.void": "Void",
  "pos.voidReason": "Void reason",
  "pos.voidPreFire": "Nothing has been made yet, so the line simply comes off the bill.",
  "pos.voidPostFire": "The kitchen already made this. Say where the food went.",
  "pos.disposition": "Where did it go?",
  "pos.dispositionReturn": "Back into stock",
  "pos.dispositionWaste": "Wasted",
  "pos.dispositionStaff": "Given to staff",
  "pos.dispositionNote": "Unclassified voids reappear later as unexplained variance, and nobody records them after the fact.",
  "pos.comp": "Comp",
  "pos.compNote": "A comp gives the item away: revenue is zero, but the cost is still recognised and the stock is still gone.",
  "pos.discount": "Discount",
  "pos.discountLine": "Discount this line",
  "pos.discountOrder": "Discount the order",
  "pos.discountPercent": "Percentage",
  "pos.discountAmount": "Amount",
  "pos.discountReason": "Reason",
  "pos.needsApproval": "Above {n}% a manager has to approve.",
  "pos.approver": "Approving manager",
  "pos.apply": "Apply",
  "pos.modifiers": "Options",
  "pos.required": "Required",
  "pos.chooseAtLeast": "Choose at least {n}",
  "pos.chooseUpTo": "Choose up to {n}",
  "pos.addToOrder": "Add to order",
  "pos.variant": "Size",
  "pos.quantity": "Quantity",
  "pos.payment": "Payment",
  "pos.tender": "Tender",
  "pos.tendered": "Cash tendered",
  "pos.changeDue": "Change due",
  "pos.amountPaid": "Amount paid",
  "pos.splitEqually": "Split equally",
  "pos.parties": "Ways",
  "pos.takePayment": "Take payment",
  "pos.settle": "Settle",
  "pos.paymentDone": "Order completed",
  "pos.receipt": "Receipt",
  "pos.printReceipt": "Print",
  "pos.newOrderAfter": "Next order",
  "pos.refund": "Refund",
  "pos.refundAmount": "Refund amount",
  "pos.refundReason": "Refund reason",
  "pos.refundReturnStock": "Put the ingredients back into stock",
  "pos.refundNote": "Refunds go back to the original tender and can never exceed what was taken.",
  "pos.recent": "Completed today",
  "pos.priceFrom": "Priced from {source}",
  "pos.priceBase": "base price",
  "pos.priceList": "price list",
  "pos.priceOverride": "manual override",

  // -- KDS -----------------------------------------------------------------
  "kds.title": "Kitchen display",
  "kds.queue": "Queue",
  "kds.noTickets": "Nothing on this station.",
  "kds.noTicketsNote": "Tickets arrive here the moment the POS fires a course.",
  "kds.bump": "Bump",
  "kds.bumpAll": "Bump ticket",
  "kds.holdToBump": "Hold to bump",
  "kds.bumpNote": "Bumping needs a deliberate hold. Kitchen screens get touched by elbows, sleeves and water.",
  "kds.start": "Start",
  "kds.started": "Being made",
  "kds.waiting": "Nobody on it yet",
  "kds.waitTotal": "Guest waiting",
  "kds.cookTime": "Cooking",
  "kds.pickup": "Sat in queue",
  "kds.recall": "Recall",
  "kds.recalled": "Recalled",
  "kds.allDay": "All day",
  "kds.allDayNote": "Everything outstanding at this station, added up.",
  "kds.elapsed": "Elapsed",
  "kds.target": "Target",
  "kds.onTarget": "On target",
  "kds.approaching": "Approaching",
  "kds.exceeded": "Over",
  "kds.critical": "Critical",
  "kds.rush": "Rush",
  "kds.vip": "VIP",
  "kds.remake": "Amended",
  "kds.amended": "Items added",
  "kds.voidedLine": "Cancelled — stop making this",
  "kds.orderCancelled": "ORDER CANCELLED",
  "kds.stopMaking": "Stop making this order.",
  "kds.cancelReason": "Reason",
  "kds.ackCancel": "Got it — clear",
  "kds.passTitle": "Pass",
  "kds.passNote": "Orders assemble here once every station has finished.",
  "kds.ready": "Ready to assemble",
  "kds.waitingOn": "Waiting on {stations}",
  "kds.serve": "Served",
  "kds.sortBy": "Sort",
  "kds.sortOldest": "Oldest first",
  "kds.sortTarget": "By target time",
  "kds.sortCourse": "By course",
  "kds.bottleneck": "Busiest station",
  "kds.avgTicket": "Average ticket time",

  // -- Forms ---------------------------------------------------------------
  "form.required": "required",
  "form.optional": "Optional",
  "form.errorCount": "{n} fields need attention before this can be saved.",
  "form.saving": "Saving",
  "form.saved": "Saved",
  "form.save": "Save",
  "form.cancel": "Cancel",
  "form.back": "Back",
  "form.next": "Next",
  "form.finish": "Finish",
  "form.skip": "Skip this step",
  "form.discard": "Discard changes",
  "form.keepEditing": "Keep editing",
  "form.unsavedTitle": "You have unsaved changes",
  "form.unsavedBody": "Leaving now discards everything typed since the last save. This cannot be undone.",
  "form.addRow": "Add",
  "form.removeRow": "Remove",
  "form.retry": "Try again",
  "form.readOnly": "Read only",
  "form.readOnlyWhy": "Your role can view this record but not change it.",

  // -- Validation ----------------------------------------------------------
  "validation.invalid": "This value is not valid.",
  "validation.required": "This field is required.",
  "validation.email": "Enter a valid email address, for example name@restaurant.com.",
  "validation.phone": "Enter a valid phone number, digits and + only.",
  "validation.minLength": "Use at least {n} characters.",
  "validation.maxLength": "Use no more than {n} characters.",
  "validation.minValue": "Enter {n} or more.",
  "validation.maxValue": "Enter {n} or less.",
  "validation.positive": "Enter a number greater than zero.",
  "validation.nonNegative": "This cannot be negative.",
  "validation.integer": "Enter a whole number.",
  "validation.digits": "Enter exactly {n} digits.",
  "validation.passwordWeak": "Include an uppercase letter, a lowercase letter and a digit.",
  "validation.passwordMismatch": "The two passwords do not match.",
  "validation.passwordReused": "The new password must differ from the current one.",
  "validation.url": "Enter a valid web address.",
  "validation.date": "Enter a valid date.",
  "validation.dateOrder": "The end date cannot come before the start date.",
  "validation.atLeastOne": "Choose at least one.",
  "validation.duplicate": "This value is already in use.",
  "validation.arabicRequired": "An Arabic name is required.",
  "validation.englishRequired": "An English name is required.",
  "validation.currencyMismatch": "These amounts are in different currencies and cannot be added.",
  "validation.percentRange": "Enter a percentage between 0 and 100.",

  // -- Authentication, continued -------------------------------------------
  "auth.forgotTitle": "Reset your password",
  "auth.forgotLede": "Enter the email you sign in with. If it matches an account, a reset link is sent to it.",
  "auth.forgotSubmit": "Send reset link",
  "auth.forgotSentTitle": "Check your email",
  "auth.forgotSentBody": "If an account exists for that address, a reset link is on its way. The link is valid for 30 minutes and can be used once.",
  "auth.forgotDemoNote": "Demo build: no email is sent. Continue to the reset screen to see it.",
  "auth.continueToReset": "Continue to reset screen",
  "auth.backToSignIn": "Back to sign in",
  "auth.resetTitle": "Choose a new password",
  "auth.resetLede": "This signs you out of every other device.",
  "auth.resetNoToken": "This reset link is incomplete. Request a new one — the link in the email carries a single-use token that this page needs.",
  "auth.changePassword": "Change password",
  "auth.currentPassword": "Current password",
  "auth.changePasswordDemo": "Demo mode has no account store, so there is no password to change. Point NEXT_PUBLIC_API_URL at the backend to use this.",
  "auth.errorCurrentPassword": "That is not the current password.",
  "auth.resetDone": "Password changed. Sign in with the new one.",
  "auth.passwordChanged": "Password changed. Every other session has been signed out.",
  "auth.newPassword": "New password",
  "auth.confirmPassword": "Confirm new password",
  "auth.resetSubmit": "Set password and sign in",
  "auth.passwordRules": "Password must contain",
  "auth.ruleLength": "At least 12 characters",
  "auth.ruleCase": "An uppercase and a lowercase letter",
  "auth.ruleDigit": "At least one digit",
  "auth.demoAccounts": "Demo accounts",
  "auth.demoAccountsHint": "One sign-in per role. Every account uses the same password, shown below. Selecting a row fills the form.",
  "auth.demoPassword": "Password for every demo account",
  "auth.pinLabel": "Terminal PIN",
  "auth.use": "Use",
  "auth.copied": "Copied",
  "auth.errorUnknownEmail": "No account uses that email address.",
  "auth.errorBadPassword": "That password is not correct.",
  "auth.errorLocked": "Too many failed attempts. This account is locked until an administrator releases it.",
  "auth.attemptsLeft": "{n} attempts left before this account locks.",
  "auth.mfaCodeHint": "Demo code",

  "auth.selectTenantTitle": "Choose an organisation",
  "auth.selectTenantLede": "Your account has access to more than one organisation. Everything you see afterwards is scoped to the one you pick.",
  "auth.selectBrandTitle": "Choose a brand",
  "auth.selectBrandLede": "Reports, menus and prices differ per brand. You can change this later from the header.",
  "auth.selectBranchTitle": "Choose a branch",
  "auth.selectBranchLede": "Pick where you are working today. Live operations, cash and stock all follow this choice.",
  "auth.allBrands": "All brands",
  "auth.allBranches": "All branches",
  "auth.continue": "Continue",
  "auth.branchCount": "{n} branches",
  "auth.scopeLocked": "Your role is assigned to a single branch, so this cannot be changed.",

  "auth.sessionExpiredTitle": "Your session has ended",
  "auth.sessionExpiredBody": "You were signed out after a period of inactivity. This protects the till and the cash drawer when a device is left unattended.",
  "auth.sessionExpiredWhat": "Nothing you saved has been lost. Any order left open on a terminal is still open.",
  "auth.signInAgain": "Sign in again",

  "auth.accessDeniedTitle": "You do not have access to this page",
  "auth.accessDeniedBody": "Your role does not hold the permission this page requires. Nothing was changed and this attempt has been recorded in the audit log.",
  "auth.accessDeniedNeeds": "Required permission",
  "auth.accessDeniedRole": "Your role",
  "auth.requestAccess": "Request access",
  "auth.requestSent": "A request has been sent to your administrator.",
  "auth.goBack": "Go back",
  "auth.goHome": "Go to my dashboard",

  "auth.deviceTitle": "Register this device",
  "auth.deviceLede": "A terminal must be registered against a branch before it can take an order or open a drawer.",
  "auth.deviceName": "Device name",
  "auth.deviceNameHint": "How this terminal appears in reports, for example \"Front till 2\".",
  "auth.pairingCode": "Pairing code",
  "auth.pairingHint": "Eight digits, issued in Settings › Terminals by a manager.",
  "auth.deviceType": "Device type",
  "auth.deviceBranch": "Branch",
  "auth.printerAttached": "A receipt printer is attached",
  "auth.registerDevice": "Register device",
  "auth.deviceRegisteredTitle": "Device registered",
  "auth.deviceRegisteredBody": "This terminal is now paired. Its identifier is included on every transaction it records.",
  "auth.deviceId": "Device identifier",
  "auth.deviceKiosk": "Self-order kiosk",
  "auth.deviceLedeLive": "Bind this device to one of the tenant's registered terminals. Every order and payment it takes will be recorded against that terminal.",
  "auth.deviceNeedsSession": "Registering a terminal is an authorised action. Sign in first, then come back here.",
  "auth.deviceNoTerminals": "No terminals are registered to this tenant yet. Add the first one below.",
  "auth.deviceRegisterNew": "Register a new terminal",
  "auth.deviceDemoNote": "No backend is configured, so nothing was paired. Set NEXT_PUBLIC_API_URL and register again to bind this terminal for real.",
  "auth.openPos": "Open the point of sale",

  "auth.posPinTitle": "Enter your PIN",
  "auth.posPinLede": "Four digits. Ask a supervisor if you have forgotten yours.",
  "auth.pinWrong": "That PIN was not recognised.",
  "auth.pinClear": "Clear",
  "auth.switchUser": "Switch user",
  "auth.signedInAs": "Signed in as",

  // -- Onboarding ----------------------------------------------------------
  "onb.title": "Set up your restaurant",
  "onb.lede": "Fifteen steps from an empty account to a first order. You can leave at any point and come back to where you stopped.",
  "onb.stepOf": "Step {n} of 15",
  "onb.saveAndExit": "Save and continue later",
  "onb.savedDraft": "Progress saved. Sign back in to continue.",
  "onb.resume": "Resume setup",
  "onb.restart": "Start again",
  "onb.completed": "Done",
  "onb.current": "In progress",
  "onb.upcoming": "Not started",
  "onb.skipped": "Skipped",
  "onb.optional": "Optional",
  "onb.example": "Example",
  "onb.importMenu": "Import from a spreadsheet instead",
  "onb.importMenuHint": "Upload a CSV with columns: category, name (English), name (Arabic), price. A template is available.",
  "onb.importPreview": "{n} rows read",
  "onb.downloadTemplate": "Download template",

  "onb.tenantTitle": "Create your organisation",
  "onb.tenantLede": "The organisation is the top of the tree. Brands, branches, staff and every report sit under it.",
  "onb.tenantNameEn": "Organisation name (English)",
  "onb.tenantNameAr": "Organisation name (Arabic)",
  "onb.country": "Country of operation",

  "onb.businessTitle": "Business details",
  "onb.businessLede": "Used on receipts, tax filings and supplier documents. You can complete this later, but receipts will show a placeholder until you do.",
  "onb.legalName": "Registered legal name",
  "onb.taxNumber": "Tax registration number",
  "onb.commercialReg": "Commercial registration number",
  "onb.addressLine": "Street address",
  "onb.city": "City",
  "onb.contactPhone": "Contact phone",
  "onb.contactEmail": "Contact email",

  "onb.brandTitle": "Create your first brand",
  "onb.brandLede": "A brand owns a menu and a price list. Groups running more than one concept keep them apart here.",
  "onb.brandNameEn": "Brand name (English)",
  "onb.brandNameAr": "Brand name (Arabic)",
  "onb.concept": "Concept",
  "onb.conceptCasual": "Casual dining",
  "onb.conceptQsr": "Quick service",
  "onb.conceptCafe": "Café",
  "onb.conceptCloud": "Cloud kitchen",
  "onb.conceptFine": "Fine dining",
  "onb.accentColour": "Brand colour",

  "onb.branchTitle": "Add your first branch",
  "onb.branchLede": "A branch is a physical place that trades. Stock, cash and staff all belong to one.",
  "onb.branchNameEn": "Branch name (English)",
  "onb.branchNameAr": "Branch name (Arabic)",
  "onb.seats": "Number of seats",
  "onb.seatsHint": "Zero for a delivery-only or cloud kitchen.",
  "onb.orderTypes": "Order types this branch accepts",

  "onb.localeTitle": "Country and currency",
  "onb.localeLede": "The country pack decides the tax engine, rounding, week start and receipt requirements. It cannot be changed after the first sale.",
  "onb.currency": "Currency",
  "onb.timezone": "Time zone",
  "onb.defaultLocale": "Default interface language",
  "onb.numerals": "Use Arabic-Indic numerals (٠١٢٣)",
  "onb.numeralsHint": "Affects display only. Values are stored the same either way.",

  "onb.taxTitle": "Tax settings",
  "onb.taxLede": "Whether menu prices already include tax changes every total in the system. Confirm it against how you price today.",
  "onb.pricingMode": "Menu prices are",
  "onb.taxInclusive": "Tax inclusive — the shelf price is what the customer pays",
  "onb.taxExclusive": "Tax exclusive — tax is added at the till",
  "onb.standardRate": "Standard rate (%)",
  "onb.reducedRate": "Reduced rate (%)",
  "onb.roundingMode": "Rounding",
  "onb.computationLevel": "Calculate tax per",
  "onb.perLine": "Line",
  "onb.perOrder": "Order",

  "onb.dayTitle": "Business day",
  "onb.dayLede": "A restaurant closing after midnight books those sales against the day it opened. Set the hour the trading day ends.",
  "onb.closingTime": "Business day ends at",
  "onb.closingHint": "Sales taken before this time count towards the previous date.",
  "onb.weekStart": "Week starts on",
  "onb.autoClose": "Close the business day automatically at this time",

  "onb.categoriesTitle": "Menu categories",
  "onb.categoriesLede": "The top row of buttons on the till. Four to eight works best on a ten-inch screen.",
  "onb.addCategory": "Add category",
  "onb.categoryNameEn": "Category name (English)",
  "onb.categoryNameAr": "Category name (Arabic)",

  "onb.itemsTitle": "Menu items",
  "onb.itemsLede": "Enough to take a real order. Recipes, modifiers and photographs can wait — an item sells without them.",
  "onb.addItem": "Add item",
  "onb.itemNameEn": "Item name (English)",
  "onb.itemNameAr": "Item name (Arabic)",
  "onb.itemCategory": "Category",
  "onb.itemPrice": "Price",
  "onb.itemTaxClass": "Tax class",
  "onb.itemPrep": "Preparation time (minutes)",
  "onb.taxStandard": "Standard",
  "onb.taxReduced": "Reduced",
  "onb.taxZero": "Zero rated",
  "onb.taxExempt": "Exempt",

  "onb.paymentsTitle": "Payment methods",
  "onb.paymentsLede": "What the till may accept. Anything switched off here does not appear on the payment screen.",
  "onb.cashRounding": "Round cash totals to",
  "onb.cashRoundingHint": "The smallest coin still in circulation. Card and wallet totals are never rounded.",

  "onb.employeeTitle": "Add your first employee",
  "onb.employeeLede": "Someone has to be able to open the till. You can add the rest of the team later.",
  "onb.employeeNameEn": "Full name (English)",
  "onb.employeeNameAr": "Full name (Arabic)",
  "onb.position": "Position",
  "onb.employeePin": "Terminal PIN (4 digits)",
  "onb.startDate": "Start date",
  "onb.assignRole": "Role",

  "onb.terminalTitle": "Register a terminal",
  "onb.terminalLede": "The device that will take the order. A pairing code is generated for it here.",
  "onb.terminalName": "Terminal name",
  "onb.cashDrawer": "A cash drawer is attached",

  "onb.previewTitle": "Review your configuration",
  "onb.previewLede": "Everything below can be changed later in Settings. Check the tax mode and the business day carefully — both are awkward to correct after trading starts.",
  "onb.previewEdit": "Edit",
  "onb.previewIncomplete": "Not set",

  "onb.shiftTitle": "Open the first shift",
  "onb.shiftLede": "Count the cash in the drawer and declare it. Every variance at close is measured against this number.",
  "onb.openingFloat": "Opening float",
  "onb.openShift": "Open shift",

  "onb.sampleTitle": "Take a sample order",
  "onb.sampleLede": "One order through the whole system: the till takes it, the kitchen sees it, stock moves, the drawer balances.",
  "onb.sampleRun": "Create the sample order",
  "onb.sampleRunning": "Sending to the kitchen",
  "onb.sampleDone": "Your first order is on the pass.",
  "onb.checklistTitle": "Setup checklist",
  "onb.checklistLede": "What is ready, and what is still worth doing before you open the doors.",
  "onb.goToConsole": "Go to the console",
  "onb.goToPos": "Open the point of sale",
  "onb.laterRecipes": "Add recipes so food cost and stock depletion work",
  "onb.laterSuppliers": "Add suppliers and place a first purchase order",
  "onb.laterStaff": "Add the rest of the team and build a schedule",
  "onb.laterStations": "Route items to kitchen stations",

  // -- Shell, search, notifications, sync ----------------------------------
  "shell.search": "Search",
  "shell.searchPlaceholder": "Search orders, items, suppliers, staff…",
  "shell.searchHint": "Press / to search, ⌘K for commands",
  "shell.noResults": "Nothing matched",
  "shell.noResultsHint": "Check the spelling, or widen the branch and date filters.",
  "shell.recent": "Recent",
  "shell.commands": "Commands",
  "shell.goTo": "Go to",
  "shell.notifications": "Notifications",
  "shell.noNotifications": "Nothing needs your attention",
  "shell.noNotificationsHint": "Alerts about cash variance, stock-outs and delayed orders appear here.",
  "shell.markAllRead": "Mark all as read",
  "shell.approvals": "Approvals",
  "shell.approvalsPending": "{n} waiting",
  "shell.noApprovals": "No approvals waiting",
  "shell.viewAll": "View all",
  "shell.businessDay": "Business day",
  "shell.dateRange": "Period",
  "shell.today": "Today",
  "shell.yesterday": "Yesterday",
  "shell.last7": "Last 7 days",
  "shell.last30": "Last 30 days",
  "shell.thisMonth": "This month",
  "shell.lastMonth": "Last month",
  "shell.custom": "Custom range",
  "shell.from": "From",
  "shell.to": "To",
  "shell.apply": "Apply",
  "shell.dismiss": "Dismiss",

  "sync.online": "Online",
  "sync.degraded": "Slow connection",
  "sync.offline": "Offline",
  "sync.syncing": "Synchronising",
  "sync.conflict": "Sync conflict",
  "sync.synced": "All synced",
  "sync.pending": "{n} waiting to send",
  "sync.queueTitle": "Pending changes",
  "sync.queueLede": "These were recorded on this device and have not reached the server yet. Nothing is lost — they send as soon as the connection returns.",
  "sync.queueEmpty": "Everything on this device has been sent.",
  "sync.lastSynced": "Last synced",
  "sync.retryNow": "Send now",
  "sync.conflictTitle": "This change conflicts with the server",
  "sync.conflictBody": "The record changed on the server while this device was offline. Choose which version to keep.",
  "sync.keepLocal": "Keep this device's version",
  "sync.keepServer": "Discard and keep the server's",
  "sync.offlineNote": "Working offline. Orders are saved on this device and sent when the connection returns.",
  "sync.simulate": "Simulate connection",
  "sync.statusPending": "Pending sync",
  "sync.statusFailed": "Sync failed",
  "menu.priceSaved": "Price saved.",
  "menu.priceListCreated": "Price list created.",
  "menu.priceHint": "Enter the shelf price, not minor units.",
  "menu.currentPrice": "Current price",
  "menu.newPriceList": "New price list",
  "menu.scopeTenant": "Whole tenant",
  "menu.scopeBrand": "One brand",
  "menu.scopeBranch": "One branch",
  "nav.menus": "Menus",
  "menu.menusTitle": "Menus",
  "menu.menusSubtitle": "Which menu each branch serves, and which one wins when several apply.",
  "menu.menuPriorityHint": "Highest priority in force wins. Give overlapping menus different priorities.",
  "menu.assignedBranches": "Assigned branches",
  "menu.noBranches": "Not assigned to any branch, so nothing serves it.",
  "menu.assignBranch": "Assign to branch",
  "menu.branchAssigned": "Branch assigned.",
  "menu.branchUnassigned": "Branch removed.",
  "menu.menuCreated": "Menu created.",
  "menu.menuActivated": "Menu activated.",
  "menu.menuDeactivated": "Menu deactivated.",
  "menu.newMenu": "New menu",
  "menu.ambiguousTitle": "Ambiguous resolution",
  "menu.ambiguousNote": "Two or more active menus share a priority on the same branch, so which one applies is not deterministic.",
  "menu.resolutionTitle": "What this branch resolves to",
  "menu.resolutionClear": "Resolution is unambiguous — the first menu below applies.",
  "common.branches": "branches",
  "common.remove": "Remove",
  "common.add": "Add",
  "common.activate": "Activate",
  "common.deactivate": "Deactivate",
  "menu.itemCreated": "Item created.",
  "menu.itemPlaced": "Category updated.",
  "menu.variantActivated": "Variant activated.",
  "menu.variantDeactivated": "Variant deactivated.",
  "menu.variantAdded": "Variant added.",
  "menu.groupLinked": "Modifier group attached.",
  "menu.noVariants": "No variants yet. An item needs at least one to be sellable.",
  "menu.newVariant": "New variant",
  "menu.newItem": "New item",
  "menu.barcode": "Barcode",
  "menu.variantPriceNote": "A new variant starts unpriced. Set its price on a price list before it can be sold.",
  "menu.placementHint": "An item is only reachable on a menu once it sits in a category.",
  "menu.attachGroup": "Attach a modifier group",
  "menu.attachGroupHint": "The API cannot list an item's attached groups, only add to them.",
  "menu.modifierGroups": "Modifier groups",
  "menu.kitchenNameHint": "The short name the line cook reads on the ticket.",
  "menu.category": "Category",
  "menu.groupCreated": "Modifier group created.",
  "menu.modifierAdded": "Modifier added.",
  "menu.noModifiers": "This group has no modifiers yet.",
  "menu.newModifier": "New modifier",
  "menu.newGroup": "New modifier group",
  "menu.modifierKindHint": "Decides how the line depletes stock — addition, removal or substitution.",
  "menu.minSelections": "Minimum selections",
  "menu.maxSelections": "Maximum selections",
  "role.newRole": "New role",
  "role.newRoleNote": "A new role starts with no permissions. Grant them from the role's editor once it exists.",
  "role.created": "Role created.",
  "role.assigned": "Role assigned.",
  "role.removed": "Role removed.",
  "role.assignRole": "Role",
  "role.membershipsTitle": "Your memberships",
  "role.membershipsNote": "The API exposes only the signed-in account's memberships, so roles can be assigned here for this account alone.",
  "common.description": "Description",
  "inv.countOpened": "Count session opened.",
  "inv.countPosted": "Count posted. Stock now matches what was counted.",
  "inv.countRecorded": "Counted quantity recorded.",
  "inv.countedHint": "What is actually on the shelf.",
  "inv.newCount": "Open a count",
  "inv.newCountNote": "Opening a session freezes the expected quantity for every item in scope, so a later movement cannot change what the count is measured against.",
  "inv.blindCount": "Blind count",
  "inv.transferDispatched": "Transfer dispatched.",
  "inv.transferReceived": "Transfer received.",
  "inv.newTransfer": "New transfer",
  "inv.dispatch": "Dispatch",
  "inv.sameLocation": "Choose a different destination.",
  "inv.quantity": "Quantity",
  "inv.item": "Item",
  "inv.reason": "Reason",
  "inv.reorderTitle": "At or below reorder point",
  "inv.reorderNote": "Computed by the backend against each location's reorder point, not filtered from the page above.",
  "inv.reorderClear": "Nothing is at its reorder point.",
  "inv.reorderQuantity": "Reorder quantity",
  "inv.reorderQuantityHint": "How much to order when the point is reached.",
  "inv.reorderPointHint": "Order again once on-hand falls to this.",
  "inv.reorderSaved": "Reorder configuration saved.",
  "inv.reorderConfigNote": "These thresholds are per item and per location, so a branch and a warehouse can reorder at different points.",
  "inv.negativeClear": "No location holds negative stock.",
  "inv.negativeAction": "Negative stock means a movement was recorded without its receipt. Find the missing receipt rather than adjusting the balance.",
  "inv.reconciliationTitle": "Ledger reconciliation",
  "inv.reconciliationNote": "The sum of movements against the stock-level projection they should equal.",
  "inv.reconciled": "The ledger and the projection agree.",
  "inv.notReconciled": "The ledger and the projection disagree. Every costing figure downstream is suspect until this is resolved.",
  "inv.ledger": "Ledger",
  "inv.projected": "Projected",
  "org.newBrand": "New brand",
  "org.brandCreated": "Brand created.",
  "org.newWarehouse": "New warehouse",
  "org.warehouseCreated": "Warehouse created.",
  "org.warehouseType": "Type",
  "org.warehouseCentral": "Central",
  "org.warehouseBranch": "Attached to a branch",
  "org.warehouseVirtual": "Virtual",
  "org.newKitchen": "New central kitchen",
  "org.kitchenCreated": "Central kitchen created.",
  "org.colour": "Colour",
  "menu.newCategory": "New category",
  "menu.categoryCreated": "Category created.",
  "inv.newItem": "New stock item",
  "inv.itemCreated": "Stock item created.",
  "inv.baseUnitId": "Base unit ID",
  "inv.baseUnitIdHint": "A real inventory.uom id. The API publishes no unit catalogue to pick from.",
  "inv.newItemUnitNote": "The base unit cannot be changed once any movement exists against the item (FR-INV-002), so choose it deliberately.",
  "inv.costingWeighted": "Weighted average",
  "inv.costingFifo": "FIFO",
  "inv.costingStandard": "Standard",
  "org.newBranch": "New branch",
  "org.branchCreated": "Branch created.",
  "org.reassignBrand": "Move to another brand",
  "org.reassignBrandHint": "Within the same tenant only.",
  "org.brandReassigned": "Branch moved to the new brand.",
  "org.operatingHours": "Operating hours",
  "org.noOperatingHours": "No opening hours are set for this branch.",
  "org.newOperatingHours": "Add opening hours",
  "org.operatingHoursAdded": "Opening hours added.",
  "org.dayOfWeek": "Day",
  "org.opensAt": "Opens at",
  "org.closesAt": "Closes at",
  "org.overnight": "Overnight",
  "org.printRouting": "Print routing",
  "org.noPrintRouting": "Nothing is routed to a printer yet.",
  "org.newPrintRouting": "Add print routing",
  "org.printRoutingAdded": "Print routing added.",
  "org.documentType": "Document",
  "org.docReceipt": "Receipt",
  "org.docKitchen": "Kitchen ticket",
  "org.docBar": "Bar ticket",
  "org.printerTarget": "Printer",
  "org.stationRouting": "Station routing",
  "org.noStationRouting": "No routing rules, so nothing reaches a station automatically.",
  "org.newStationRouting": "Add routing rule",
  "org.stationRoutingAdded": "Routing rule added.",
  "org.stationRoutingHint": "The most specific match at the highest priority wins. Leave the category empty for a catch-all.",
  "org.station": "Station",
  "common.sunday": "Sunday",
  "common.monday": "Monday",
  "common.tuesday": "Tuesday",
  "common.wednesday": "Wednesday",
  "common.thursday": "Thursday",
  "common.friday": "Friday",
  "common.saturday": "Saturday",
  "recipes.newRecipe": "New recipe",
  "recipes.newRecipeNote": "A recipe starts with no versions. Create a draft version, add its lines, then publish it.",
  "recipes.created": "Recipe created.",
  "recipes.published": "Version published. The previous one is now superseded.",
  "recipes.typeMenuItem": "Menu item",
  "recipes.typeSubRecipe": "Sub-recipe",
  "recipes.typeProduction": "Production item",
  "recipes.versions": "Versions",
  "recipes.noVersions": "No versions yet.",
  "recipes.substituteGroups": "Substitute groups",
  "recipes.substituteGroupsNote": "A recipe line can name a group instead of one ingredient, so a stock-out on one member does not make the recipe uncostable.",
  "recipes.noSubstituteGroups": "No substitute groups defined.",
  "recipes.newSubstituteGroup": "New substitute group",
  "recipes.substituteGroupCreated": "Substitute group created.",
  "recipes.addSubstituteMember": "Add a member",
  "recipes.substituteMemberAdded": "Member added.",
  "ops.tableDefinitions": "Floor plan",
  "ops.tableDefinitionsNote": "The tables a branch has. Live occupancy above is device state — the API models a table's label, section and seats, not what is happening on it.",
  "ops.noTables": "No tables are defined for this branch.",
  "ops.newTable": "New table",
  "ops.tableLabel": "Label",
  "ops.section": "Section",
  "ops.tableCreated": "Table created.",
  "ops.tableUpdated": "Table updated.",
  "pos.noTerminal": "This device is not bound to a terminal",
  "pos.noTerminalNote": "Every order and payment is recorded against a terminal, so the till cannot open until this device is bound to one.",
  "pos.orderOpened": "Order opened.",
  "pos.openOrder": "Open order",
  "pos.branchFromTerminal": "The branch comes from the bound terminal, not from the console's scope picker.",
  "pos.searchPlaceholder": "Search the menu",
  "pos.lineAdded": "Line added.",
  "pos.lineVoided": "Line voided.",
  "pos.noSellableVariant": "This item has no variants, so there is nothing to ring up. Add one on the menu screen.",
  "pos.noActiveOrder": "No order open.",
  "pos.noLines": "Nothing on the bill yet.",
  "pos.pending": "Not yet fired",
  "pos.capturePayment": "Capture payment",
  "pos.paymentCaptured": "Payment captured.",
  "pos.closeOrder": "Leave this order",
  "pos.voidReasonHint": "Required. The database refuses a voided line without one.",
  "pos.noReasonCodes": "No reason codes exist for this tenant, so a line cannot be voided. Add one under Inventory.",
  "pos.partialOnlyNote": "The backend accepts partial payments only — a payment that would settle the order in full is refused, because order Completion is not implemented yet.",
  "pos.tenderedHint": "What the guest handed over. The server derives the cash rounding from this.",
  "pos.terminalRefHint": "Your own record of the already-completed external card transaction.",
  "pos.unsupportedTitle": "Not available against this backend",
  "pos.unsupportedNote": "These are shown rather than hidden, because a till that appears to take a discount and does not is worse than one that says it cannot.",
  "pos.unsupportedDiscount": "Discounts and price overrides — no endpoint.",
  "pos.unsupportedComp": "Comps — no endpoint.",
  "pos.unsupportedSplit": "Split bills and full settlement — Completion is not implemented.",
  "pos.unsupportedRefund": "Refunds and post-fire voids — no endpoint.",
  "pos.unsupportedTable": "Table state and moving an order between tables — not modelled.",
  "pos.unsupportedCourse": "Courses, seat numbers and line notes after capture — no endpoint.",
  "pos.unsupportedKds": "Kitchen display bump and recall — no endpoint.",
  "shift.openTitle": "Open the drawer",
  "shift.drawer": "Drawer",
  "shift.openingFloatHint": "The cash counted into the drawer at the start of the shift.",
  "orders.outstanding": "Outstanding",
  "orders.amount": "Amount",
  "orders.tendered": "Tendered",
  "orders.terminalReference": "Terminal reference",
  "orders.card": "Card (external terminal)",
  "orders.net": "Subtotal",
  "orders.grandTotal": "Total",
} as const;

export type ConsoleCopy = Record<keyof typeof consoleEn, string>;
export type ConsoleKey = keyof typeof consoleEn;
